In [3]:
# imports
import numpy as np
import pandas as pd

from collections import defaultdict
from operator import itemgetter
from os import path

from common.county_geometry import central_angle
from common.county_geometry import earth_radius_mi

In [4]:
# bring in intersections -> DataFrame intersections 
intersection_data_path = "./data/cleaner/intersections_clean.json"

grid_column = "KY_grid_XY"
# I've changed this a few times and it's getting annoying to change it everytime :)

# import intersection data
def read_in_intersections(path_to_intersection_data):
    df = pd.read_json(path_to_intersection_data, orient='records', lines=True)
    df['GEOMETRY'] = df.GEOMETRY.apply(np.array)
    df[grid_column] = df[grid_column].apply(np.array)
    return df.set_index("INTID")       

intersections = read_in_intersections(intersection_data_path).drop([grid_column], axis=1)

#intersections.GEOMETRY = intersections.GEOMETRY.apply(np.array)
#intersections.GEOMETRY.iloc[0] # == array([-85.51043903,  38.20587931]) # good 

intersections.head()

# from common.county_geometry import convert_points

# grid_to_LL = intersections.KY_grid_XY.apply(convert_points.point_to_ll)
# LL_to_grid = intersections.GEOMETRY.apply(convert_points.point_to_grid)

,FST_ROADNAME,SEC_ROADNAME,SIFCODE1,SIFCODE2,FST_SIFID,SEC_SIFID,GEOMETRY
INTID,,,,,,,
5710837346,REHL RD,W REHL CT,5464,7662,4976,6856,"[-85.51044384084946, 38.20588660809318]"
10005800273,REHL RD,TUCKER STATION RD,5464,6551,4976,5908,"[-85.52816882852979, 38.20037561255241]"
14300767569,REHL RD,TUCKER STATION RD,5464,6551,4976,5908,"[-85.52841872335158, 38.200360349057064]"
18011691414,I 64 EAST,I 265 RAMP,3194,9996,3076,8763,"[-85.50495414554669, 38.22260344055154]"
23945910678,I 265 NORTH,I 265 RAMP,9349,9996,8197,8763,"[-85.50554642815675, 38.222127288727606]"

In [5]:
# bring in centerlines -> DataFrame centerlines
centerlines_path = "./data/cleaner/centerlines_clean.json"

def read_in_centerlines(path_to_data):
    df = pd.read_json(path_to_data, orient='records', lines=True)
    return df.set_index("OBJECTID")

centerline_data = read_in_centerlines(centerlines_path)
#centerlines.head()

# fix geometry column

def get_geo_ends(df):
    ends = df.GEOMETRY.transform({"GEOLOW":itemgetter(0), 'GEOHI':itemgetter(-1)})
    df['GEO_start'] = ends.GEOLOW.apply(np.array)
    df['GEO_end'] = ends.GEOHI.apply(np.array) 
    return df

centerlines = get_geo_ends(centerline_data)

# set aside full geo for now:
centerline_GEOMETRY = centerlines.GEOMETRY
centerlines = centerlines.drop(["GEOMETRY"], axis=1)

display(centerline_GEOMETRY.head())
centerlines.head()

OBJECTID
1    [[-85.6809503218278, 38.158867088749105], [-85...
2    [[-85.80120122370631, 38.23056379303306], [-85...
3    [[-85.80501498815028, 38.228933021550915], [-8...
4    [[-85.68020545343364, 38.24806713661984], [-85...
5    [[-85.74203979766622, 38.211814770925905], [-8...
Name: GEOMETRY, dtype: object

,ROADNAME,SIFID,SIFCODE,low_cross_ROADNAME,SIFIDLOW,LOCROSSSIF,hi_cross_ROADNAME,SIFIDHI,HICROSSSIF,CORE_CLASS,GEO_start,GEO_end
OBJECTID,,,,,,,,,,,,
1,SERENITY CT,8665,9887,DELLAFAY DR,1550,1557,DEAD END,8594,9811,LOCAL,"[-85.6809503218278, 38.158867088749105]","[-85.68123463490603, 38.158180484404916]"
2,S 28TH ST,5926,6570,W HILL ST,2854,2934,W GAULBERT AVE,2470,2499,LOCAL,"[-85.80120122370631, 38.23056379303306]","[-85.8013692697861, 38.22934335950893]"
3,BEECH ST,473,0458,WILSON AVE,6487,7212,DR WILLIAM G WEATHERS DR,10596,D596,LOCAL,"[-85.80501498815028, 38.228933021550915]","[-85.80483162492965, 38.22753788732054]"
4,GARDEN DR,2442,2470,RAINBOW DR,13394,5391,POPPY WAY,4702,5128,PRIMARY COLLECTOR,"[-85.68020545343364, 38.24806713661984]","[-85.67986300781635, 38.24760815991686]"
5,PARKWAY DR,4573,4974,MOUNT CLAIRE AVE,4162,4476,DEAD END,8594,9811,LOCAL,"[-85.74203979766622, 38.211814770925905]","[-85.74164752771065, 38.21196859682181]"

In [6]:
# remove interstates from centerlines ?\
# - and other roads like ramps?
exclusions = ('EXPRESSWAY', 'INTERSTATE RAMP')
centerlines = centerlines[~centerlines.CORE_CLASS.isin(exclusions)]

# remove these from intersections as well? 

centerlines.head()

,ROADNAME,SIFID,SIFCODE,low_cross_ROADNAME,SIFIDLOW,LOCROSSSIF,hi_cross_ROADNAME,SIFIDHI,HICROSSSIF,CORE_CLASS,GEO_start,GEO_end
OBJECTID,,,,,,,,,,,,
1,SERENITY CT,8665,9887,DELLAFAY DR,1550,1557,DEAD END,8594,9811,LOCAL,"[-85.6809503218278, 38.158867088749105]","[-85.68123463490603, 38.158180484404916]"
2,S 28TH ST,5926,6570,W HILL ST,2854,2934,W GAULBERT AVE,2470,2499,LOCAL,"[-85.80120122370631, 38.23056379303306]","[-85.8013692697861, 38.22934335950893]"
3,BEECH ST,473,0458,WILSON AVE,6487,7212,DR WILLIAM G WEATHERS DR,10596,D596,LOCAL,"[-85.80501498815028, 38.228933021550915]","[-85.80483162492965, 38.22753788732054]"
4,GARDEN DR,2442,2470,RAINBOW DR,13394,5391,POPPY WAY,4702,5128,PRIMARY COLLECTOR,"[-85.68020545343364, 38.24806713661984]","[-85.67986300781635, 38.24760815991686]"
5,PARKWAY DR,4573,4974,MOUNT CLAIRE AVE,4162,4476,DEAD END,8594,9811,LOCAL,"[-85.74203979766622, 38.211814770925905]","[-85.74164752771065, 38.21196859682181]"

\# Old code to match centerlines and intersections by SIFID pairs

```py
def build_2(intersection_sifid_index, centerline_sifid_index, 
                      intersection_dict, centerline_dict) -> None:
    # build intersection sifid pair / centerline sifid pair index
    matchset = index_by_SIFID_pairs(intersection_sifid_index, centerline_sifid_index)

    for _, intersection_ids, centerline_ids in matchset.itertuples():
        for int_id in intersection_ids:
            # gather centerline ids into appropriate dictionaries, indexed by intersection ids
            for cl_id in centerline_ids:
                intersection_dict[(int_id, cl_id)] = True
                centerline_dict[(int_id, cl_id)] = True
```

This code was an improved version of this:

```py
def build_match_dicts(intersection_sifid_index, centerline_sifid_index, 
                      intersection_dict, centerline_dict) -> None:
    # build intersection sifid pair / centerline sifid pair index
    matchset = index_by_SIFID_pairs(intersection_sifid_index, centerline_sifid_index)

    for _, intersection_ids, centerline_ids in matchset.itertuples():
        for int_id in intersection_ids:
            # gather centerline ids into appropriate dictionaries, indexed by intersection ids
            intersection_dict[int_id].update(centerline_ids)
            centerline_dict[int_id].update(centerline_ids)
```

Both required error-prone finagling of data objects like this:

```py
# create dictionaries to store future series info
intersections_FST_match = defaultdict(set)
intersections_SEC_match = defaultdict(set)
centerlines_LOW_match = defaultdict(set)
centerlines_HI_match = defaultdict(set)

intm1 = dict()#pd.Series(name='FST_match')
intm2 = dict()#pd.Series(name='SEC_match')
clLOWm = dict()#pd.Series(name='SIFIDLOW_match')
clHIm = dict()#pd.Series(name='SIFIDHI_match')

build_2(intersections_by_FST_SEC, centerlines_by_SIFID_SIFIDLOW, intm1, clLOWm)
build_2(intersections_by_FST_SEC, centerlines_by_SIFID_SIFIDHI, intm1, clHIm)
build_2(intersections_by_SEC_FST, centerlines_by_SIFID_SIFIDLOW, intm2, clLOWm)
build_2(intersections_by_SEC_FST, centerlines_by_SIFID_SIFIDHI, intm2, clHIm)
# build step takes 30s! # not anymore very fast now for some reaason.
```


```python
# Create indexes, sort information into the appropriate dictionaries.
build_match_dicts(intersections_by_FST_SEC, centerlines_by_SIFID_SIFIDLOW, intersections_FST_match, centerlines_LOW_match)
    # Where intersections[FST_SIFID] == centerlines[SIFID] & intersections[SEC_SIFID] == centerlines[SIFIDLOW]
    # Map intersection ids to the centerline ids. Next, do the same for all the other combinations of columns:
build_match_dicts(intersections_by_FST_SEC, centerlines_by_SIFID_SIFIDHI, intersections_FST_match, centerlines_HI_match)
build_match_dicts(intersections_by_SEC_FST, centerlines_by_SIFID_SIFIDLOW, intersections_SEC_match, centerlines_LOW_match)
build_match_dicts(intersections_by_SEC_FST, centerlines_by_SIFID_SIFIDHI, intersections_SEC_match, centerlines_HI_match)

# Convert the dictionaries to Series.
intersections_FST_match = pd.Series(intersections_FST_match, name='FST_match')
intersections_SEC_match = pd.Series(intersections_SEC_match, name='SEC_match')
centerlines_LOW_match = pd.Series(centerlines_LOW_match, name='SIFIDLOW_match')
centerlines_HI_match = pd.Series(centerlines_HI_match, name='SIFIDHI_match')

# Create dataframe by concatenating Series. Intersection id's are the index. 
matchdf = pd.concat((intersections_FST_match, intersections_SEC_match, centerlines_LOW_match, centerlines_HI_match), axis=1)
matchdf.info()
```

```py
intm1 = pd.Series(intm1, name='FST_match', dtype='boolean')
intm2 = pd.Series(intm2, name='SEC_match', dtype='boolean')
clLOWm = pd.Series(clHIm, name='SIFIDLOW_match', dtype='boolean')
clHIm = pd.Series(clLOWm, name='SIFIDHI_match', dtype='boolean')

newmatch = pd.concat((intm1, intm2, clLOWm, clHIm), axis=1)
newmatch[newmatch.SIFIDHI_match & newmatch.SIFIDLOW_match]
```

In [8]:
# get groups
def get_groups(df, by) -> dict:
    return pd.Series(df.groupby(by=by).groups)

centerlines_by_SIFID_SIFIDLOW = get_groups(centerlines, ['SIFID', 'SIFIDLOW'])
centerlines_by_SIFID_SIFIDHI = get_groups(centerlines, ['SIFID', 'SIFIDHI'])

#
#any(centerlines_by_SIFID_SIFIDLOW.apply(len)>1) # True
#any(centerlines_by_SIFID_SIFIDHI.apply(len)>1) # True
#centerlines_by_SIFID_SIFIDHI

intersections_by_FST_SEC = get_groups(intersections, ['FST_SIFID', 'SEC_SIFID'])
# If the index of one of the centerline groups matches an index in this group, that means
#
#   (centerline == centerlines.loc[centerline index])
#   intersection[FST_SIFID] == centerline[SIFID]
#                   and
#   intersections[SEC_SIFID] == either centerline[SIFIDLOW] or centerline[SIFIDHI]
# depending on which set of centerline groups, which we built above, that we are using. 

# The names FST_SIFID / SEC_SIFID -> First / Second intersection SIFID are convention and
# the order is arbitrary. Reversing the order of the index allows us to match SEC_SIFID efficiently.
intersections_by_SEC_FST = get_groups(intersections, ['SEC_SIFID', 'FST_SIFID'])
# If the index of one of the centerline groups is an index in this group, that means
#
#   intersection[SEC_SIFID] == centerline[SIFID]
#                   and
#   intersections[FST_SIFID] == either centerline[SIFIDLOW] or centerline[SIFIDHI]

#
#any(intersections_by_FST_SEC.apply(len) > 1) # True
#any(intersections_by_SEC_FST.apply(len) > 1) # True


def index_by_SIFID_pairs(intersection_sifid_pairs, centerline_sifid_pairs) -> pd.DataFrame:
    return pd.concat((intersection_sifid_pairs, centerline_sifid_pairs), axis=1,
                    # map intersection ids to centerline ids where their sifid pair indexes match
                    # matches are collections of intersection ids/indexes and centerline ids/indexes
                        ).dropna(how='any')
                    # if either collection of ids is empty (or both), there is no match.

In [9]:
mapping = defaultdict(int)

fst_mask = 0b0001
sec_mask = 0b0010
low_mask = 0b0100
hi_mask = 0b1000

for imask, I in ((fst_mask, intersections_by_FST_SEC), (sec_mask, intersections_by_SEC_FST)):
    for cmask, C in ((low_mask, centerlines_by_SIFID_SIFIDLOW), (hi_mask, centerlines_by_SIFID_SIFIDHI)):
        matchset = index_by_SIFID_pairs(I, C)
        set_cols = imask + cmask
        for (s1, s2), intersection_ids, centerline_ids in matchset.itertuples():
            for intersection_id in intersection_ids:
                for cl_id in centerline_ids:
                    mapping[(intersection_id, cl_id)] |= set_cols

mdf = matchdfnumeric = pd.Series(mapping)

matchdfnumeric.index.set_names(('int_id', 'cl_id'), inplace=True)
matchdfnumeric.apply("0b {:04b}".format)

int_id           cl_id
589991067518338  10250     0b 0101
                 28655     0b 0101
590506463593858  10250     0b 0101
                 28655     0b 0101
409323268213029  26919     0b 0101
                            ...
847134907955010  174788    0b 1010
847207302035270  175429    0b 1010
847212217628486  175434    0b 1010
847246577432390  175435    0b 1010
847250872399689  175437    0b 1010
Length: 64111, dtype: object

In [10]:
# intersections
iw = matchdfnumeric.sort_index().index.to_frame()
iw

intersection_geos = intersections['GEOMETRY']

int_points = iw.int_id.apply(lambda int_id:intersection_geos.loc[int_id])

# centerlines
cl_GEO_start = centerlines.GEO_start
cl_GEO_end = centerlines.GEO_end

cl_start_points = iw.cl_id.apply(lambda cl_id:cl_GEO_start.loc[cl_id])
cl_end_points = iw.cl_id.apply(lambda cl_id:cl_GEO_end.loc[cl_id])

In [11]:
angle_int_to_end = cl_end_points.combine(int_points, central_angle).sort_index()
angle_int_to_start = cl_start_points.combine(int_points, central_angle).sort_index()

In [12]:
diffs = angle_int_to_start - angle_int_to_end

start_is_close = diffs <= 0
start_is_far = end_is_close = diffs > 0
end_is_far = diffs < 0

def encode(diff):
    if diff < 0: # start angle is smaller
        return 'start' 
    elif diff > 0: # start angle is larger 
        return 'end' 
    elif diff == 0:
        return 'both'
    else:
        return pd.NA 

GEO_map = matchdfnumeric.transform({"int_match": lambda x:x & 0b0011,
                               "hi_match": lambda x:bool(x & 0b1000),
                               "low_match": lambda x:bool(x & 0b0100)})

GEO_map['intersection_point'] = int_points

GEO_map['GEO_match_code'] = diffs.apply(encode)

In [13]:


GEO_map['GEO_close'] = pd.concat((
    cl_start_points[start_is_close],
    cl_end_points[end_is_close]))

GEO_map['GEO_far'] = pd.concat((
    cl_start_points[start_is_far],
    cl_end_points[end_is_far]))

GEO_map['close_angle'] = pd.concat((
    angle_int_to_start[start_is_close],
    angle_int_to_end[end_is_close]))

GEO_map['far_angle'] = pd.concat((
    angle_int_to_start[start_is_far],
    angle_int_to_end[end_is_far]))

GEO_map = GEO_map.sort_index()
GEO_map

                         int_match  hi_match  low_match  \
int_id           cl_id
5710837346       20353           1     False       True
                 20860           2     False       True
                 52803           1      True      False
10005800273      7109            1      True       True
                 9233            1     False       True
...                            ...       ...        ...
2698443752596326 32774           1     False       True
                 105004          1     False       True
2698447711168309 4069            1     False       True
                 8304            2     False       True
                 30017           1      True      False

                                              intersection_point  \
int_id           cl_id
5710837346       20353   [-85.51044384084946, 38.20588660809318]
                 20860   [-85.51044384084946, 38.20588660809318]
                 52803   [-85.51044384084946, 38.20588660809318]
10005800273      7109    [-85.52816882852979, 38.20037561255241]
                 9233    [-85.52816882852979, 38.20037561255241]
...                                                          ...
2698443752596326 32774   [-85.52706694300736, 38.22235647012922]
                 105004  [-85.52706694300736, 38.22235647012922]
2698447711168309 4069    [-85.68299954058695, 38.13164510965587]
                 8304    [-85.68299954058695, 38.13164510965587]
                 30017   [-85.68299954058695, 38.13164510965587]

                        GEO_match_code  \
int_id           cl_id
5710837346       20353           start
                 20860           start
                 52803             end
10005800273      7109              end
                 9233            start
...                                ...
2698443752596326 32774           start
                 105004          start
2698447711168309 4069            start
                 8304            start
                 30017             end

                                                       GEO_close  \
int_id           cl_id
5710837346       20353   [-85.51044384084946, 38.20588660809318]
                 20860   [-85.51044384084946, 38.20588660809318]
                 52803   [-85.51044384084946, 38.20588660809318]
10005800273      7109    [-85.52816882852979, 38.20037561255241]
                 9233    [-85.52816882852979, 38.20037561255241]
...                                                          ...
2698443752596326 32774     [-85.5284541859341, 38.2171605272513]
                 105004  [-85.52706694300736, 38.22235647012922]
2698447711168309 4069    [-85.68299954058695, 38.13164510965587]
                 8304    [-85.68299954058695, 38.13164510965587]
                 30017   [-85.68299954058695, 38.13164510965587]

                                                          GEO_far  \
int_id           cl_id
5710837346       20353   [-85.50187141303726, 38.206105324500015]
                 20860    [-85.50782952965943, 38.20500236063127]
                 52803    [-85.51425148406123, 38.20488285764657]
10005800273      7109    [-85.52841872335158, 38.200360349057064]
                 9233     [-85.52154597701633, 38.20245302533696]
...                                                           ...
2698443752596326 32774    [-85.53108855038136, 38.21655402891962]
                 105004   [-85.52577512279841, 38.21982202058226]
2698447711168309 4069     [-85.68203371076034, 38.12989574098884]
                 8304      [-85.6821648141634, 38.13195098098284]
                 30017    [-85.68417066088023, 38.13377420926451]

                         close_angle  far_angle
int_id           cl_id
5710837346       20353      0.000000   0.000118
                 20860      0.000000   0.000039
                 52803      0.000000   0.000055
10005800273      7109       0.000000   0.000003
                 9233       0.000000   0.000098
...                              ...        ...
2698443752596326 32774      0.000093   0.000115
                 105004     0.000000   0.000048
2698447711168309 4069       0.000000   0.000033
                 8304       0.000000   0.000013
                 30017      0.000000   0.000040

[64111 rows x 9 columns]

In [14]:
direct_matches = dm = GEO_map[GEO_map.close_angle == 0]
direct_matches

                         int_match  hi_match  low_match  \
int_id           cl_id
5710837346       20353           1     False       True
                 20860           2     False       True
                 52803           1      True      False
10005800273      7109            1      True       True
                 9233            1     False       True
...                            ...       ...        ...
2698443752596326 8539            1      True      False
                 105004          1     False       True
2698447711168309 4069            1     False       True
                 8304            2     False       True
                 30017           1      True      False

                                              intersection_point  \
int_id           cl_id
5710837346       20353   [-85.51044384084946, 38.20588660809318]
                 20860   [-85.51044384084946, 38.20588660809318]
                 52803   [-85.51044384084946, 38.20588660809318]
10005800273      7109    [-85.52816882852979, 38.20037561255241]
                 9233    [-85.52816882852979, 38.20037561255241]
...                                                          ...
2698443752596326 8539    [-85.52706694300736, 38.22235647012922]
                 105004  [-85.52706694300736, 38.22235647012922]
2698447711168309 4069    [-85.68299954058695, 38.13164510965587]
                 8304    [-85.68299954058695, 38.13164510965587]
                 30017   [-85.68299954058695, 38.13164510965587]

                        GEO_match_code  \
int_id           cl_id
5710837346       20353           start
                 20860           start
                 52803             end
10005800273      7109              end
                 9233            start
...                                ...
2698443752596326 8539              end
                 105004          start
2698447711168309 4069            start
                 8304            start
                 30017             end

                                                       GEO_close  \
int_id           cl_id
5710837346       20353   [-85.51044384084946, 38.20588660809318]
                 20860   [-85.51044384084946, 38.20588660809318]
                 52803   [-85.51044384084946, 38.20588660809318]
10005800273      7109    [-85.52816882852979, 38.20037561255241]
                 9233    [-85.52816882852979, 38.20037561255241]
...                                                          ...
2698443752596326 8539    [-85.52706694300736, 38.22235647012922]
                 105004  [-85.52706694300736, 38.22235647012922]
2698447711168309 4069    [-85.68299954058695, 38.13164510965587]
                 8304    [-85.68299954058695, 38.13164510965587]
                 30017   [-85.68299954058695, 38.13164510965587]

                                                          GEO_far  \
int_id           cl_id
5710837346       20353   [-85.50187141303726, 38.206105324500015]
                 20860    [-85.50782952965943, 38.20500236063127]
                 52803    [-85.51425148406123, 38.20488285764657]
10005800273      7109    [-85.52841872335158, 38.200360349057064]
                 9233     [-85.52154597701633, 38.20245302533696]
...                                                           ...
2698443752596326 8539      [-85.52800654883289, 38.2245264344245]
                 105004   [-85.52577512279841, 38.21982202058226]
2698447711168309 4069     [-85.68203371076034, 38.12989574098884]
                 8304      [-85.6821648141634, 38.13195098098284]
                 30017    [-85.68417066088023, 38.13377420926451]

                         close_angle  far_angle
int_id           cl_id
5710837346       20353           0.0   0.000118
                 20860           0.0   0.000039
                 52803           0.0   0.000055
10005800273      7109            0.0   0.000003
                 9233            0.0   0.000098
...                              ...        ...
2698443752596326 8539            0.0   0.000040
                 105004          0.0   0.000048
2698447711168309 4069            0.0   0.000033
                 8304            0.0   0.000013
                 30017           0.0   0.000040

[58707 rows x 9 columns]

In [18]:

int_FST_cl_match = defaultdict(list)
int_SEC_cl_match = defaultdict(list)

cl_low_int_match = defaultdict(list)
cl_hi_int_match = defaultdict(list)

cl_start_int_match = defaultdict(list)
cl_end_int_match = defaultdict(list)

hi_xor_low = dm[dm.hi_match ^ dm.low_match]
both = dm[dm.hi_match & dm.low_match]
#dm[~dm.hi_match & ~dm.low_match] # None

#both[both.GEO_match_code == 'both']

In [279]:
# HERE

def order(sifid1, sifid2):
    if sifid1 > sifid2:
        return (sifid2, sifid1)
    else:
        return (sifid1, sifid2)

int_SIFID_order = intersections.FST_SIFID.combine(intersections.SEC_SIFID, order)
intersections_by_SIFID_order = pd.Series(intersections.groupby(int_SIFID_order).groups)

cl_SIFID_LOW_order = centerlines.SIFID.combine(centerlines.SIFIDLOW, order)
centerlines_by_SIFID_LOW_order = pd.Series(centerlines.groupby(cl_SIFID_LOW_order).groups)

cl_SIFID_HI_order = centerlines.SIFID.combine(centerlines.SIFIDHI, order)
centerlines_by_SIFID_HI_order = pd.Series(centerlines.groupby(cl_SIFID_HI_order).groups)


#cl_SIFID_LOW_order.combine(centerlines_by_SIFID_LOW_order, lambda x,y:(x,y))
centerlines_by_SIFID_order = centerlines_by_SIFID_LOW_order.combine(centerlines_by_SIFID_HI_order,
                           lambda x, y:x.union(y),
                           fill_value = pd.Index(()))

In [330]:
ic_map = pd.concat((
intersections_by_SIFID_order,
centerlines_by_SIFID_order), axis=1,
keys=['intersection_ids', 'centerline_ids'])

ic_map = ic_map.dropna() # ignore mismatches for now

int_cl_SIFID_map = defaultdict(set)

def map_int_to_cl(row):
    int_ids = row.intersection_ids
    cl_ids = row.centerline_ids
    for int_id in int_ids:
        int_cl_SIFID_map[int_id].update(cl_ids)

ic_map.apply(map_int_to_cl, axis=1)
int_cl_SIFID_map = pd.Series(int_cl_SIFID_map).sort_index()
int_cl_SIFID_map

5710837346                      {20353, 52803, 20860}
10005800273         {13504, 7109, 84838, 31468, 9233}
14300767569         {13504, 7109, 84838, 31468, 9233}
79566575913                     {26604, 90022, 23911}
83861558290                             {26604, 4511}
                                  ...
2698419891660598                {19602, 12019, 19268}
2698428751996728                  {26925, 6101, 1638}
2698437341931319                 {5496, 19602, 26925}
2698443752596326    {8034, 32774, 6763, 105004, 8539}
2698447711168309                  {8304, 30017, 4069}
Length: 19738, dtype: object

In [336]:
cl_gg_start = centerlines.groupby(centerlines.GEO_start.apply(tuple)).groups 
# annoying converting between types
cl_gg_end = centerlines.groupby(centerlines.GEO_end.apply(tuple)).groups

empty = set()

def match_cl_point(point, which=None):
    this = which.get(point, None)
    if this is None:
        return empty
    else:
        return this
        
int_GEO = intersections.GEOMETRY.apply(tuple)
start_match = int_GEO.apply(match_cl_point, which=cl_gg_start)
end_match = int_GEO.apply(match_cl_point, which=cl_gg_end)

In [353]:

gsm = int_cl_SIFID_map.combine(start_match, lambda x, y:x.intersection(y), fill_value=set())
#start_match
c = 0
for row in gsm.items():
    int_id, cl_ids = row
    os = start_match.loc[int_id]
    if len(cl_ids) != len(os):
        c += 1
        print(int_id, cl_ids, os)

c

87315224873 set() Index([90020], dtype='int64', name='OBJECTID')
1404457620489 set() Index([8261, 25468], dtype='int64', name='OBJECTID')
1602451677192 {30306} Index([3131, 9407, 30306], dtype='int64', name='OBJECTID')
1602451685766 {9407} Index([3131, 9407, 30306], dtype='int64', name='OBJECTID')
1602560213382 {3131} Index([3131, 9407, 30306], dtype='int64', name='OBJECTID')
2410644330103 set() Index([8189, 31364], dtype='int64', name='OBJECTID')
2410644334353 {31364} Index([8189, 31364], dtype='int64', name='OBJECTID')
2410927318801 {8189} Index([8189, 31364], dtype='int64', name='OBJECTID')
2418358114624 {50572, 18519} Index([10901, 18519, 50572], dtype='int64', name='OBJECTID')
2418358146905 set() Index([10901, 18519, 50572], dtype='int64', name='OBJECTID')
2419564009305 {10901, 18519} Index([10901, 18519, 50572], dtype='int64', name='OBJECTID')
2488403256657 {3457} Index([3457, 6763, 42246], dtype='int64', name='OBJECTID')
2762860829078 {497} Index([497, 160071], dtype='int64', name='OBJECTID')
2762860847764 {160071} Index([497, 160071], dtype='int64', name='OBJECTID')
2764240773780 set() Index([497, 160071], dtype='int64', name='OBJECTID')
3401617397254 {140221} Index([32586, 140221], dtype='int64', name='OBJECTID')
3401617398080 set() Index([32586, 140221], dtype='int64', name='OBJECTID')
3403057355072 {32586} Index([32586, 140221], dtype='int64', name='OBJECTID')
3450356131601 set() Index([39, 270, 4342], dtype='int64', name='OBJECTID')
3450356143113 {270} Index([39, 270, 4342], dtype='int64', name='OBJECTID')
3450587943945 {4342, 39} Index([39, 270, 4342], dtype='int64', name='OBJECTID')
3678222513712 set() Index([3914], dtype='int64', name='OBJECTID')
3678222579248 set() Index([3914], dtype='int64', name='OBJECTID')
4501699744073 set() Index([9878, 31266], dtype='int64', name='OBJECTID')
4504637002069 set() Index([9878, 31266], dtype='int64', name='OBJECTID')
4907160147827 set() Index([165187], dtype='int64', name='OBJECTID')
4907393587587 set() Index([165187], dtype='int64', name='OBJECTID')
5035199076739 set() Index([3934, 24955, 72053], dtype='int64', name='OBJECTID')
5035199076740 {3934} Index([3934, 24955, 72053], dtype='int64', name='OBJECTID')
5036277209476 {24955, 72053} Index([3934, 24955, 72053], dtype='int64', name='OBJECTID')
5568500827928 {24922} Index([19373, 24922], dtype='int64', name='OBJECTID')
5568500827929 {19373} Index([19373, 24922], dtype='int64', name='OBJECTID')
5568544147225 set() Index([19373, 24922], dtype='int64', name='OBJECTID')
6002491773523 set() Index([11605, 26387], dtype='int64', name='OBJECTID')
6002491773555 {26387} Index([11605, 26387], dtype='int64', name='OBJECTID')
6003598021235 {11605} Index([11605, 26387], dtype='int64', name='OBJECTID')
6013361533776 {29637} Index([9023, 29637, 90033], dtype='int64', name='OBJECTID')
6013361543488 set() Index([9023, 29637, 90033], dtype='int64', name='OBJECTID')
6013815118144 {90033, 9023} Index([9023, 29637, 90033], dtype='int64', name='OBJECTID')
6121948738066 set() Index([21983, 28460], dtype='int64', name='OBJECTID')
6129347289236 set() Index([26352, 28561], dtype='int64', name='OBJECTID')
6615209449777 {1541} Index([1541, 1567], dtype='int64', name='OBJECTID')
7095824117768 set() Index([6526, 29712], dtype='int64', name='OBJECTID')
7095824118356 set() Index([6526, 29712], dtype='int64', name='OBJECTID')
7109094830676 {25860} Index([25860, 28462], dtype='int64', name='OBJECTID')
7170214228564 set() Index([18914], dtype='int64', name='OBJECTID')
7173024346708 set() Index([4083, 19187], dtype='int64', name='OBJECTID')
8127274979427 {31512} Index([18901, 31512], dtype='int64', name='OBJECTID')
8127274981782 {18901} Index([18901, 31512], dtype='int64', name='OBJECTID')
8128500570518 set() Index([18901, 31512], dtype='int64', name='OBJECTID')
8286489306920 {13817, 1126} Index([394, 1126, 13817], dtype='int64', name='OBJECTID')
9008562403383 {27041} Index([25331, 27041], dtype='int64', name='OBJECTID')
9008562403392 set() Index([25331, 27041], dtype='int64', name='OBJECTID')
9008563320896 {25331} Index([25331, 27041], dtype='int64', name='OBJECTID')
9153436222055 {98601} Index([25075, 98601], dtype='int64', name='OBJECTID')
9155143480144 {25075} Index([25075, 98601], dtype='int64', name='OBJECTID')
9968892977417 {18050} Index([1843, 18050, 27114], dtype='int64', name='OBJECTID')
9968892983047 {1843} Index([1843, 18050, 27114], dtype='int64', name='OBJECTID')
9969173346055 {27114} Index([1843, 18050, 27114], dtype='int64', name='OBJECTID')
10059736634417 {32002} Index([26341, 32002], dtype='int64', name='OBJECTID')
10059736641842 {26341} Index([26341, 32002], dtype='int64', name='OBJECTID')
10060225933618 set() Index([26341, 32002], dtype='int64', name='OBJECTID')
10063982118982 set() Index([1881, 58564], dtype='int64', name='OBJECTID')
10064320950578 set() Index([1881, 58564], dtype='int64', name='OBJECTID')
10329724122933 {16712} Index([16712, 32306], dtype='int64', name='OBJECTID')
10329724122934 {32306} Index([16712, 32306], dtype='int64', name='OBJECTID')
10331396339510 set() Index([16712, 32306], dtype='int64', name='OBJECTID')
17871664670519 set() Index([7211, 30752], dtype='int64', name='OBJECTID')
17873090602808 set() Index([7211, 30752], dtype='int64', name='OBJECTID')
18709013071893 {118136} Index([118135, 118136, 118137], dtype='int64', name='OBJECTID')
18709013108551 {118137} Index([118135, 118136, 118137], dtype='int64', name='OBJECTID')
18709013174087 {118135} Index([118135, 118136, 118137], dtype='int64', name='OBJECTID')
18760552670357 set() Index([33174], dtype='int64', name='OBJECTID')
18760991171733 set() Index([33174], dtype='int64', name='OBJECTID')
20028929898032 {10834, 21374} Index([10834, 19663, 21374], dtype='int64', name='OBJECTID')
20028929906985 set() Index([10834, 19663, 21374], dtype='int64', name='OBJECTID')
20029415397673 {19663} Index([10834, 19663, 21374], dtype='int64', name='OBJECTID')
20094426666597 {21878} Index([21878, 28586], dtype='int64', name='OBJECTID')
20094426666627 {28586} Index([21878, 28586], dtype='int64', name='OBJECTID')
20095454008963 set() Index([21878, 28586], dtype='int64', name='OBJECTID')
20160850481987 {31991} Index([10366, 31991], dtype='int64', name='OBJECTID')
20164120926585 set() Index([10366, 31991], dtype='int64', name='OBJECTID')
20354442041749 set() Index([18717, 27843], dtype='int64', name='OBJECTID')
20355520698773 set() Index([18717, 27843], dtype='int64', name='OBJECTID')
20998922717251 {11060} Index([11060, 12382], dtype='int64', name='OBJECTID')
20998922753121 {12382} Index([11060, 12382], dtype='int64', name='OBJECTID')
20999307514977 set() Index([11060, 12382], dtype='int64', name='OBJECTID')
21238680802423 set() Index([26860], dtype='int64', name='OBJECTID')
21240030386548 set() Index([26860], dtype='int64', name='OBJECTID')
21252169568306 set() Index([4364, 31217], dtype='int64', name='OBJECTID')
21253227450418 set() Index([4364, 31217], dtype='int64', name='OBJECTID')
21377670541376 set() Index([29458], dtype='int64', name='OBJECTID')
22235165530518 {16456} Index([16456, 23369], dtype='int64', name='OBJECTID')
22235165549570 {23369} Index([16456, 23369], dtype='int64', name='OBJECTID')
22237622494210 set() Index([16456, 23369], dtype='int64', name='OBJECTID')
22348649821732 {14634} Index([14634, 15335, 40963], dtype='int64', name='OBJECTID')
22364315350564 {7590, 96687} Index([7590, 21199, 96687], dtype='int64', name='OBJECTID')
22367990585618 set() Index([7590, 21199, 96687], dtype='int64', name='OBJECTID')
22367990609444 {21199} Index([7590, 21199, 96687], dtype='int64', name='OBJECTID')
22406851930519 set() Index([28154], dtype='int64', name='OBJECTID')
22407542162288 set() Index([28154], dtype='int64', name='OBJECTID')
22626726609456 {25609} Index([25609, 40650], dtype='int64', name='OBJECTID')
23237526386496 set() Index([16539, 29612], dtype='int64', name='OBJECTID')
23237773326144 set() Index([16539, 29612], dtype='int64', name='OBJECTID')
23472053166982 set() Index([17937, 31810], dtype='int64', name='OBJECTID')
23472592278088 set() Index([17937, 31810], dtype='int64', name='OBJECTID')
24417027695687 set() Index([1048, 19728, 26931], dtype='int64', name='OBJECTID')
24417027719778 {1048, 19728} Index([1048, 19728, 26931], dtype='int64', name='OBJECTID')
24417497743970 {26931} Index([1048, 19728, 26931], dtype='int64', name='OBJECTID')
24807841411428 set() Index([8930, 24766], dtype='int64', name='OBJECTID')
24807841413216 {24766} Index([8930, 24766], dtype='int64', name='OBJECTID')
24808559753312 {8930} Index([8930, 24766], dtype='int64', name='OBJECTID')
25324054138999 set() Index([9712], dtype='int64', name='OBJECTID')
25324477190472 set() Index([9712], dtype='int64', name='OBJECTID')
25452286988562 {19929} Index([4697, 19929], dtype='int64', name='OBJECTID')
25452286992448 {4697} Index([4697, 19929], dtype='int64', name='OBJECTID')
25453336354880 set() Index([4697, 19929], dtype='int64', name='OBJECTID')
25641112249688 {32965} Index([13525, 32965], dtype='int64', name='OBJECTID')
25641112262935 {13525} Index([13525, 32965], dtype='int64', name='OBJECTID')
25641581304087 set() Index([13525, 32965], dtype='int64', name='OBJECTID')
25775528371847 set() Index([11881], dtype='int64', name='OBJECTID')
25775528372064 set() Index([11881], dtype='int64', name='OBJECTID')
25782846170470 {5381} Index([5381, 7210, 20825], dtype='int64', name='OBJECTID')
25782846175320 {7210} Index([5381, 7210, 20825], dtype='int64', name='OBJECTID')
25783316133976 {20825} Index([5381, 7210, 20825], dtype='int64', name='OBJECTID')
25792224442466 {11347} Index([7282, 11347, 13986], dtype='int64', name='OBJECTID')
25792224457288 {13986, 7282} Index([7282, 11347, 13986], dtype='int64', name='OBJECTID')
25792224588360 set() Index([7282, 11347, 13986], dtype='int64', name='OBJECTID')
25868690085238 set() Index([18865], dtype='int64', name='OBJECTID')
25868690085239 set() Index([18865], dtype='int64', name='OBJECTID')
26423313641733 set() Index([23285, 25345], dtype='int64', name='OBJECTID')
26423461234071 set() Index([23285, 25345], dtype='int64', name='OBJECTID')
26671866718465 {16767} Index([8720, 16767], dtype='int64', name='OBJECTID')
26671866722400 set() Index([8720, 16767], dtype='int64', name='OBJECTID')
26672434853984 {8720} Index([8720, 16767], dtype='int64', name='OBJECTID')
26873730175817 set() Index([1197], dtype='int64', name='OBJECTID')
26873933952646 set() Index([1197], dtype='int64', name='OBJECTID')
26891870640482 set() Index([1338], dtype='int64', name='OBJECTID')
26892238690658 set() Index([1338], dtype='int64', name='OBJECTID')
26943000961058 set() Index([4999, 20067], dtype='int64', name='OBJECTID')
26943942714164 set() Index([4999, 20067], dtype='int64', name='OBJECTID')
27513663807541 {160708} Index([160707, 160708], dtype='int64', name='OBJECTID')
27513663808309 set() Index([160707, 160708], dtype='int64', name='OBJECTID')
27515174609717 {160707} Index([160707, 160708], dtype='int64', name='OBJECTID')
27698264236308 set() Index([4288, 23619], dtype='int64', name='OBJECTID')
27699142025492 set() Index([4288, 23619], dtype='int64', name='OBJECTID')
27784572314432 set() Index([160712], dtype='int64', name='OBJECTID')
27784572319505 set() Index([160712], dtype='int64', name='OBJECTID')
27801646863990 {25060, 28228} Index([19626, 25060, 28228], dtype='int64', name='OBJECTID')
27801646886969 set() Index([19626, 25060, 28228], dtype='int64', name='OBJECTID')
27801700167737 {19626} Index([19626, 25060, 28228], dtype='int64', name='OBJECTID')
28059645257009 set() Index([19622, 23998], dtype='int64', name='OBJECTID')
28059645346901 set() Index([19622, 23998], dtype='int64', name='OBJECTID')
28132949196855 set() Index([2557, 11798], dtype='int64', name='OBJECTID')
28134186909752 set() Index([2557, 11798], dtype='int64', name='OBJECTID')
35566744003874 {164555} Index([17107, 164555], dtype='int64', name='OBJECTID')
35566744008321 {17107} Index([17107, 164555], dtype='int64', name='OBJECTID')
35568320935553 set() Index([17107, 164555], dtype='int64', name='OBJECTID')
35842043682889 set() Index([20021], dtype='int64', name='OBJECTID')
35842043687236 set() Index([20021], dtype='int64', name='OBJECTID')
37417874901059 {26818, 25597} Index([25597, 26818, 28072], dtype='int64', name='OBJECTID')
37417874903075 set() Index([25597, 26818, 28072], dtype='int64', name='OBJECTID')
37418967453731 {28072} Index([25597, 26818, 28072], dtype='int64', name='OBJECTID')
37474757038851 set() Index([843, 19762], dtype='int64', name='OBJECTID')
37475473085187 set() Index([843, 19762], dtype='int64', name='OBJECTID')
37483141423378 set() Index([22241], dtype='int64', name='OBJECTID')
37483380498706 set() Index([22241], dtype='int64', name='OBJECTID')
37598283388501 {28858} Index([12753, 28858], dtype='int64', name='OBJECTID')
37598283424613 set() Index([12753, 28858], dtype='int64', name='OBJECTID')
37599592178533 {12753} Index([12753, 28858], dtype='int64', name='OBJECTID')
37821488562277 set() Index([7963, 14799], dtype='int64', name='OBJECTID')
37821488656408 set() Index([7963, 14799], dtype='int64', name='OBJECTID')
38500090546002 set() Index([10117], dtype='int64', name='OBJECTID')
38501970184018 set() Index([10117], dtype='int64', name='OBJECTID')
38659430115382 set() Index([9988], dtype='int64', name='OBJECTID')
38660749027463 set() Index([9988], dtype='int64', name='OBJECTID')
38780623938614 set() Index([781, 1086], dtype='int64', name='OBJECTID')
38780941005106 set() Index([781, 1086], dtype='int64', name='OBJECTID')
39131536504723 set() Index([26212, 28170], dtype='int64', name='OBJECTID')
39131536505234 {26212} Index([26212, 28170], dtype='int64', name='OBJECTID')
39132379429266 {28170} Index([26212, 28170], dtype='int64', name='OBJECTID')
39583384498482 set() Index([30767, 32948], dtype='int64', name='OBJECTID')
39583845937458 {30767} Index([30767, 32948], dtype='int64', name='OBJECTID')
40024889727286 set() Index([8742, 31728], dtype='int64', name='OBJECTID')
40682203930709 set() Index([21460], dtype='int64', name='OBJECTID')
40682304594005 set() Index([21460], dtype='int64', name='OBJECTID')
40841437918512 {3011} Index([3011, 7541], dtype='int64', name='OBJECTID')
40841437922853 {7541} Index([3011, 7541], dtype='int64', name='OBJECTID')
40841736373797 set() Index([3011, 7541], dtype='int64', name='OBJECTID')
40845207479075 {14519} Index([14519, 29050, 29551], dtype='int64', name='OBJECTID')
40845207500375 {29050, 29551} Index([14519, 29050, 29551], dtype='int64', name='OBJECTID')
40845728511575 set() Index([14519, 29050, 29551], dtype='int64', name='OBJECTID')
40896763564049 set() Index([19510, 20058, 30203], dtype='int64', name='OBJECTID')
40896763564050 {30203, 19510} Index([19510, 20058, 30203], dtype='int64', name='OBJECTID')
40899095662610 {20058} Index([19510, 20058, 30203], dtype='int64', name='OBJECTID')
40901563078976 set() Index([21823], dtype='int64', name='OBJECTID')
40901563085321 set() Index([21823], dtype='int64', name='OBJECTID')
40961124476723 set() Index([917, 31935], dtype='int64', name='OBJECTID')
40961124499968 set() Index([917, 31935], dtype='int64', name='OBJECTID')
40970065814816 set() Index([1523, 4678, 28176], dtype='int64', name='OBJECTID')
40970065815652 {4678} Index([1523, 4678, 28176], dtype='int64', name='OBJECTID')
40970315901028 {28176, 1523} Index([1523, 4678, 28176], dtype='int64', name='OBJECTID')
41108608676249 set() Index([8732, 11510], dtype='int64', name='OBJECTID')
41108629385625 set() Index([8732, 11510], dtype='int64', name='OBJECTID')
41240281551479 {20347} Index([12609, 20347, 27221], dtype='int64', name='OBJECTID')
41240281569111 {27221} Index([12609, 20347, 27221], dtype='int64', name='OBJECTID')
41240585787223 {12609} Index([12609, 20347, 27221], dtype='int64', name='OBJECTID')
41301211295752 set() Index([3877, 8225, 16669], dtype='int64', name='OBJECTID')
41301211306304 {8225, 16669} Index([3877, 8225, 16669], dtype='int64', name='OBJECTID')
41301211371840 {3877} Index([3877, 8225, 16669], dtype='int64', name='OBJECTID')
41802941165908 set() Index([7958], dtype='int64', name='OBJECTID')
41804147814740 set() Index([7958], dtype='int64', name='OBJECTID')
41987605891427 set() Index([18601], dtype='int64', name='OBJECTID')
41989097687395 set() Index([18601], dtype='int64', name='OBJECTID')
41991970033717 {17372} Index([12537, 17372], dtype='int64', name='OBJECTID')
41991970068869 set() Index([12537, 17372], dtype='int64', name='OBJECTID')
41992167201157 {12537} Index([12537, 17372], dtype='int64', name='OBJECTID')
42224998500409 set() Index([6103, 20624, 31997], dtype='int64', name='OBJECTID')
42224998504768 {20624} Index([6103, 20624, 31997], dtype='int64', name='OBJECTID')
42225035204928 {31997, 6103} Index([6103, 20624, 31997], dtype='int64', name='OBJECTID')
42889817101904 {20507} Index([20507, 23719, 31117], dtype='int64', name='OBJECTID')
42889817120853 {31117, 23719} Index([20507, 23719, 31117], dtype='int64', name='OBJECTID')
42889917784149 set() Index([20507, 23719, 31117], dtype='int64', name='OBJECTID')
43185965961621 {14187} Index([14187, 21057, 83874], dtype='int64', name='OBJECTID')
43185965983031 set() Index([14187, 21057, 83874], dtype='int64', name='OBJECTID')
43186191164727 {21057, 83874} Index([14187, 21057, 83874], dtype='int64', name='OBJECTID')
43294228037942 {23263} Index([23263, 23399], dtype='int64', name='OBJECTID')
43294228039523 {23399} Index([23263, 23399], dtype='int64', name='OBJECTID')
43294364419939 set() Index([23263, 23399], dtype='int64', name='OBJECTID')
43333019146629 {2185} Index([2185, 29710, 31017], dtype='int64', name='OBJECTID')
43333019146630 {31017, 29710} Index([2185, 29710, 31017], dtype='int64', name='OBJECTID')
43334500718982 set() Index([2185, 29710, 31017], dtype='int64', name='OBJECTID')
43362131936024 set() Index([28879, 179913], dtype='int64', name='OBJECTID')
43363453207320 {179913} Index([28879, 179913], dtype='int64', name='OBJECTID')
43372077151059 {116194, 22198} Index([254, 22198, 116194], dtype='int64', name='OBJECTID')
44551806199810 set() Index([9007, 11554], dtype='int64', name='OBJECTID')
44552366993968 set() Index([9007, 11554], dtype='int64', name='OBJECTID')
53412640073573 {6492} Index([6492, 13250, 26491], dtype='int64', name='OBJECTID')
53412640077680 {26491} Index([6492, 13250, 26491], dtype='int64', name='OBJECTID')
53412874237808 {13250} Index([6492, 13250, 26491], dtype='int64', name='OBJECTID')
53429511148900 set() Index([24141], dtype='int64', name='OBJECTID')
53429817857380 set() Index([24141], dtype='int64', name='OBJECTID')
53897570906889 set() Index([10286], dtype='int64', name='OBJECTID')
53898676302601 set() Index([10286], dtype='int64', name='OBJECTID')
54030782260116 {4376} Index([795, 4376, 9308], dtype='int64', name='OBJECTID')
54030782272407 set() Index([795, 4376, 9308], dtype='int64', name='OBJECTID')
54032359265175 {795, 9308} Index([795, 4376, 9308], dtype='int64', name='OBJECTID')
54044536554368 {13883} Index([5718, 13883, 30682], dtype='int64', name='OBJECTID')
54044536561985 {30682, 5718} Index([5718, 13883, 30682], dtype='int64', name='OBJECTID')
54044705972545 set() Index([5718, 13883, 30682], dtype='int64', name='OBJECTID')
54086642907495 set() Index([17425, 92848], dtype='int64', name='OBJECTID')
54086642909843 {92848} Index([17425, 92848], dtype='int64', name='OBJECTID')
54087486227091 {17425} Index([17425, 92848], dtype='int64', name='OBJECTID')
54091442369881 {16976, 20892} Index([13856, 16976, 20892], dtype='int64', name='OBJECTID')
54091442373699 {13856} Index([13856, 16976, 20892], dtype='int64', name='OBJECTID')
54091713168451 set() Index([13856, 16976, 20892], dtype='int64', name='OBJECTID')
54161826681669 {25291} Index([2466, 25291], dtype='int64', name='OBJECTID')
54161826682262 {2466} Index([2466, 25291], dtype='int64', name='OBJECTID')
54162008413590 set() Index([2466, 25291], dtype='int64', name='OBJECTID')
54396655850374 set() Index([16026, 19900, 21263], dtype='int64', name='OBJECTID')

2625

In [347]:
start_match.sort_index()

INTID
5710837346          Index([20353, 20860], dtype='int64', name='OBJ...
10005800273         Index([9233, 13504], dtype='int64', name='OBJE...
14300767569             Index([7109], dtype='int64', name='OBJECTID')
18011691414                                                        {}
23945910678                                                        {}
                                          ...
2698419891660598    Index([19268, 19602], dtype='int64', name='OBJ...
2698428751996728    Index([1638, 6101], dtype='int64', name='OBJEC...
2698437341931319    Index([5496, 26925], dtype='int64', name='OBJE...
2698443752596326      Index([105004], dtype='int64', name='OBJECTID')
2698447711168309    Index([4069, 8304], dtype='int64', name='OBJEC...
Name: GEOMETRY, Length: 20946, dtype: object

In [ ]:
wm = both[both.GEO_match_code != 'both']
wm

def gm(row):
    int_id, cl_id = row.name

    cl_geo_close = row.GEO_close
    cl_geo_far = row.GEO_far 
    int_point = row.intersection_point 

    cl = centerlines.loc[cl_id]
    cl_SIFID = cl.SIFID 
    low_cross_sifid = cl.SIFIDLOW
    hi_cross_sifid = cl.SIFIDHI

    try:
        centerlines_by_SIFID_SIFIDLOW[low_cross_sifid, cl_SIFID]
    except KeyError:
        pass
    try:
        centerlines_by_SIFID_SIFIDHI[hi_cross_sifid, cl_SIFID]
    except KeyError:
        pass

        
    cl_low_geo_start = ...
    cl_low_geo_end = ...

    cl_hi_geo_start = ...
    cl_hi_geo_end = ...

                        int_match  hi_match  low_match  \
int_id           cl_id
10005800273      7109           1      True       True
14300767569      7109           1      True       True
91610177636      31054          2      True       True
582312564550     7992           1      True       True
                 21943          2      True       True
...                           ...       ...        ...
2697659918312745 4934           1      True       True
2698219353024632 27847          1      True       True
2698235477223204 96             1      True       True
                 6074           2      True       True
2698443752596326 8034           2      True       True

                                              intersection_point  \
int_id           cl_id
10005800273      7109    [-85.52816882852979, 38.20037561255241]
14300767569      7109   [-85.52841872335158, 38.200360349057064]
91610177636      31054  [-85.49041133329159, 38.204811157321686]
582312564550     7992    [-85.48918423050128, 38.25469997424565]
                 21943   [-85.48918423050128, 38.25469997424565]
...                                                          ...
2697659918312745 4934   [-85.59552658739156, 38.118673033102404]
2698219353024632 27847   [-85.55849963244644, 38.24249765745603]
2698235477223204 96      [-85.60771003631034, 38.32844290109257]
                 6074    [-85.60771003631034, 38.32844290109257]
2698443752596326 8034    [-85.52706694300736, 38.22235647012922]

                       GEO_match_code  \
int_id           cl_id
10005800273      7109             end
14300767569      7109           start
91610177636      31054            end
582312564550     7992             end
                 21943            end
...                               ...
2697659918312745 4934             end
2698219353024632 27847            end
2698235477223204 96             start
                 6074           start
2698443752596326 8034             end

                                                       GEO_close  \
int_id           cl_id
10005800273      7109    [-85.52816882852979, 38.20037561255241]
14300767569      7109   [-85.52841872335158, 38.200360349057064]
91610177636      31054  [-85.49041133329159, 38.204811157321686]
582312564550     7992    [-85.48918423050128, 38.25469997424565]
                 21943   [-85.48918423050128, 38.25469997424565]
...                                                          ...
2697659918312745 4934   [-85.59552658739156, 38.118673033102404]
2698219353024632 27847   [-85.55849963244644, 38.24249765745603]
2698235477223204 96      [-85.60771003631034, 38.32844290109257]
                 6074    [-85.60771003631034, 38.32844290109257]
2698443752596326 8034    [-85.52706694300736, 38.22235647012922]

                                                         GEO_far  close_angle  \
int_id           cl_id
10005800273      7109   [-85.52841872335158, 38.200360349057064]          0.0
14300767569      7109    [-85.52816882852979, 38.20037561255241]          0.0
91610177636      31054   [-85.49945278036108, 38.20743661819182]          0.0
582312564550     7992    [-85.49091110522652, 38.25286219846074]          0.0
                 21943   [-85.49091110522652, 38.25286219846074]          0.0
...                                                          ...          ...
2697659918312745 4934    [-85.59973607672718, 38.12006181925096]          0.0
2698219353024632 27847   [-85.55812792258003, 38.24290938778276]          0.0
2698235477223204 96     [-85.60544072029754, 38.329357281872326]          0.0
                 6074   [-85.60544072029754, 38.329357281872326]          0.0
2698443752596326 8034      [-85.5284541859341, 38.2171605272513]          0.0

                        far_angle
int_id           cl_id
10005800273      7109    0.000003
14300767569      7109    0.000003
91610177636      31054   0.000132
582312564550     7992    0.000040
                 21943   0.000040
...                           ...
2697659918312745 4934    0.000063
2698219353024632 27847   0.000009
2698235477223204 96      0.000035
                 6074    0.000035
2698443752596326 8034    0.000093

[2023 rows x 9 columns]

In [293]:
#cl_gg_start = centerlines.groupby(centerlines.GEO_start.apply(tuple)).groups
#cl_gg_end = centerlines.groupby(centerlines.GEO_end.apply(tuple)).groups

int_gg = intersections.groupby(intersections.GEOMETRY.apply(tuple)).groups

#gg_map = pd.concat((int_gg, cl_gg_start, cl_gg_end), axis=1, keys=['int_ids', 'cl_start', 'cl_end'])

In [370]:


#me = defaultdict(int)
#ms = defaultdict(int) 
mb = defaultdict(int)

for int_point, int_ids in int_gg.items():

    starts = cl_gg_start.get(int_point, None)
    if starts is not None:
        for int_id in int_ids:
            for cl_id in starts:
                mb[(int_id, cl_id)] |= 0b10

    ends = cl_gg_end.get(int_point, None)
    if ends is not None:
        for int_id in int_ids:
            for cl_id in ends:
                mb[(int_id, cl_id)] |= 0b01

mb = pd.Series(mb, name='point_matches')
mb.index.set_names(['int_id', 'cl_id'], inplace=True)
mb

int_id           cl_id
607025278104711  1334      2
                 4613      2
                 11316     1
607020983137801  11316     2
                 20599     1
                          ..
709691547185296  38147     2
                 38158     1
726338898139543  108844    1
726784057799682  108844    2
                 177349    1
Name: point_matches, Length: 66474, dtype: int64

In [372]:
hh = pd.concat((mb, matchdfnumeric), axis=1).convert_dtypes()
hh.dropna()

                       point_matches   0
int_id          cl_id
607025278104711 1334               2   6
                4613               2   5
                11316              1   9
607020983137801 11316              2   5
                20599              1  10
...                              ...  ..
709671528034448 38147              1  10
709684886827152 38123              1  10
                38130              1   9
709691547185296 38147              2   6
                38158              1   9

[58707 rows x 2 columns]

In [235]:
ii=hh[hh[0].notna() & hh[1].notna()]
ii[ii[0]==3]

                        0   1
int_id           cl_id
447953572487975  24013  3  13
422433206461753  27636  3  14
2696517125592441 7478   3  14
690789222245942  6389   3  14

In [ ]:

matches = gg_map.int_ids.notna() & (gg_map.cl_start.notna() | gg_map.cl_end.notna())
gg_mm = gg_map[matches]

,,int_ids,cl_start,cl_end
-85.936859,38.005901,"Index([607025278104711], dtype='int64', name='...","Index([1334, 4613], dtype='int64', name='OBJEC...","Index([11316], dtype='int64', name='OBJECTID')"
-85.935704,38.006712,"Index([607020983137801], dtype='int64', name='...","Index([11316], dtype='int64', name='OBJECTID')","Index([20599, 21796], dtype='int64', name='OBJ..."
-85.926923,38.012872,"Index([607007728145938], dtype='int64', name='...","Index([2808, 21796], dtype='int64', name='OBJE...","Index([15032], dtype='int64', name='OBJECTID')"
-85.921471,38.018520,"Index([623530856224919], dtype='int64', name='...","Index([22217], dtype='int64', name='OBJECTID')","Index([22427, 25011], dtype='int64', name='OBJ..."
-85.921173,38.018295,"Index([623565197154097], dtype='int64', name='...","Index([15032, 25011], dtype='int64', name='OBJ...","Index([27330], dtype='int64', name='OBJECTID')"
...,...,...,...,...
-85.406573,38.125504,"Index([709671528034448], dtype='int64', name='...","Index([38122, 38123], dtype='int64', name='OBJ...","Index([38147], dtype='int64', name='OBJECTID')"
-85.404792,38.127515,"Index([709684886827152], dtype='int64', name='...",0,"Index([38123, 38130], dtype='int64', name='OBJ..."
-85.399015,38.115176,"Index([709691547185296], dtype='int64', name='...","Index([38147], dtype='int64', name='OBJECTID')","Index([38158], dtype='int64', name='OBJECTID')"
-85.347920,38.206860,"Index([726338898139543], dtype='int64', name='...",0,"Index([108844], dtype='int64', name='OBJECTID')"
-85.347451,38.208679,"Index([726784057799682], dtype='int64', name='...","Index([108844], dtype='int64', name='OBJECTID')","Index([177349], dtype='int64', name='OBJECTID')"

In [ ]:

def match_ids(gf):
    gf = gf.fillna('')
    se_map = defaultdict(lambda :[False, False])
    for row in gf.itertuples():
        int_ids = row.int_ids
        starts = row.cl_start
        ends = row.cl_end 
        for int_id in int_ids:
            for cl_start in starts:
                se_map[(int_id, cl_start)][0] = True 
            for cl_end in ends:
                se_map[(int_id, cl_end)][1] = True 
    return se_map
    

se = match_ids(gg_mm)
#gg_mm.fillna('')
pd.DataFrame.from_dict

ValueError: Expected 'index', 'columns' or 'tight' for orient parameter. Got 'records' instead

In [ ]:


c = centerlines_by_SIFID_SIFIDHI.combine(
    centerlines_by_SIFID_SIFIDLOW, lambda x, y:x.union(y), fill_value=pd.Index(()))

def get_cl_cross_geos(cl_id):
    cl = centerlines.loc[cl_id]
    sifid = cl.SIFID 
    low = cl.SIFIDLOW
    hi = cl.SIFIDHI 

    try:
        low_cl_match  = c.loc[low, sifid]
    except KeyError:
        low_cl_match = None

    try:
        hi_cl_match = c.loc[hi, sifid]
    except KeyError:
        if low_cl_match is None:
            return "no match"

1      591      Index([6313, 10250, 15159, 28655], dtype='int6...
       897                         Index([26919], dtype='object')
       906      Index([29463, 31519], dtype='int64', name='OBJ...
       1813                        Index([11063], dtype='object')
       2252                        Index([25407], dtype='object')
                                      ...
15640  8594                       Index([180227], dtype='object')
15641  2072                       Index([180229], dtype='object')
       8594                       Index([180229], dtype='object')
15642  8594                       Index([180236], dtype='object')
       15611                      Index([180236], dtype='object')
Length: 43418, dtype: object

In [ ]:

def do(row):
    sif = row.SIFID 
    low = row.SIFIDLOW
    hi = row.SIFIDHI
    geo_start = row.GEO_start
    geo_end = row.GEO_end 

    try:
        low_match = c.loc[low, sif]
    except KeyError:
        low_match = None

    try:
        hi_match = c.loc[hi, sif]
    except KeyError:
        hi_match = None 
    
    return {"low_match":low_match, "hi_match":hi_match}

centerlines.apply(do, axis=1)

OBJECTID
1                   {'low_match': [6013], 'hi_match': None}
2         {'low_match': [3753, 23064], 'hi_match': [2808...
3         {'low_match': [20485, 24494, 27237], 'hi_match...
4         {'low_match': [84286, 84288], 'hi_match': [842...
5                  {'low_match': [18357], 'hi_match': None}
                                ...
180232            {'low_match': None, 'hi_match': [145324]}
180233        {'low_match': [180235], 'hi_match': [180236]}
180234        {'low_match': [180236], 'hi_match': [180235]}
180235    {'low_match': [176706, 176711, 180233, 180234]...
180236    {'low_match': [180233, 180234], 'hi_match': None}
Length: 34215, dtype: object

In [ ]:
def cl_geo_match(row):
    int_id, cl_id = row.name
    intersection = intersections.loc[int_id]
    centerline = centerlines.loc[cl_id]

In [ ]:

def do(row):
    int_id, cl_id = row.name

    int_match = row.int_match
    assert int_match != 0b11

    low_match = row.low_match
    hi_match = row.hi_match
    GEO_match = row.GEO_match_code

    if low_match ^ hi_match:
        if GEO_match != 'both':
            # normal case
            if int_match == 1:
                int_FST_cl_match[int_id].append(cl_id)
            else: # int_match == 2:
                int_SEC_cl_match[int_id].append(cl_id)
            
            if GEO_match == 'hi':
                cl_hi_int_match[cl_id].append(int_id) 
            else: # GEO_match == 'low' 
                cl_low_int_match[cl_id].append(int_id)
        else:
            # impossible for this data
            raise ValueError
    elif low_match & hi_match:
        if GEO_match == 'both':
            # easy?
            if int_match == 1:
                int_FST_cl_match[int_id].append(cl_id)
            elif  int_match == 2: 
                int_SEC_cl_match[int_id].append(cl_id)
            cl_hi_int_match[cl_id].append(int_id) 
            cl_low_int_match[cl_id].append(int_id)
        else:
            # most complex case
            cl_geo_match(row)
            ...
    else:
        # impossible case
        raise ValueError
    
ee = direct_matches.apply(do, axis=1)

In [115]:
len(both[both.GEO_match_code != 'both']) == len(not_m) # True. Good news
not_m

[(10005800273, 7109),
 (14300767569, 7109),
 (91610177636, 31054),
 (582312564550, 7992),
 (582312564550, 21943),
 (1119183476550, 7992),
 (1119183476550, 21943),
 (1379545420614, 25745),
 (1413953435207, 4267),
 (1444018206279, 4267),
 (1478966155554, 14679),
 (1478966155554, 31731),
 (1483261122850, 14679),
 (1483261122850, 31731),
 (1521279341382, 25745),
 (1650764847510, 4286),
 (1650764847510, 7578),
 (2204250564471, 29651),
 (2208545531767, 29651),
 (2574101274724, 31054),
 (2762860829078, 931),
 (3510485686678, 7578),
 (3719459635475, 17799),
 (3719459635475, 29332),
 (3719459635475, 30005),
 (3801064014099, 29332),
 (3801064014099, 31236),
 (4702205957409, 4158),
 (4706500924705, 4158),
 (4710859920674, 16624),
 (4710859920674, 19924),
 (4715154887970, 16624),
 (4715154887970, 19924),
 (4849707002201, 20792),
 (4879771773273, 20792),
 (5923683146134, 24566),
 (6017656526883, 25208),
 (8127274981782, 18901),
 (8131569949078, 8772),
 (8131569949078, 18901),
 (8140159883670, 931),
 (8140159883670, 8772),
 (8965612730422, 23909),
 (8969907697718, 23909),
 (9908831851634, 10493),
 (9908831851634, 17323),
 (9913126818930, 10493),
 (9913126818930, 17323),
 (9973837306262, 12225),
 (9978132273558, 12225),
 (9978132273558, 26424),
 (10547708286056, 7765),
 (10547708286056, 25601),
 (10547708286056, 29827),
 (10552003253352, 7765),
 (10552003253352, 25601),
 (10552003253352, 29827),
 (17906641901974, 24566),
 (17906641901974, 26424),
 (18106798231921, 25647),
 (18149747904881, 25647),
 (19866476205097, 15554),
 (19883656074281, 15554),
 (19951620495766, 4286),
 (20276646943125, 9105),
 (20276646943125, 12704),
 (20293840312725, 137954),
 (20303981091221, 14793),
 (20409839163799, 904),
 (20450321406359, 8729),
 (22344401998722, 5940),
 (23111610307096, 25074),
 (23111610307096, 25610),
 (23115905274392, 25074),
 (23115905274392, 25610),
 (24774520620161, 2287),
 (24774520620161, 13874),
 (24778815587457, 2287),
 (24778815587457, 13874),
 (24844528292385, 1119),
 (24844528292385, 9428),
 (25293169706112, 5310),
 (25301759640704, 5310),
 (25308384760353, 1119),
 (25308384760353, 9428),
 (25370998363223, 16054),
 (25396768166999, 16054),
 (25430812152082, 19929),
 (25452286988562, 19929),
 (25572607858231, 18758),
 (25572607858231, 18958),
 (25856330704953, 3395),
 (25856330704953, 20579),
 (25925050181689, 3395),
 (25925050181689, 20579),
 (26543553803570, 25545),
 (26543553803570, 29935),
 (28146369132289, 4530),
 (28146369132289, 18553),
 (35215598178663, 30763),
 (35348742164839, 30763),
 (35606461973569, 11082),
 (35606461973569, 32588),
 (35683771384897, 11082),
 (35683771384897, 32588),
 (35837748785476, 20021),
 (35837748785476, 20291),
 (35842043687236, 30593),
 (35842043752772, 20021),
 (35842043752772, 20291),
 (36323080024388, 30593),
 (36529015640099, 7507),
 (36559080411171, 7507),
 (36590170887559, 20265),
 (36873638729095, 20265),
 (37665078089271, 31797),
 (37682257958455, 31797),
 (37699178497573, 5357),
 (37699178497573, 17959),
 (37808875193638, 24705),
 (37825851770915, 32037),
 (37834644997414, 24705),
 (37877391378467, 32037),
 (37896746993189, 5357),
 (37896746993189, 17959),
 (38796717660451, 31062),
 (38856847202595, 31062),
 (39004583392855, 682),
 (39583845937458, 3424),
 (39613910708530, 3424),
 (39670303323735, 682),
 (40699115667584, 13360),
 (40699115667584, 24423),
 (40854568009811, 29609),
 (40854568009811, 29659),
 (40922453966976, 13360),
 (40922453966976, 24423),
 (40967299625304, 26046),
 (41047077122672, 13132),
 (41047077122672, 23189),
 (41163805655123, 29609),
 (41163805655123, 29659),
 (41202298935616, 23543),
 (41267947336024, 26046),
 (41871710843504, 13132),
 (41871710843504, 23189),
 (42228193125698, 26363),
 (42430056588610, 26363),
 (42912134227255, 83879),
 (42972276217750, 10862),
 (43019520858006, 10862),
 (43234269222807, 4681),
 (43238564190103, 4681),
 (43469704807574, 16117),
 (43469704807574, 25335),
 (44071000229014, 16117),
 (44071000229014, 25335),
 (44543793920007, 27309),
 (45080131312023, 10335),
 (45148850788759, 904),
 (45148850788759, 10335),
 (45455895660164, 11463),
 (45455895660164, 32837),
 (45722183632516, 11463),
 (45722183632516, 32837),
 (52777524359830, 32602),
 (52794704229014, 32602),
 (54027223322646, 11584),
 (54027223322646, 28487),
 (54084517270934, 2466),
 (54084517270934, 24940),
 (54100237766678, 11584),
 (54100237766678, 28487),
 (54161826681669, 2799),
 (54161826681669, 25291),
 (54161826682262, 2466),
 (54161826682262, 24940),
 (54192037599639, 18621),
 (54192037599639, 20876),
 (54363690144581, 2799),
 (54363690144581, 25291),
 (55182835146885, 8636),
 (55221489852549, 8636),
 (55557599889520, 7846),
 (55557599889520, 24999),
 (56221450135841, 25280),
 (56238630005025, 25280),
 (56424632120600, 16589),
 (56433222055192, 16589),
 (56436987218243, 7752),
 (56702217263509, 4651),
 (56707141611553, 18665),
 (56711436578849, 18665),
 (57243383142805, 4651),
 (57243383142805, 15785),
 (57333577456021, 10555),
 (57333577456021, 15785),
 (57518261049749, 3337),
 (57518261049749, 10555),
 (57659994970517, 3337),
 (57682088571493, 17511),
 (58284961990272, 32437),
 (58774588262016, 32437),
 (58777305231973, 17511),
 (58829564896148, 10482),
 (58829564896148, 24415),
 (58833859863444, 10482),
 (58833859863444, 24415),
 (60576595669785, 6795),
 (60576595669785, 25530),
 (60624412887377, 9979),
 (60679674884889, 6795),
 (60679674884889, 25530),
 (60886405892433, 9979),
 (60967667066453, 22747),
 (61051234472981, 13422),
 (61122285889109, 22747),
 (61579515435302, 96359),
 (61929737786161, 21557),
 (63174714884505, 28151),
 (63232682853440, 27769),
 (63232682853440, 31225),
 (63249862722624, 27769),
 (63249862722624, 31225),
 (70442704455577, 21391),
 (70446999422873, 21391),
 (70749137572152, 3927),
 (70749137572152, 5461),
 (70753432539448, 3927),
 (70753432539448, 5461),
 (72088630237590, 25187),
 (72092925204886, 25187),
 (72092925204886, 29094),
 (72705295061345, 13089),
 (72705295061345, 20307),
 (72709590028641, 13089),
 (72709590028641, 20307),
 (72980906403079, 16453),
 (72993791304967, 16453),
 (72998086268725, 30617),
 (72998086268725, 164554),
 (73002381236021, 30617),
 (73002381236021, 164554),
 (74096796180769, 12327),
 (74165515657505, 12327),
 (74180554293655, 11567),
 (74219588720697, 15679),
 (74219588720697, 32073),
 (74223503966615, 11567),
 (74241063557177, 15679),
 (74241063557177, 32073),
 (75076951568728, 911),
 (75111311307096, 911),
 (75179717980505, 10163),
 (75179717980505, 12654),
 (75184012947801, 10163),
 (75184012947801, 12654),
 (75215347878260, 72050),
 (75219642845556, 72050),
 (75318852620581, 22413),
 (76016998749751, 18758),
 (76016998749751, 18958),
 (76081706595634, 25545),
 (76081706595634, 29935),
 (76315398214672, 13798),
 (76354052920336, 13798),
 (76499110950657, 4530),
 (76499110950657, 18553),
 (76976601794672, 7846),
 (76976601794672, 24999),
 (77207137972770, 30663),
 (77211432940066, 30663),
 (77598291085635, 7752),
 (78104821322516, 15293),
 (78139181060884, 15293),
 (78444676546934, 727),
 (78444676546934, 14254),
 (78496216154486, 727),
 (78496216154486, 14254),
 (78624518792057, 31510),
 (78714713105273, 31510),
 (79476291699750, 15777),
 (79536421241894, 15777),
 (80441537553921, 17080),
 (80475897292289, 17080),
 (80900629481864, 16891),
 (80900629481864, 18765),
 (80922104318344, 16891),
 (80922104318344, 18765),
 (88468427388513, 8085),
 (88468427388513, 32061),
 (88519967035797, 21712),
 (88519967035797, 22935),
 (88524262003093, 21712),
 (88524262003093, 22935),
 (89234227885685, 21746),
 (89234227885685, 23585),
 (89239104756004, 32046),
 (89269169592614, 96359),
 (89282054428964, 32046),
 (89288679478423, 10666),
 (89292974428977, 21557),
 (89362818832790, 13013),
 (89371661605271, 8729),
 (89371661605271, 168073),
 (89410316310935, 168076),
 (89478435989128, 11775),
 (89478435989128, 23887),
 (89482730956424, 11775),
 (89482730956424, 23887),
 (89627483871637, 15014),
 (89631778838933, 15014),
 (89631778838933, 25271),
 (89636073806229, 15598),
 (89636073806229, 25271),
 (89640368773525, 12704),
 (89640368773525, 15598),
 (89649259288695, 16963),
 (89649259288695, 19499),
 (89683619027063, 6882),
 (89687913994359, 6882),
 (89687913994359, 16963),
 (89687913994359, 19499),
 (89706674288245, 21746),
 (89706674288245, 23585),
 (90331861562736, 10146),
 (90336156530032, 10146),
 (90539408005525, 15986),
 (90539408005525, 26833),
 (90543702972821, 12004),
 (90543702972821, 24932),
 (90578062711189, 10338),
 (90586652645781, 1259),
 (90586652645781, 26833),
 (90590947613077, 1259),
 (90590947613077, 24932),
 (90599537547669, 10338),
 (90599537547669, 12004),
 (90608127482261, 15986),
 (90718419065237, 137954),
 (90735499178069, 13539),
 (90735499178069, 24330),
 (90735499178370, 31889),
 (92364083468355, 29130),
 (92376968370243, 29130),
 (92394148218419, 18288),
 (92394148218419, 18394),
 (92573745180757, 13539),
 (92573745180757, 24330),
 (92573745181058, 31889),
 (92591024806294, 24152),
 (92737321276515, 4471),
 (92788860884067, 4471),
 (93818494440985, 84233),
 (93844263981577, 4242),
 (93874329081369, 10103),
 (93874329081369, 84239),
 (93874329081369, 84243),
 (93878623719945, 4242),
 (93939627487553, 2833),
 (93939627487553, 7810),
 (93943922454849, 2833),
 (93943922454849, 7810),
 (94009478701876, 23718),
 (94018068636468, 23718),
 (94573191008549, 22413),
 (94584578609446, 5702),
 (94584578609446, 32473),
 (94588873576742, 5702),
 (94588873576742, 32473),
 (95666176460088, 933),
 (95666176460088, 4860),
 (95670471427384, 933),
 (95670471427384, 4860),
 (95971119138166, 28541),
 (96001183909238, 28541),
 (96215942897945, 17743),
 (96795763482905, 17743),
 (96986671970355, 15847),
 (96986671970355, 25891),
 (96990966937651, 15847),
 (96990966937651, 25891),
 (97893394716050, 13438),
 (97944934323602, 13438),
 (106070715831701, 17781),
 (106070715831701, 20671),
 (106075010798997, 17781),
 (106075010798997, 20671),
 (106830954465288, 30907),
 (106882494072840, 30907),
 (107165399685525, 3245),
 (107208349358485, 3245),
 (107208349358485, 20614),
 (107212644325781, 14793),
 (107212644325781, 20614),
 (107305618444374, 2739),
 (107309913411670, 2739),
 (107895350128946, 27391),
 (107903940063538, 27391),
 (108112954005861, 27218),
 (108117248973157, 27218),
 (108177447623061, 9105),
 (108890993948679, 27309),
 (109079426245781, 24310),
 (109148145722517, 24310),
 (110447066141570, 5940),
 (111073226154776, 16687),
 (111077521122072, 16687),
 (111330393867792, 13004),
 (111360458638864, 13004),
 (111411845428758, 29885),
 (111536399480342, 29885),
 (113329442298263, 18621),
 (114712224696114, 15506),
 (114729404565298, 15506),
 (114905498880021, 14444),
 (114931268683797, 14444),
 (115547513635927, 32132),
 (115590463308887, 32132),
 (115625737840384, 32189),
 (116021850708374, 14214),
 (116021850708374, 29094),
 (116026145675670, 14214),
 (116074031403378, 19665),
 (116074031403378, 26200),
 (116079300104563, 2027),
 (116079300104563, 4326),
 (116099801207154, 19665),
 (116099801207154, 26200),
 (123368914520389, 749),
 (123386094389573, 749),
 (124395458681158, 22459),
 (124404048615750, 22459),
 (124488846070131, 2027),
 (124488846070131, 4326),
 (124863409068438, 20395),
 (124863409068438, 24152),
 (124902063774102, 20395),
 (125426844864609, 7168),
 (125426844864609, 30452),
 (125439729766497, 7168),
 (125439729766497, 30452),
 (127002200349074, 15382),
 (127002200349074, 29355),
 (127010790283666, 15382),
 (127010790283666, 29355),
 (129948604264755, 10564),
 (129957194199347, 10564),
 (130180480856836, 31464),
 (132229821391361, 12712),
 (132234116358657, 12712),
 (133557973719446, 27680),
 (133561810772884, 31295),
 (133596628425110, 4148),
 (133596628425110, 27680),
 (133613350380436, 18908),
 (133613350380436, 27914),
 (133613350380436, 31295),
 (133617645347732, 18908),
 (133617645347732, 27914),
 (141082282513977, 31325),
 (141250275956068, 13865),
 (141357160420921, 31325),
 (141976125429092, 13865),
 (141992026150947, 25208),
 (142208037853590, 4148),
 (142961583248995, 14154),
 (142961583248995, 25027),
 (142965878216291, 14154),
 (142965878216291, 25027),
 (143022469978518, 3797),
 (143022469978518, 26120),
 (143031059913110, 3797),
 (143031059913110, 30412),
 (143039649847702, 26120),
 (143078331029910, 18018),
 (143078331029910, 18280),
 (143108336032150, 19756),
 (143108336032150, 31811),
 (143233006072465, 811),
 (143233006072465, 25979),
 (144042808956201, 3876),
 (144059988825385, 3876),
 (144066500437525, 12681),
 (144070743959061, 17097),
 (144074745272645, 27126),
 (144113399978309, 27126),
 (145243045881602, 6873),
 (145487877587478, 27187),
 (145569687545365, 17097),
 (145754422584853, 12681),
 (146243994341732, 140274),
 (146243994341732, 140276),
 (146248289309028, 140274),
 (146248289309028, 140276),
 (146797793539334, 13300),
 (146797793539334, 23771),
 (146802088506630, 13300),
 (146802088506630, 23771),
 (148675465613832, 31420),
 (148679760581128, 31420),
 (149675457016465, 811),
 (149675457016465, 25979),
 (150933006308417, 15088),
 (150933006308417, 32831),
 (150995285202581, 22939),
 (150995285202581, 29428),
 (151137019123349, 22939),
 (151137019123349, 29428),
 (151214345115237, 7306),
 (151274474657381, 7306),
 (158779843401080, 1115),
 (161112864596323, 23104),
 (163987040911942, 1622),
 (163991335879238, 1622),
 (165342635021575, 5490),
 (165342635021576, 16408),
 (165342635021576, 19104),
 (165346929988872, 16408),
 (165346929988872, 19104),
 (165351224956167, 5490),
 (166537442400662, 13733),
 (166610731481378, 18498),
 (166614751811990, 13733),
 (166614751811990, 18280),
 (167130422524194, 18498),
 (167276176775574, 18018),
 (167491936803141, 17540),
 (167607900920133, 17540),
 (282602257282857, 2925),
 (282602257282857, 14551),
 (282606552250153, 2925),
 (282606552250153, 14551),
 (283851271493140, 6200),
 (283851271493140, 25538),
 (283881336264212, 6200),
 (283881336264212, 25538),
 (283949033275926, 27187),
 (284045354235505, 10633),
 (284045354235505, 16209),
 (284195724228913, 19022),
 (284195724228913, 19029),
 (284225788999985, 19022),
 (284225788999985, 19029),
 (284876717822776, 9144),
 (284876717822776, 12058),
 (284881012790072, 9144),
 (284881012790072, 12058),
 (284988401542036, 4539),
 (284988401542036, 29524),
 (284992696509332, 4539),
 (284992696509332, 29524),
 (285342428591652, 115556),
 (285424041096853, 10619),
 (285424041096853, 10716),
 (285428336064149, 10619),
 (285428336064149, 10716),
 (285893695493496, 1115),
 (286105010446721, 4238),
 (287062754892182, 11426),
 (287071344826774, 11426),
 (287071344826774, 31811),
 (287109999532438, 19756),
 (287139310064788, 3062),
 (287268084699173, 5473),
 (287268084699173, 20863),
 (287272379666469, 5473),
 (287272379666469, 20863),
 (288091429507366, 17795),
 (288112904343846, 17795),
 (288707760628097, 4238),
 (289408059512904, 14704),
 (289412354480200, 14704),
 (289622637118516, 84202),
 (289743344816151, 33131),
 (289751934750743, 33131),
 (290701776807737, 4492),
 (290701776807737, 30801),
 (291674810603078, 12396),
 (291679105570374, 12396),
 (299576273244473, 25442),
 (299584863179065, 25442),
 (300342039401618, 188),
 (300342039401618, 1011),
 (300393579009170, 188),
 (300393579009170, 1011),
 (300458003649684, 3062),
 (301336002646053, 6424),
 (301348887547941, 6424),
 (301643391685430, 6877),
 (301643391685430, 29567),
 (301647686652726, 6877),
 (301647686652726, 29567),
 (301901900192150, 15036),
 (301901900192150, 30412),
 (303546868377240, 3314),
 (303551163344536, 3314),
 (304874017560982, 15036),
 (305123118031203, 23104),
 (306029325017126, 30917),
 (306076569657382, 30917),
 (308243513579913, 21568),
 (308243513579913, 23975),
 (308247808547209, 21568),
 (308247808547209, 23975),
 (308277873381670, 17162),
 (308282168281378, 7916),
 (308295053183266, 7916),
 (308363772727590, 17162),
 (309341564585730, 12621),
 (317833627539861, 5629),
 (317863102683541, 11375),
 (317863102683541, 26648),
 (317909241979973, 1800),
 (317923705198999, 10364),
 (317927490754967, 24176),
 (317965662919063, 25288),
 (318175795386776, 2270),
 (318198054610305, 29702),
 (318241865177497, 11800),
 (318254750079385, 11800),
 (318254750079385, 16727),
 (318263340013977, 9730),
 (318263340013977, 16727),
 (318310584654233, 9730),
 (318343617860921, 30076),
 (318382272566585, 30076),
 (319438198302071, 22602),
 (319442493269367, 22602),
 (319447168607301, 2612),
 (319962564682821, 2612),
 (319988006151527, 18256),
 (320026660857191, 18256),
 (320041370743350, 12745),
 (320045665710646, 12745),
 (320053850498419, 26078),
 (320113980040563, 26078),
 (320233172783401, 21996),
 (320314485851170, 30080),
 (320314485851170, 31165),
 (320318718625126, 22514),
 (320323367096617, 21996),
 (320379176510839, 16320),
 (320383471478135, 16320),
 (320400323003750, 22514),
 (320444576651414, 8301),
 (320538348250483, 702),
 (320577002956147, 702),
 (320616194871833, 15083),
 (320616194871833, 17249),
 (321058576503321, 15083),
 (321058576503321, 17249),
 (321075936843926, 8301),
 (321139578847764, 17685),
 (321216888259092, 17685),
 (321359117375638, 16194),
 (321418292446242, 30080),
 (321418292446242, 31165),
 (321470786525334, 16194),
 (321509475509332, 26938),
 (321629734593620, 26938),
 (321632978622614, 13370),
 (321688813197462, 13370),
 (322311832082562, 3061),
 (322363371690114, 3061),
 (322523087791172, 9890),
 (322535972693060, 9890),
 (322664821712240, 16263),
 (322716361319792, 16263),
 (323339131577718, 24717),
 (323360606414198, 24717),
 (323415640139140, 21324),
 (323433620858246, 29253),
 (323467179746692, 21324),
 (323485160465798, 29253),
 (323561448605476, 11795),
 (323703214986505, 30117),
 (323768377894262, 3984),
 (323811327567222, 3984),
 (323827650687044, 18779),
 (323879190294596, 18779),
 (324455572661608, 16259),
 (324498522334568, 16259),
 (324514963805449, 30117),
 (324699935827332, 15431),
 (324708695889205, 24153),
 (324712990856501, 24153),
 (324717115696516, 15431),
 (324781540205942, 13796),
 (324794425107830, 13796),
 (325009059111509, 7135),
 (325013354078805, 7135),
 (326036496998758, 12308),
 (326040791966054, 12308),
 (326075010278774, 4986),
 (326109370017142, 4986),
 (326662748333444, 16500),
 (326701099917957, 9366),
 (326705394885253, 9366),
 (326726869721721, 18193),
 (326731467810180, 16500),
 (326769819394681, 18193),
 (326778409346132, 907),
 (326782704313428, 907),
 (326795589215302, 4777),
 (326799884182598, 4777),
 (326851423790168, 8945),
 (326855718757464, 8945),
 (326907258365024, 11175),
 (326911553332320, 11175),
 (326924438234184, 20570),
 (326928733201480, 20570),
 (326967387941253, 20385),
 (326975977875845, 20385),
 (327006042612816, 11580),
 (327036107383888, 11580),
 (327041449169446, 26979),
 (327058629038630, 26979),
 (327109415506470, 32957),
 (327126595375654, 32957),
 (327186431239528, 15717),
 (327190726206824, 15717),
 (334420136584580, 7218),
 (334458791290244, 7218),
 (334484561094006, 6600),
 (334497445995894, 6600),
 (334540395668870, 25191),
 (334544690636166, 25191),
 (334630104491092, 22636),
 (334664464229460, 22636),
 (334673054164038, 11640),
 (334681644098630, 11640),
 (334703311873412, 1730),
 (334810686055812, 1730),
 (335430002369176, 3578),
 (335527246583959, 32363),
 (335561606322327, 32363),
 (335591671079428, 17356),
 (335647769502850, 26749),
 (335651800621572, 17356),
 (335708421252484, 6018),
 (335729616496132, 28201),
 (335798093358210, 26749),
 (335832695711236, 28201),
 (335837270271364, 6018),
 (335909962916994, 31333),
 (335978682393730, 31333),
 (336455495935364, 11699),
 (336472403227954, 24110),
 (336520170068119, 7734),
 (336528510379396, 11699),
 (336537349937303, 7734),
 (336541122704690, 24110),
 (336730368796036, 25737),
 (336760433567108, 25737),
 (336817382988181, 5629),
 (337009566836100, 29538),
 (337031041672580, 29538),
 (337640634328964, 19035),
 (337692173936516, 19035),
 (337834730412183, 11061),
 (337851096524164, 3671),
 (337860500215959, 11061),
 (337906931098994, 18853),

In [110]:
len(not_m)

2023

In [ ]:
def do(row):
    sif = row.SIFID

    low = row.SIFIDLOW
    hi = row.SIFIDHI 

    low_pair = (low, sif)
    hi_pair = (hi, sif)


    for memo, cross in ((set(), low), (set(), hi)):
        pair = (cross, sif)
        for table in (centerlines_by_SIFID_SIFIDHI, centerlines_by_SIFID_SIFIDLOW):
            try:
                match = table.loc[pair]
            except KeyError:
                continue
            else:
                memo = match.union(memo)

,ROADNAME,SIFID,SIFCODE,low_cross_ROADNAME,SIFIDLOW,LOCROSSSIF,hi_cross_ROADNAME,SIFIDHI,HICROSSSIF,CORE_CLASS,GEO_start,GEO_end
OBJECTID,,,,,,,,,,,,
195,GOLDSMITH LN,2543,2585,DAVID GRAVES DR,14199,E998,BELMONT RD,495,0483,PRIMARY COLLECTOR,"[-85.67457458991743, 38.20539083374192]","[-85.67334993258598, 38.20602795942558]"
198,GOLDSMITH LN,2543,2585,DAVID GRAVES DR,14199,E998,SUMNER RD,5610,6210,PRIMARY COLLECTOR,"[-85.67201567611251, 38.206724595474846]","[-85.67064558883953, 38.20743107542566]"

In [ ]:

c = centerlines_by_SIFID_SIFIDHI.combine(
    centerlines_by_SIFID_SIFIDLOW, lambda x, y:x.union(y), fill_value=pd.Index(()))

In [ ]:

def match(cl):
    sifid = cl.SIFID
    low = cl.SIFIDLOW
    hi = cl.SIFIDHI

    try:
        low_match = c.loc[low, sifid]
    except KeyError:
        low_match = None
    try:
        hi_match = c.loc[hi, sifid]
    except KeyError:
        hi_match = None 

    return {"low_match":low_match, "hi_match": hi_match}


centerlines.apply(match, axis=1)

#centerlines.head(150).tail()
#centerlines.loc[centerlines_by_SIFID_SIFIDLOW.loc[2543, 14199]]

In [ ]:

def do_geo(row):
    int_id, cl_id = row.name
    if row.int_match == 1:
        int_FST_cl_match[int_id].append(cl_id)
    elif row.int_match == 2:
        int_SEC_cl_match[int_id].append(cl_id)

    geo_match = row.GEO_match_code
    if geo_match == 'start':
        cl_start_int_match[cl_id].append(int_id)
    elif geo_match == 'end':
        cl_end_int_match[cl_id].append(int_id)
    elif geo_match == 'both':
        cl_start_int_match[cl_id].append(int_id)
        cl_end_int_match[cl_id].append(int_id)

direct_matches.apply(do_geo, axis=1)

geos = pd.DataFrame.from_dict({'FST_match':int_FST_cl_match, 'SEC_match':int_SEC_cl_match})
(geos.FST_match.dropna().apply(len) > 3).any()

In [ ]:


mm = GEO_map[['int_match', 'hi_match', 'low_match', 'GEO_match_code',
               'close_angle', 'intersection_point', 'GEO_close']]
dm = mm[mm.close_angle == 0]
dm

In [729]:
dm[(dm.hi_match == True) & (dm.low_match == True)]
#) & (dm.GEO_match_code != 'both')]

                        int_match  hi_match  low_match GEO_match_code  \
int_id           cl_id
10005800273      7109           1      True       True            end
14300767569      7109           1      True       True          start
91610177636      31054          2      True       True            end
582312564550     7992           1      True       True            end
                 21943          2      True       True            end
...                           ...       ...        ...            ...
2697659918312745 4934           1      True       True            end
2698219353024632 27847          1      True       True            end
2698235477223204 96             1      True       True          start
                 6074           2      True       True          start
2698443752596326 8034           2      True       True            end

                        close_angle                        intersection_point  \
int_id           cl_id
10005800273      7109           0.0   [-85.52816882852979, 38.20037561255241]
14300767569      7109           0.0  [-85.52841872335158, 38.200360349057064]
91610177636      31054          0.0  [-85.49041133329159, 38.204811157321686]
582312564550     7992           0.0   [-85.48918423050128, 38.25469997424565]
                 21943          0.0   [-85.48918423050128, 38.25469997424565]
...                             ...                                       ...
2697659918312745 4934           0.0  [-85.59552658739156, 38.118673033102404]
2698219353024632 27847          0.0   [-85.55849963244644, 38.24249765745603]
2698235477223204 96             0.0   [-85.60771003631034, 38.32844290109257]
                 6074           0.0   [-85.60771003631034, 38.32844290109257]
2698443752596326 8034           0.0   [-85.52706694300736, 38.22235647012922]

                                                       GEO_close
int_id           cl_id
10005800273      7109    [-85.52816882852979, 38.20037561255241]
14300767569      7109   [-85.52841872335158, 38.200360349057064]
91610177636      31054  [-85.49041133329159, 38.204811157321686]
582312564550     7992    [-85.48918423050128, 38.25469997424565]
                 21943   [-85.48918423050128, 38.25469997424565]
...                                                          ...
2697659918312745 4934   [-85.59552658739156, 38.118673033102404]
2698219353024632 27847   [-85.55849963244644, 38.24249765745603]
2698235477223204 96      [-85.60771003631034, 38.32844290109257]
                 6074    [-85.60771003631034, 38.32844290109257]
2698443752596326 8034    [-85.52706694300736, 38.22235647012922]

[2027 rows x 7 columns]

In [ ]:
int_FST_cl = defaultdict(list)
int_SEC_cl = defaultdict(list)

cl_LOW_int = defaultdict(list)
cl_HI_int = defaultdict(list)
cl_start_int = defaultdict(list)
cl_end_int = defaultdict(list)


def do(row):
    int_id, cl_id = row.name
    intersection = intersections.loc[int_id]
    centerline = centerlines.loc[cl_id]

    cl_SIFID = centerline.SIFID
    int_FST = intersection.FST_SIFID
    int_SEC = intersection.SEC_SIFID
    if row.int_match == 1:
        assert cl_SIFID == int_FST
        int_FST_cl[int_id].append(cl_id)
        int_cross_SIFID = int_SEC
    elif row.int_match == 2:
        assert cl_SIFID == int_SEC
        int_SEC_cl[int_id].append(cl_id)
        int_cross_SIFID = int_FST
    
    if row.cl_match == 'low':
        assert centerline.SIFIDLOW == int_cross_SIFID
        cl_LOW_int[cl_id].append(int_id)
    elif row.cl_match == 'hi':
        assert centerline.SIFIDHI == int_cross_SIFID
        cl_HI_int[cl_id].append(int_id)

    if row.GEO_match_code == 'start':
        cl_start_int[cl_id].append(int_id)
    elif row.GEO_match_code == 'end':
        cl_end_int[cl_id].append(int_id)



#point_match = mm[mm.close_angle == 0]
dm.apply(do, axis=1)
# how to deal with 'boths' ??


int_m = pd.DataFrame.from_dict({'int_FST_cl': int_FST_cl,
                        'int_SEC_cl': int_SEC_cl})

cl_m = pd.DataFrame.from_dict({
    'cl_LOW_int': cl_LOW_int,
    'cl_HI_int': cl_HI_int,
    'cl_start_int': cl_start_int,
    'cl_end_int': cl_end_int,})

In [642]:
cf = cl_m.cl_start_int.dropna()
cf[cf.apply(len) == 2]

18519         [2418358114624, 2419564009305]
31991       [20160850481987, 20160850483577]
29458       [21376879845493, 21376879849536]
30767       [39583384491283, 39583845937458]
27033      [43316244673058, 712767631022432]
                         ...
28620     [728388906197030, 728393796624422]
132206    [728388906197030, 728398091600387]
151719    [730706905155414, 730736441292164]
170641    [846043974596247, 846168528713367]
170633    [846086924334743, 846629611828887]
Name: cl_start_int, Length: 78, dtype: object

In [662]:
def get_ints(*ints):
    for int in ints:
        display(intersections.loc[int])

get_ints(10005800273)

FST_ROADNAME                                    REHL RD
SEC_ROADNAME                          TUCKER STATION RD
SIFCODE1                                           5464
SIFCODE2                                           6551
FST_SIFID                                          4976
SEC_SIFID                                          5908
GEOMETRY        [-85.52816882852979, 38.20037561255241]
Name: 10005800273, dtype: object

In [661]:
def get_cls(*cls):
    for cl in cls:
        display(centerlines.loc[cl])

get_cls(	7109)

ROADNAME                                               REHL RD
SIFID                                                     4976
SIFCODE                                                   5464
low_cross_ROADNAME                           TUCKER STATION RD
SIFIDLOW                                                  5908
LOCROSSSIF                                                6551
hi_cross_ROADNAME                            TUCKER STATION RD
SIFIDHI                                                   5908
HICROSSSIF                                                6551
CORE_CLASS                                               LOCAL
GEO_start             [-85.52841872335158, 38.200360349057064]
GEO_end                [-85.52816882852979, 38.20037561255241]
Name: 7109, dtype: object

In [ ]:
def lem(xs):
    if pd.isna(xs):
        return 0
    else:
        return len(xs)

cc = cl_m.cl_LOW_int.dropna().apply(len)

def j(cls):
    ...
    


int_m.int_FST_cl.dropna().apply(j).all()

np.True_

In [ ]:
S = pd.Series


int_FST_cl = S(int_FST_cl)
int_SEC_cl = S(int_SEC_cl)

cl_LOW_int = S(cl_LOW_int)
cl_HI_int = S(cl_HI_int)
#S(cl_start_int).apply(lambda x:len(x) == 1).all() # False
#S(cl_end_int).apply(lambda x:len(x) == 1).all() # False

cl_HI_int[cl_HI_int.apply(len) >1]

5710837346                 [20860]
10005800273                [13504]
14300767569                [84838]
79566575913         [23911, 90022]
83861558290                 [4511]
                         ...
2698381254387508       [576, 9388]
2698419891660598           [19602]
2698428751996728            [6101]
2698437341931319            [5496]
2698447711168309            [8304]
Length: 18488, dtype: object

In [549]:

t = cl_LOW_int[cl_LOW_int.apply(len) == 2] # some cls have 2 intersection matches
# none have more than that
# more than one intersection matches on the cl
# this shouldn't be the case, logically. # clarify?

display(t) # 66 rows

67216       [7095824117768, 721281507401747]
25217       [20303981091221, 20355520698773]
27672       [22235165530518, 92591024806294]
598         [41795557880148, 41804147814740]
119721      [41957824364690, 42198342533266]
                         ...
174155    [844656661558820, 847057579734084]
162317    [844738298200420, 844739559880241]
162640    [844802722952754, 844811312887346]
167433    [845603724072841, 845612314007433]
163913    [847182152726083, 847186447693379]
Length: 66, dtype: object

In [ ]:


ixs = list()

for cl, ints in t.items():
    for i in ints:
        ixs.append((i, cl))

dm.loc[ixs]

In [ ]:

def test1(point):
    a, b = point
    if a != 0:
        return False
    if b != 0:
        return False
    return True 

(imm.intersection_point - imm.GEO_close).apply(test1)

In [ ]:
""" 
columns to add

centerlines -> 
    low_geo, hi_geo == mark start/end of geometry OR align geometry order? 
    low_int, hi_int = intersections

    find
    next_hi -> connection through intersection
    next_low -> connection though other intersection

intersections ->
    fst_roadway == ordered pair
    sec_roadway == ordered pair

    find 
    next intersections -> follow through each roadway component
"""

In [296]:
# -> create# NAME_df


# #int_d = intersections[['FST_ROADNAME', 'SEC_ROADNAME']]
# cl_d = centerlines[['ROADNAME', 'SIFIDLOW', 'SIFIDHI']]

# def get_int_names(int_id):
#     int_d.loc[int_id]

# def get_cl_names(cl_id):
#     rw, sl, sh = cl_d.loc[cl_id]
#     sl = sifid_to_roadname.get(sl)
#     sh = sifid_to_roadname.get(sh)
#     return pd.Series({
#         'ROADNAME': rw,
#         'LO_cross': sl,
#         'HI_cross': sh})

# NAME_df = iw.cl_id.apply(lambda id:centerlines.loc[id])
# #matchdfnumeric.index.to_frame()
# #4.9 sec

# NAME_df

matchdfnumeric[matchdfnumeric.apply(lambda x:((x >> 2) == 3))]

int_id           cl_id
323827650687044  18779     13
323879190294596  18779     13
40699115667584   13360     13
40922453966976   13360     13
319438198302071  22602     13
                           ..
847177857758787  174793    14
845631654655585  167436    14
845627359688289  167436    14
847130612987714  174475    14
847134907955010  174475    14
Length: 2521, dtype: int64

In [ ]:
centerlines

low_group = ['low_cross_ROADNAME', 'SIFIDLOW', 'LOCROSSSIF']
hi_group = ['hi_cross_ROADNAME', 'SIFIDHI', 'HICROSSSIF']

cols = ['low_cross_ROADNAME', 'SIFIDLOW', 'LOCROSSSIF', 'hi_cross_ROADNAME', 'SIFIDHI', 'HICROSSSIF']

mm= pd.concat((matchdfnumeric.apply(lambda x:x>>2), GEO_map.GEO_match_code), axis=1)

GEO_map[['intersection_point', 'GEO_match_code', 'GEO_close']].assign(mdf=matchdfnumeric)

matchdfnumeric.transform({"int_match": lambda x:x & 0b0011,
                          "LOW_match": lambda x:bool(x & low_mask),
                          "HI_match": lambda x:bool(x & hi_mask)})

                        int_match  LOW_match  HI_match
int_id          cl_id
589991067518338 10250           1       True     False
                28655           1       True     False
590506463593858 10250           1       True     False
                28655           1       True     False
409323268213029 26919           1       True     False
...                           ...        ...       ...
847134907955010 174788          2      False      True
847207302035270 175429          2      False      True
847212217628486 175434          2      False      True
847246577432390 175435          2      False      True
847250872399689 175437          2      False      True

[64111 rows x 3 columns]

In [314]:

#SIF_columns = ["SIFIDLOW", "SIFIDHI", "HICROSSSIF", "LOCROSSSIF"]
SIF_columns = ["SIFID", "SIFIDLOW", "SIFIDHI"]

SIF_data = centerlines[SIF_columns]

ee = iw.cl_id.apply(lambda cl_id: SIF_data.loc[cl_id])#.assign(int_match=matchdfnumeric & 0b0011)
SIF_data
ee

                         SIFID  SIFIDLOW  SIFIDHI
int_id           cl_id
5710837346       20353    4976      6856     6857
                 20860    6856      4976     8594
                 52803    4976      4674     6856
10005800273      7109     4976      5908     5908
                 9233     4976      5908    12697
...                        ...       ...      ...
2698443752596326 32774    5908       351     1117
                 105004   5908       351    15012
2698447711168309 4069     4716     12859     5897
                 8304    12859      4716     8594
                 30017    4716       586    12859

[64111 rows x 3 columns]

                         SIFID  SIFIDLOW  SIFIDHI
int_id           cl_id
5710837346       20353    4976      6856     6857
                 20860    6856      4976     8594
                 52803    4976      4674     6856
10005800273      7109     4976      5908     5908
                 9233     4976      5908    12697
...                        ...       ...      ...
2698443752596326 32774    5908       351     1117
                 105004   5908       351    15012
2698447711168309 4069     4716     12859     5897
                 8304    12859      4716     8594
                 30017    4716       586    12859

[64111 rows x 3 columns]

In [330]:

def f(sifid, mm):
    if mm:
        return sifid
    else:
        return pd.NA

ee['SIFIDLOW'] = ee.SIFIDLOW.combine(matchdfnumeric & low_mask, f)
ee['SIFIDHI'] = ee.SIFIDHI.combine(matchdfnumeric & hi_mask, f)

ee

                         SIFID SIFIDLOW SIFIDHI
int_id           cl_id
5710837346       20353    4976     6856    <NA>
                 20860    6856     4976    <NA>
                 52803    4976     <NA>    6856
10005800273      7109     4976     5908    5908
                 9233     4976     5908    <NA>
...                        ...      ...     ...
2698443752596326 32774    5908      351    <NA>
                 105004   5908      351    <NA>
2698447711168309 4069     4716    12859    <NA>
                 8304    12859     4716    <NA>
                 30017    4716     <NA>   12859

[64111 rows x 3 columns]

In [ ]:
centerlines_by_sifid = pd.concat(
    (centerlines_by_SIFID_SIFIDLOW, centerlines_by_SIFID_SIFIDHI),
    axis=1, keys=['SIFIDxLOW', 'SIFIDxHI'])

centerlines_by_sifid

def flip(index):
    return index[1], index[0]

def get(from_):
    def getter(index):
        try:
            match = from_.loc[index]
        except KeyError:
            match = pd.NA
        return match
    return getter 


cl_SSHI_index = centerlines_by_SIFID_SIFIDHI.index
rev = cl_SSHI_index.to_series().map(flip)
rev.transform({'low_match': get(centerlines_by_SIFID_SIFIDLOW),
               'hi_match': get(centerlines_by_SIFID_SIFIDHI)})

pd.concat((centerlines_by_SIFID_SIFIDLOW.index.to_series(),
           centerlines_by_SIFID_SIFIDHI.index.to_series()),
             axis=1, keys=['CLxSSLOW', 'CLxSSHI'])

def g(sifs):
    SIFID, LOW, HI = sifs
    hi_index = (HI, SIFID)
    low_index = (LOW, SIFID)



    try:
        hi_match = centerlines_by_SIFID_SIFIDHI.loc[hi_index]
    except KeyError:
        hi_match = None 

    try:
        match_sslow = centerlines_by_SIFID_SIFIDLOW[hi_index]
    except KeyError:
        if hi_match is None:
            hi_match = pd.NA
    else:
        if hi_match is None:
            hi_match = match_sslow
        else:
            hi_match = hi_match.union(match_sslow)
    return hi_match

                SIFIDLOW         SIFIDHI
OBJECTID
1           (1550, 8665)    (8594, 8665)
2           (2854, 5926)    (2470, 5926)
3            (6487, 473)    (10596, 473)
4          (13394, 2442)    (4702, 2442)
5           (4162, 4573)    (8594, 4573)
...                  ...             ...
180232     (8594, 15329)  (15331, 15329)
180233    (15610, 15611)  (15642, 15611)
180234    (15642, 15611)  (15610, 15611)
180235    (15611, 15610)  (15611, 15610)
180236    (15611, 15642)   (8594, 15642)

[34215 rows x 2 columns]

In [ ]:
def get(index):
    try:
        hi_match = centerlines_by_SIFID_SIFIDHI.loc[index]
    except KeyError:
        hi_match = None 

    try:
        low_match = centerlines_by_SIFID_SIFIDLOW.loc[index]
    except KeyError:
        if hi_match is None:
            return pd.NA 
        else:
            return hi_match.to_list()
    else:
        if hi_match is None:
            return low_match.to_list()
        else:
            return hi_match.union(low_match).to_list()

def h(s):
    return s.combine(centerlines.SIFID, lambda x, y:(x, y)).apply(get)


centerlines[['SIFIDLOW', 'SIFIDHI']].apply(h)

                                  SIFIDLOW                           SIFIDHI
OBJECTID
1                                   [6013]                              <NA>
2                            [3753, 23064]                    [28081, 32011]
3                    [20485, 24494, 27237]                            [3057]
4                           [84286, 84288]                           [84285]
5                                  [18357]                              <NA>
...                                    ...                               ...
180232                                <NA>                          [145324]
180233                            [180235]                          [180236]
180234                            [180236]                          [180235]
180235    [176706, 176711, 180233, 180234]  [176706, 176711, 180233, 180234]
180236                    [180233, 180234]                              <NA>

[34215 rows x 2 columns]

In [410]:
centerlines.index.to_list()

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 20,
 21,
 22,
 23,
 25,
 30,
 31,
 32,
 33,
 35,
 37,
 38,
 39,
 40,
 46,
 47,
 48,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 62,
 63,
 64,
 68,
 71,
 72,
 73,
 75,
 76,
 77,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 130,
 131,
 132,
 133,
 135,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 162,
 167,
 168,
 169,
 170,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 209,
 218,
 219,
 220,
 221,
 224,
 225,
 226,
 227,
 228,
 229,
 231,
 232,
 233,
 234,
 236,
 237,
 239,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 264,
 265,
 267,
 268,
 270,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 341,
 342,
 343,
 344,
 345,
 349,
 350,
 351,
 353,
 354,
 356,
 357,
 358,
 359,
 360,
 361,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 384,
 385,
 386,
 387,
 389,
 390,
 391,
 392,
 394,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 408,
 409,
 411,
 412,
 413,
 414,
 416,
 417,
 420,
 421,
 422,
 423,
 424,
 426,
 427,
 428,
 429,
 430,
 431,
 433,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 467,
 468,
 469,
 470,
 471,
 472,
 474,
 475,
 476,
 477,
 478,
 481,
 482,
 483,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 499,
 500,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 518,
 520,
 522,
 523,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 548,
 549,
 550,
 552,
 554,
 555,
 556,
 558,
 559,
 560,
 561,
 562,
 563,
 565,
 566,
 567,
 568,
 569,
 571,
 572,
 573,
 574,
 576,
 577,
 578,
 579,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 601,
 602,
 603,
 604,
 606,
 607,
 608,
 609,
 611,
 612,
 613,
 614,
 615,
 616,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 653,
 655,
 656,
 657,
 658,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 671,
 672,
 674,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 707,
 708,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 947,
 948,
 949,
 950,
 951,
 952,
 954,
 955,
 956,
 957,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 1000,
 1002,
 1003,
 1004,
 1006,
 1007,
 1008,
 1009,
 1010,
 1011,
 1012,
 1013,
 1014,
 1015,
 1016,
 1017,
 1018,
 1019,
 1020,
 1021,
 1022,
 1023,
 1024,
 1026,
 1027,
 1028,
 1029,
 1030,
 1031,
 1032,
 1033,
 1034,
 1035,
 1036,
 1038,
 1039,
 1040,
 1041,
 1042,
 1043,
 1044,
 1045,
 1046,
 1047,
 1048,
 1050,
 1051,
 1052,
 1053,
 1054,
 1055,
 1056,
 1057,
 1058,
 1059,
 1060,
 1061,
 1063,
 1064,
 1065,
 1066,
 1067,
 1068,
 1070,
 1071,
 1072,
 1073,
 1074,
 1075,
 1076,
 1077,
 1078,
 1079,
 1080,
 1081,
 1082,
 1083,
 1084,
 1085,
 1086,
 1087,
 1090,
 1091,
 1092,
 1093,
 1094,
 1095,
 1096,
 1097,
 1098,
 1099,
 1100,
 1101,
 1102,
 1103,
 1105,
 1106,
 1108,
 1109,
 1110,
 1111,
 1112,
 1113,
 1114,
 1115,
 1116,
 1117,
 1118,
 1119,
 1120,
 1121,
 1122,
 1123,
 1125,
 1126,
 1127,
 1128,
 1129,
 1130,
 1131,
 1132,
 1133,
 1134,
 1135,
 1136,
 1137,
 1138,
 1139,
 1140,
 1141,
 1142,
 1143,
 1144,
 1145,
 1146,
 1147,
 1148,
 1149,
 1150,
 1151,
 1152,
 1153,
 1154,
 1155,
 1156,
 1157,
 1158,
 1159,
 1160,
 1161,
 1162,
 1163,
 1164,
 1165,
 1167,
 1168,
 1169,
 1171,
 ...]

In [ ]:
ee['intersection_point'] = GEO_map.intersection_point
ee["GEO_close"] = GEO_map.GEO_close

ee

In [271]:
(ee[ee.SIFIDHI.notna() & ee.SIFIDLOW.notna()] == ee[ee.SIFIDLOW == ee.SIFIDHI]).all().all()
# -> True. This means that in all cases where both SIFIDHI and LOW match, the SIFIDs are equal
# Road loops and such as, I guess.

CLG = centerlines.groupby('SIFID')[['GEO_start', 'GEO_end']].apply(lambda x:x)
CLG

                                               GEO_start  \
SIFID OBJECTID
1     2398       [-85.84448159320799, 38.20137533915249]
      3506       [-85.70968827136649, 38.12813112397158]
      6313       [-85.89531203661909, 38.14401468934693]
      8356       [-85.84798778460241, 38.17734130223805]
      8683      [-85.84280313341836, 38.201214934112464]
...                                                  ...
15638 179908      [-85.60731013837355, 38.1857501107605]
15639 179911     [-85.85171970535131, 38.20031227634193]
15640 180227      [-85.5778646682938, 38.31733391246771]
15641 180229    [-85.54618848348093, 38.084581472122935]
15642 180236    [-85.45174798320075, 38.270920967505994]

                                                 GEO_end
SIFID OBJECTID
1     2398       [-85.84498831396351, 38.20004206388769]
      3506       [-85.70951084235313, 38.12868880056472]
      6313       [-85.89203421085367, 38.14392222397775]
      8356       [-85.84881288521419, 38.17714727759056]
      8683       [-85.84448159320799, 38.20137533915249]
...                                                  ...
15638 179908    [-85.60609105189127, 38.185491770938995]
15639 179911     [-85.85181439690278, 38.20435070734935]
15640 180227     [-85.57028952405062, 38.31993204916915]
15641 180229     [-85.54604439062057, 38.08411166310706]
15642 180236     [-85.45058838480479, 38.27180114613091]

[34215 rows x 2 columns]

In [277]:

dist = central_angle

def cg(s):
    LOW = s.SIFIDLOW
    HI = s.SIFIDHI
    if pd.isna(LOW):
        sifid = HI
    elif pd.isna(HI):
        sifid = LOW
    else:
        assert HI == LOW
        sifid = LOW # arbitrary
    int_match = s.GEO_close
    try:
        cl_geos = CLG.loc[sifid]#.map(lambda p:dist(int_match, p))
    except KeyError:
        return
    else:
        return type(cl_geos)


#ee.apply(cg, axis=1)

ee

                        SIFIDLOW SIFIDHI  \
int_id           cl_id
5710837346       20353      6856    <NA>
                 20860      4976    <NA>
                 52803      <NA>    6856
10005800273      7109       5908    5908
                 9233       5908    <NA>
...                          ...     ...
2698443752596326 32774       351    <NA>
                 105004      351    <NA>
2698447711168309 4069      12859    <NA>
                 8304       4716    <NA>
                 30017      <NA>   12859

                                                       GEO_close
int_id           cl_id
5710837346       20353   [-85.51044384084946, 38.20588660809318]
                 20860   [-85.51044384084946, 38.20588660809318]
                 52803   [-85.51044384084946, 38.20588660809318]
10005800273      7109    [-85.52816882852979, 38.20037561255241]
                 9233    [-85.52816882852979, 38.20037561255241]
...                                                          ...
2698443752596326 32774     [-85.5284541859341, 38.2171605272513]
                 105004  [-85.52706694300736, 38.22235647012922]
2698447711168309 4069    [-85.68299954058695, 38.13164510965587]
                 8304    [-85.68299954058695, 38.13164510965587]
                 30017   [-85.68299954058695, 38.13164510965587]

[64111 rows x 3 columns]

In [223]:
c = centerlines.groupby('SIFID')[['GEO_start', 'GEO_end']].apply(lambda x:x)
#centerlines[["SIFID", 'GEO_start', 'GEO_end']].groupby("SIFID").apply(lambda x:x)
c

                                               GEO_start  \
SIFID OBJECTID
1     2398       [-85.84448159320799, 38.20137533915249]
      3506       [-85.70968827136649, 38.12813112397158]
      6313       [-85.89531203661909, 38.14401468934693]
      8356       [-85.84798778460241, 38.17734130223805]
      8683      [-85.84280313341836, 38.201214934112464]
...                                                  ...
15638 179908      [-85.60731013837355, 38.1857501107605]
15639 179911     [-85.85171970535131, 38.20031227634193]
15640 180227      [-85.5778646682938, 38.31733391246771]
15641 180229    [-85.54618848348093, 38.084581472122935]
15642 180236    [-85.45174798320075, 38.270920967505994]

                                                 GEO_end
SIFID OBJECTID
1     2398       [-85.84498831396351, 38.20004206388769]
      3506       [-85.70951084235313, 38.12868880056472]
      6313       [-85.89203421085367, 38.14392222397775]
      8356       [-85.84881288521419, 38.17714727759056]
      8683       [-85.84448159320799, 38.20137533915249]
...                                                  ...
15638 179908    [-85.60609105189127, 38.185491770938995]
15639 179911     [-85.85181439690278, 38.20435070734935]
15640 180227     [-85.57028952405062, 38.31993204916915]
15641 180229     [-85.54604439062057, 38.08411166310706]
15642 180236     [-85.45058838480479, 38.27180114613091]

[34215 rows x 2 columns]

In [ ]:
def f(sifid, mm):
    if mm:
        return sifid
    else:
        return pd.NA
    
def g(sifid):
    try:
        geos = c.loc[sifid]
    except KeyError:
        return pd.NA
    else:
        ...


sl = ee.SIFIDLOW.combine(matchdfnumeric & low_mask, f)#.apply(g)

int_id            cl_id
5710837346        20353      6856
                  20860      4976
                  52803      <NA>
10005800273       7109       5908
                  9233       5908
                            ...
2698443752596326  32774       351
                  105004      351
2698447711168309  4069      12859
                  8304       4716
                  30017      <NA>
Length: 64111, dtype: object

In [293]:
sl.iloc[1]

,GEO_start,GEO_end
OBJECTID,,
7109,"[-85.52841872335158, 38.200360349057064]","[-85.52816882852979, 38.20037561255241]"
9233,"[-85.52816882852979, 38.20037561255241]","[-85.52154597701633, 38.20245302533696]"
14678,"[-85.50187141303726, 38.206105324500015]","[-85.49945278036108, 38.20743661819182]"
20166,"[-85.53836064009367, 38.200600417756]","[-85.531149709042, 38.2005045068783]"
20353,"[-85.51044384084946, 38.20588660809318]","[-85.50187141303726, 38.206105324500015]"
31468,"[-85.531149709042, 38.2005045068783]","[-85.52841872335158, 38.200360349057064]"
52803,"[-85.51425148406123, 38.20488285764657]","[-85.51044384084946, 38.20588660809318]"
52804,"[-85.52154597701633, 38.20245302533696]","[-85.51425148406123, 38.20488285764657]"
90023,"[-85.49041133329159, 38.204811157321686]","[-85.48494532437061, 38.2079572283897]"

In [ ]:
# -> make  SIFdf

# cl_dat = centerlines[['SIFID', 'SIFIDLOW', 'SIFIDHI']]

# def gc(ci):
#     return cl_dat.loc[ci]

# sifm = matchdfnumeric.index.to_frame().cl_id.apply(gc)
# sifm

# any(matchdfnumeric == 0b0011) # none
# any(matchdfnumeric == 0b0000) # false # none of these either

# data = {"int_match": matchdfnumeric & 0b0011,
#         "cl_sifid": sifm.SIFID,
#         "low_match": sifm.SIFIDLOW[(matchdfnumeric & low_mask) != 0],
#         "hi_match": sifm.SIFIDHI[(matchdfnumeric & hi_mask) != 0]}


# #dd = pd.concat((int_ser, sifm.SIFID, low_ser, hi_ser), axis=1, keys=['int_match', 'cl_sifid', 'low_match', 'hi_match']).convert_dtypes()

# SIFdf = pd.DataFrame.from_dict(data).convert_dtypes()
# SIFdf

In [61]:
# make multi index coumns helper

# def ix(columns, *labels):
#     out = list()
#     columns = iter(columns)
#     for label, column in zip(labels, columns):
#         out.append((label, column))
#     else:
#         # default = last value of label
#         for column in columns:
#             out.append((label, column))
#     return pd.MultiIndex.from_tuples(out)

# ix(NAME_df.columns, 'hello')

# NAME_df.columns=ix(NAME_df.columns, 'hello')
# NAME_df

In [71]:

from common.county_geometry import *

iw = matchdfnumeric.index.to_frame()

intersections_GEOMETRY = intersections.GEOMETRY
intersections_state_grid_GEO = intersections.state_grid_GEO

centerlines_GEOLOW = centerlines.GEOLOW
centerlines_GEOHI = centerlines.GEOHI

In [ ]:
hav = haversine_distance_ft

intersection_coordinates = iw.int_id.apply(lambda int_id:intersections_GEOMETRY.at[int_id])
intersection_state_grid_conv = iw.int_id.apply(lambda int_id:intersections_state_grid_GEO.at[int_id])

# TODO ...

In [ ]:
ids = mdf.index.to_frame(name=['intersection_ids',"centerline_ids"])

int_long_lat = ids.intersection_ids.apply(lambda intid: intersections_GEO.at[intid])
int_state_grid = ids.intersection_ids.apply(lambda intid: intersections_state_grid.at[intid])

hi_points = ids.centerline_ids.apply(lambda cl_id: centerlines_GEOHI.at[cl_id])
low_points = ids.centerline_ids.apply(lambda cl_id: centerlines_GEOLOW.at[cl_id])

int_long_lat.combine(hi_points, central_angle)
int_state_grid.combine(hi_points, central_angle)

int_long_lat.combine(hi_points, central_angle)
int_state_grid.combine(hi_points, central_angle)

int_id           cl_id
589991067518338  10250     2.542220e-05
                 28655     4.687739e-05
590506463593858  10250     2.816241e-05
                 28655     4.542790e-05
409323268213029  26919     3.775007e-05
                               ...
847134907955010  174788    1.436194e-07
847207302035270  175429    1.431915e-07
847212217628486  175434    1.431968e-07
847246577432390  175435    1.431938e-07
847250872399689  175437    1.431925e-07
Length: 64111, dtype: float64

In [ ]:

hi_dist = (int_points - hi_points).apply(euclidean_distance)

low_dist = (int_points - low_points).apply(euclidean_distance)

In [ ]:

def encode_closer_point(difference):
    if difference < 0: # hi_dist < low_dist
        return 'hi'
    elif difference > 0: # hi_dist > low_dist
        return 'low'
    elif difference == 0: # hi_dist == low_dist
        return 'both'
    else:
        return pd.NA

dist_diff = (hi_dist - low_dist)
geo_end = dist_diff.apply(encode_closer_point)


geo_end.hasnans # -> False.
# checking something;
(geo_end[geo_end != 'low'] == geo_end[(geo_end == 'hi') | (geo_end == 'both')]).all() # -> True

In [ ]:
close_points = pd.concat((
    hi_points[geo_end != 'low'], 
    low_points[geo_end == 'low']))

close_distance = pd.concat((
    hi_dist[geo_end != 'low'],
    low_dist[geo_end == 'low']))

far_points = pd.concat((
    hi_points[geo_end == 'low'],
    low_points[geo_end == 'hi']))

far_distance = pd.concat((
    hi_dist[geo_end == 'low'],
    low_dist[geo_end == 'hi']))


working = pd.DataFrame(pd.Series(int_points, name='int_point'))
working['geo_end'] = geo_end
working['close_point'] = close_points
working['far_point'] = far_points
working['close_dist'] = close_distance
working['far_dist'] = far_distance
working['dist_diff'] = dist_diff.abs()

working.index.set_names(('int_id', 'cl_id'), inplace=True)
geo_data = working

geo_data

                                                       int_point geo_end  \
int_id          cl_id
589991067518338 10250    [-85.89203421085367, 38.14392222397775]     low
                28655    [-85.89203421085367, 38.14392222397775]     low
590506463593858 10250   [-85.89205718950319, 38.143226353738676]     low
                28655   [-85.89205718950319, 38.143226353738676]     low
409323268213029 26919   [-85.83013514539758, 38.213609743764856]     low
...                                                          ...     ...
847134907955010 174788   [-85.49669357922623, 38.29070651405069]      hi
847207302035270 175429   [-85.55862850424626, 38.12636761108555]      hi
847212217628486 175434   [-85.55884906334812, 38.12802620488927]      hi
847246577432390 175435    [-85.55854188749127, 38.1271646809743]      hi
847250872399689 175437   [-85.55753279215419, 38.12710321087191]      hi

                                                     close_point  \
int_id          cl_id
589991067518338 10250    [-85.89203421085367, 38.14392222397775]
                28655   [-85.89205718950319, 38.143226353738676]
590506463593858 10250    [-85.89203421085367, 38.14392222397775]
                28655   [-85.89205718950319, 38.143226353738676]
409323268213029 26919   [-85.83013514539758, 38.213609743764856]
...                                                          ...
847134907955010 174788   [-85.49669357922623, 38.29070651405069]
847207302035270 175429   [-85.55862850424626, 38.12636761108555]
847212217628486 175434   [-85.55884906334812, 38.12802620488927]
847246577432390 175435    [-85.55854188749127, 38.1271646809743]
847250872399689 175437   [-85.55753279215419, 38.12710321087191]

                                                       far_point  close_dist  \
int_id          cl_id
589991067518338 10250    [-85.89017790736897, 38.14387530855226]    0.000000
                28655    [-85.89535933539815, 38.14331916493513]    0.000696
590506463593858 10250    [-85.89017790736897, 38.14387530855226]    0.000696
                28655    [-85.89535933539815, 38.14331916493513]    0.000000
409323268213029 26919    [-85.83201078511965, 38.21202291188871]    0.000000
...                                                          ...         ...
847134907955010 174788  [-85.49758979847759, 38.290228130801005]    0.000000
847207302035270 175429    [-85.55854188749127, 38.1271646809743]    0.000000
847212217628486 175434   [-85.55899003824544, 38.12895721169443]    0.000000
847246577432390 175435   [-85.55884906334812, 38.12802620488927]    0.000000
847250872399689 175437  [-85.55664071193948, 38.127332178618765]    0.000000

                        far_dist  dist_diff
int_id          cl_id
589991067518338 10250   0.001857   0.001857
                28655   0.003379   0.002683
590506463593858 10250   0.001988   0.001292
                28655   0.003303   0.003303
409323268213029 26919   0.002457   0.002457
...                          ...        ...
847134907955010 174788  0.001016   0.001016
847207302035270 175429  0.000802   0.000802
847212217628486 175434  0.000942   0.000942
847246577432390 175435  0.000915   0.000915
847250872399689 175437  0.000921   0.000921

[64111 rows x 7 columns]

In [ ]:

def get_intersection_names(intersection_id):
    in1 = intersections.at[intersection_id, 'FST_ROADNAME']
    in2 = intersections.at[intersection_id, 'SEC_ROADNAME']
    return in1, in2

names = centerlines.groupby("SIFID").ROADNAME.apply(set)#.apply(lambda x:len(x)==1).all() # true
sifid_names = names.apply(lambda x:x.pop())

def roadname_by_sifid(sifid):
    return sifid_names[sifid]

def get_names(int_id, cd_id):
    inames = get_intersection_names(intersection_id)
    cnames = roadname_by_sifid(cl_id)
    return {'intersection':inames, 'centerline':cnames}

In [ ]:
intids = working.index.to_frame().int_id
intids

int_id           cl_id
589991067518338  10250     589991067518338
                 28655     589991067518338
590506463593858  10250     590506463593858
                 28655     590506463593858
409323268213029  26919     409323268213029
                                ...
847134907955010  174788    847134907955010
847207302035270  175429    847207302035270
847212217628486  175434    847212217628486
847246577432390  175435    847246577432390
847250872399689  175437    847250872399689
Name: int_id, Length: 64111, dtype: int64

In [ ]:
working = geo_data[geo_data.close_dist >= .1]
working

iw = working.index.to_frame()
iw

def get_int_data(int_id):
    return intersections.loc[int_id][["FST_ROADNAME", "FST_SIFID", "SEC_ROADNAME", "SEC_SIFID"]]

def get_cl_data(cl_id):
    return centerlines.loc[cl_id][['ROADNAME', 'SIFID', 'CORE_CLASS']]

data = pd.concat((
iw.cl_id.transform({"centerline_data":get_cl_data}) ,
iw.int_id.transform({'intersection_data':get_int_data})
), axis=1)

data


def mmft(label, df):
    if isinstance(label, str):
        return pd.MultiIndex.from_tuples((label, col) for col in df.columns)
    else:
        return pd.MultiIndex.from_tuples((L, C) for L, C in zip(label, df.columns))
    


def dd(geodf):
    #ex = geodf[['int_point
    #out = list()
    iw = geodf.index.to_frame()
    cl_geo = geodf[['int_point', 'close_point', 'close_dist', 'geo_end']]
    cl_geo.columns = mmft(('int_geo', 'cl_geo', 'cl_geo', 'cl_geo'), cl_geo)

    cl_data = iw.cl_id.apply(get_cl_data)
    cl_data.columns = mmft('cl_data', cl_data)
    # TODO get hi/low sifid / roadname

    int_data = iw.int_id.apply(get_int_data)
    int_data.columns = mmft("int_data", int_data)

    out = [int_data, cl_geo, cl_data]
    return pd.concat(out, axis=1)
    
    int_data = iw.int_id.apply(get_int_data)
    int_info = pd.concat((int_data, geodf.int_point), axis=1)
    int_info.columns = pd.MultiIndex.from_tuples(('int_data', col) for col in int_info.columns)
    
    return pd.concat((int_info, cl_info), axis=1).sort_index()

#    pd.MultiIndex.from_tuples([('cl_data', col) for col in c.columns])
#c.columns = pd.MultiIndex.from_tuples([('cl_data', col) for col in c.columns])
#c

see = dd(working)

#see[~see.int_data.FST_ROADNAME.str.contains('841')]

see

                              int_data                                    \
                          FST_ROADNAME FST_SIFID  SEC_ROADNAME SEC_SIFID
int_id           cl_id
590467808889140  29463  NO STREET NAME         1   CANE RUN RD       906
38521867941168   6218     COLUMBIA AVE      1245  KENTUCKY AVE      3356
589634891494704  21710    COLUMBIA AVE      1245  KENTUCKY AVE      3356
706470196341142  903       KY-841 RAMP     14021        KY 841     14195
                 18413     KY-841 RAMP     14021        KY 841     14195
...                                ...       ...           ...       ...
654251992213784  6590           KY 841     14195   KY-841 RAMP     14021
                 7706           KY 841     14195   KY-841 RAMP     14021
2696491761592600 6590           KY 841     14195   KY-841 RAMP     14021
                 7706           KY 841     14195   KY-841 RAMP     14021
                 11399          KY 841     14195   KY-841 RAMP     14021

                                                         int_geo  \
                                                       int_point
int_id           cl_id
590467808889140  29463   [-85.89679114783614, 38.14336979587274]
38521867941168   6218    [-85.61845036330493, 38.26000799417955]
589634891494704  21710  [-85.84807001201702, 38.150808026597076]
706470196341142  903    [-85.70246758147974, 38.115233764331414]
                 18413  [-85.70246758147974, 38.115233764331414]
...                                                          ...
654251992213784  6590   [-85.87003129510553, 38.091380651748494]
                 7706   [-85.87003129510553, 38.091380651748494]
2696491761592600 6590    [-85.87691759786703, 38.09294723096209]
                 7706    [-85.87691759786703, 38.09294723096209]
                 11399   [-85.87691759786703, 38.09294723096209]

                                                          cl_geo             \
                                                     close_point close_dist
int_id           cl_id
590467808889140  29463   [-85.8175947343509, 38.218723744753156]   0.109317
38521867941168   6218   [-85.84807001201702, 38.150808026597076]   0.254263
589634891494704  21710   [-85.61845036330493, 38.26000799417955]   0.254263
706470196341142  903     [-85.8189716474408, 38.103260224945146]   0.117118
                 18413  [-85.87003129510553, 38.091380651748494]   0.169253
...                                                          ...        ...
654251992213784  6590   [-85.75479831645234, 38.117411563113556]   0.118137
                 7706    [-85.74797696339039, 38.11669772522921]   0.124652
2696491761592600 6590   [-85.75479831645234, 38.117411563113556]   0.124546
                 7706    [-85.74797696339039, 38.11669772522921]   0.131110
                 11399   [-85.77549954907987, 38.11946730096766]   0.104828

                                     cl_data
                       geo_end      ROADNAME  SIFID      CORE_CLASS
int_id           cl_id
590467808889140  29463      hi       NO NAME      1           LOCAL
38521867941168   6218      low  COLUMBIA AVE   1245           LOCAL
589634891494704  21710     low  COLUMBIA AVE   1245           LOCAL
706470196341142  903       low   KY-841 RAMP  14021  MAJOR ARTERIAL
                 18413     low   KY-841 RAMP  14021  MAJOR ARTERIAL
...                        ...           ...    ...             ...
654251992213784  6590       hi   KY-841 RAMP  14021  MAJOR ARTERIAL
                 7706      low   KY-841 RAMP  14021  MAJOR ARTERIAL
2696491761592600 6590       hi   KY-841 RAMP  14021  MAJOR ARTERIAL
                 7706      low   KY-841 RAMP  14021  MAJOR ARTERIAL
                 11399     low   KY-841 RAMP  14021  MAJOR ARTERIAL

[89 rows x 11 columns]

In [ ]:
s= working.index.get_level_values('cl_id')

centerlines.loc[s].ROADNAME.value_counts()

ROADNAME
KY-841 RAMP     39
KY 841          36
COLUMBIA AVE     4
CANE RUN RD      4
KENTUCKY AVE     4
NO NAME          2
Name: count, dtype: int64

In [ ]:
mi = intersections.loc[working.index.get_level_values('int_id')]

# KY 841 / I 265 / Watterson Expwy and ramps
mi[(mi.FST_ROADNAME.str.contains("841") & mi.SEC_ROADNAME.str.contains("841"))]

# other weird matches
wm = mi[~(mi.FST_ROADNAME.str.contains("841") & mi.SEC_ROADNAME.str.contains("841"))]

working.loc[wm.index, :]
wm
mi

,FST_ROADNAME,SEC_ROADNAME,SIFCODE1,SIFCODE2,FST_SIFID,SEC_SIFID,GEOMETRY,state_grid_GEO
int_id,,,,,,,,
590467808889140,NO STREET NAME,CANE RUN RD,0000,0934,1,906,"[-85.89679114783614, 38.14336979587274]","[-85.89673981756692, 38.143358031236794]"
38521867941168,COLUMBIA AVE,KENTUCKY AVE,1241,3530,1245,3356,"[-85.61845036330493, 38.26000799417955]","[-85.61844551689906, 38.260000695318304]"
589634891494704,COLUMBIA AVE,KENTUCKY AVE,1241,3530,1245,3356,"[-85.84807001201702, 38.150808026597076]","[-85.84805632815548, 38.15080051575182]"
706470196341142,KY-841 RAMP,KY 841,E918,E996,14021,14195,"[-85.70246758147974, 38.115233764331414]","[-85.70246272131506, 38.11522649717792]"
706470196341142,KY-841 RAMP,KY 841,E918,E996,14021,14195,"[-85.70246758147974, 38.115233764331414]","[-85.70246272131506, 38.11522649717792]"
...,...,...,...,...,...,...,...,...
654251992213784,KY 841,KY-841 RAMP,E996,E918,14195,14021,"[-85.87003129510553, 38.091380651748494]","[-85.87002638784153, 38.09137339695274]"
654251992213784,KY 841,KY-841 RAMP,E996,E918,14195,14021,"[-85.87003129510553, 38.091380651748494]","[-85.87002638784153, 38.09137339695274]"
2696491761592600,KY 841,KY-841 RAMP,E996,E918,14195,14021,"[-85.87691759786703, 38.09294723096209]","[-85.87691268847966, 38.09293997618528]"
2696491761592600,KY 841,KY-841 RAMP,E996,E918,14195,14021,"[-85.87691759786703, 38.09294723096209]","[-85.87691268847966, 38.09293997618528]"
2696491761592600,KY 841,KY-841 RAMP,E996,E918,14195,14021,"[-85.87691759786703, 38.09294723096209]","[-85.87691268847966, 38.09293997618528]"

In [ ]:


    

#display(
#info[['int_point', 'close_point', 'close_dist', 'geo_end', ]])



wmm = data[~data.intersection_data.FST_ROADNAME.str.contains('841')]

display(
working.loc[wmm.index][['int_point', 'close_point', 'close_dist', 'geo_end', ]],
wmm)

,,int_point,close_point,close_dist,geo_end
int_id,cl_id,,,,
590467808889140,29463,"[-85.89679114783614, 38.14336979587274]","[-85.8175947343509, 38.218723744753156]",0.109317,hi
38521867941168,6218,"[-85.61845036330493, 38.26000799417955]","[-85.84807001201702, 38.150808026597076]",0.254263,low
589634891494704,21710,"[-85.84807001201702, 38.150808026597076]","[-85.61845036330493, 38.26000799417955]",0.254263,low
352187318274356,31519,"[-85.81503148910512, 38.21843165728323]","[-85.89535933539815, 38.14331916493513]",0.109975,low
38521867941168,10508,"[-85.61845036330493, 38.26000799417955]","[-85.84620751970706, 38.15069748385449]",0.252630,low
589634891494704,11695,"[-85.84807001201702, 38.150808026597076]","[-85.61953362264914, 38.25940896160892]",0.253028,low
352187318274356,11220,"[-85.81503148910512, 38.21843165728323]","[-85.89679114783614, 38.14336979587274]",0.110991,low
590467808889140,26722,"[-85.89679114783614, 38.14336979587274]","[-85.81797210922643, 38.21544151873681]",0.106803,hi
38521867941168,2474,"[-85.61845036330493, 38.26000799417955]","[-85.84807001201702, 38.150808026597076]",0.254263,low
589634891494704,29055,"[-85.84807001201702, 38.150808026597076]","[-85.62012324704497, 38.25992290121035]",0.252717,hi
352187318274356,32589,"[-85.81503148910512, 38.21843165728323]","[-85.8965300725521, 38.145020499957575]",0.109687,low
590467808889140,5361,"[-85.89679114783614, 38.14336979587274]","[-85.81503148910512, 38.21843165728323]",0.110991,hi
38521867941168,10465,"[-85.61845036330493, 38.26000799417955]","[-85.84789878936502, 38.1526162694713]",0.253337,low
589634891494704,5523,"[-85.84807001201702, 38.150808026597076]","[-85.61845036330493, 38.26000799417955]",0.254263,hi

                      centerline_data                           \
                             ROADNAME SIFID         CORE_CLASS
int_id          cl_id
590467808889140 29463         NO NAME     1              LOCAL
38521867941168  6218     COLUMBIA AVE  1245              LOCAL
589634891494704 21710    COLUMBIA AVE  1245              LOCAL
352187318274356 31519         NO NAME     1              LOCAL
38521867941168  10508    COLUMBIA AVE  1245              LOCAL
589634891494704 11695    COLUMBIA AVE  1245              LOCAL
352187318274356 11220     CANE RUN RD   906  PRIMARY COLLECTOR
590467808889140 26722     CANE RUN RD   906     MINOR ARTERIAL
38521867941168  2474     KENTUCKY AVE  3356              LOCAL
589634891494704 29055    KENTUCKY AVE  3356              LOCAL
352187318274356 32589     CANE RUN RD   906  PRIMARY COLLECTOR
590467808889140 5361      CANE RUN RD   906     MINOR ARTERIAL
38521867941168  10465    KENTUCKY AVE  3356              LOCAL
589634891494704 5523     KENTUCKY AVE  3356              LOCAL

                      intersection_data
                           FST_ROADNAME FST_SIFID  SEC_ROADNAME SEC_SIFID
int_id          cl_id
590467808889140 29463    NO STREET NAME         1   CANE RUN RD       906
38521867941168  6218       COLUMBIA AVE      1245  KENTUCKY AVE      3356
589634891494704 21710      COLUMBIA AVE      1245  KENTUCKY AVE      3356
352187318274356 31519    NO STREET NAME         1   CANE RUN RD       906
38521867941168  10508      COLUMBIA AVE      1245  KENTUCKY AVE      3356
589634891494704 11695      COLUMBIA AVE      1245  KENTUCKY AVE      3356
352187318274356 11220    NO STREET NAME         1   CANE RUN RD       906
590467808889140 26722    NO STREET NAME         1   CANE RUN RD       906
38521867941168  2474       COLUMBIA AVE      1245  KENTUCKY AVE      3356
589634891494704 29055      COLUMBIA AVE      1245  KENTUCKY AVE      3356
352187318274356 32589    NO STREET NAME         1   CANE RUN RD       906
590467808889140 5361     NO STREET NAME         1   CANE RUN RD       906
38521867941168  10465      COLUMBIA AVE      1245  KENTUCKY AVE      3356
589634891494704 5523       COLUMBIA AVE      1245  KENTUCKY AVE      3356

In [ ]:
centerlines[centerlines.ROADNAME.str.contains("KENTUCKY AVE")]
centerlines[(centerlines.SIFID == 3356) & ((centerlines.SIFIDLOW == 1245) | (centerlines.SIFIDHI == 1245))]

#wm = wm.groupby(by="FST_SIFID").apply(lambda x:x)

,ROADNAME,SIFID,SIFCODE,low_cross_ROADNAME,SIFIDLOW,LOCROSSSIF,hi_cross_ROADNAME,SIFIDHI,HICROSSSIF,CORE_CLASS,GEOLOW,GEOHI
OBJECTID,,,,,,,,,,,,
2474,KENTUCKY AVE,3356,3530,COLUMBIA AVE,1245,1241,PRINCETON AVE,4725,5155,LOCAL,"[-85.84807001201702, 38.150808026597076]","[-85.84822119095742, 38.149025980797525]"
5523,KENTUCKY AVE,3356,3530,FLORIDA AVE,2249,2251,COLUMBIA AVE,1245,1241,LOCAL,"[-85.6148949649379, 38.25574321445772]","[-85.61845036330493, 38.26000799417955]"
10465,KENTUCKY AVE,3356,3530,DEAD END,8594,9811,COLUMBIA AVE,1245,1241,LOCAL,"[-85.84789878936502, 38.1526162694713]","[-85.84807001201702, 38.150808026597076]"
29055,KENTUCKY AVE,3356,3530,COLUMBIA AVE,1245,1241,DEAD END,8594,9811,LOCAL,"[-85.61845036330493, 38.26000799417955]","[-85.62012324704497, 38.25992290121035]"

In [ ]:
def convert_geo(geo):
    if len(geo) == 2:
        long, lat = geo
        return (lat, long)
    else:
        return [(lat, long) for long, lat in geo]

def swap_point(point):
    x, y = point
    return (y, x)

swap_point((1,2))

(2, 1)

In [ ]:
# working = mdf.index.to_series()


# def get_geo(row):
#     int_id, cl_id = row
#     out = dict() # tried Series. Took too long. Dict is very fast ( .4 sec)
#     out['intx_geo'] = intx_geo = intersections_GEO.at[int_id]
#     out['cl_geo_low'] = centerlines_GEOLOW.at[cl_id]
#     out['cl_geo_hi'] = centerlines_GEOHI.at[cl_id]
#     return out

# working = pd.DataFrame(mdf.index.to_series().apply(get_geo).to_list(), index=mdf.index)
# hi_dist = (working.intx_geo - working.cl_geo_hi).apply(euclidean_distance)
# low_dist = (working.intx_geo - working.cl_geo_low).apply(euclidean_distance)

# def find_close_closer_point(x):
#     if x < 0:
#         return 'hi'
#     elif x > 0:
#         return 'low'
#     elif x == 0:
#         return 'both'
#     else:
#         return pd.NA

# working['geo_end'] = (hi_dist - low_dist).apply(find_close_closer_point)
# working

# def gp(row):
#     code = row.geo_end
#     if code == 'low':
#         return (row.cl_geo_low, row.cl_geo_hi)
#     elif code == 'hi':
#         return (row.cl_geo_hi,row.cl_geo_low)
#     elif code == 'both':
#         return (row.cl_geo_hi, None)
#     else:
#         return (None, None)

# ee = pd.DataFrame(working.apply(gp, axis=1).to_list(), index=working.index, columns=['close_point', 'far_point'])
# pd.concat((working, ee), axis=1)

In [ ]:
# old versions of code
#     lowdist = euclidean_distance(intx_geo - cl_geo_low)
#     hidist = euclidean_distance(intx_geo - cl_geo_hi)
#     if lowdist < hidist:
#         geo_close = 'low'
#         closer_point = cl_geo_low
#         farther_point = cl_geo_hi
#         close_dist = lowdist
#         far_dist = hidist
#     elif lowdist > hidist:
#         geo_close = 'hi'
#         closer_point = cl_geo_hi
#         farther_point = cl_geo_low
#         close_dist = lowdist
#         far_dist = hidist
#     elif lowdist == hidist:
#         geo_close = 'both'
#         #assert cl_geo_low == cl_geo_hi
#         closer_point = cl_geo_low
#         farther_point = pd.NA
#         close_dist = lowdist
#         far_dist = hidist

#     out['geo_close'] = geo_close
#     out['close_point'] = closer_point
#     out['far_point'] = farther_point
#     out['close_dist'] = close_dist
#     out['far_dist'] = far_dist

#     return out


# working = pd.DataFrame(mdf.index.to_series().apply(find_close_closer_point).to_list(), index=mdf.index)
# #centerlines.loc[working[working.closer_code == 'both'].index.get_level_values(1)] # closer_code = 'both'

In [ ]:

diffs = (working['close_dist'] - working['far_dist']).abs()
# some values are zero
# drop these to make finding min easier
dd = diffs.drop(diffs[diffs == 0].index)


dd.min()

np.float64(0.0005881797990768545)

In [ ]:
# Problematic numbers?

#intersections.loc[319438198302071]
#centerlines.loc[22602]

#centerlines.loc[[84838, 31468]]
#(-85.5284187234, 38.2003603491)
#intersections.loc[[14300767569, 10005800273]]
# Problematic numbers?


#centerlines.loc[[13164, 24805, 26558]],
#intersections.loc[389674641274662])

#low_match_1[low_match_1 == 389674641274662]

# cl, ix =88673, {334354632500584, 726302145904921}


# 5 have 3 matches

# removing ramps from centerlines removed 2 of these

# 11577    {318119662229912, 318128252164504, 31811536726...
# Arthur St. and I 65 RAMP

# 79773    {731803473713560, 844908543362584, 84487847859...
# I 65 ramp

# 80073    {844438991051160, 731813464524312, 73181635861...
# I 65 ramp

# 31660    {582161378284545, 582191443055617, 61834218278...

#582161378284545	AUTUMN WAY	244	SUMMERTIME PKY	8232	(-85.8735529704, 38.0723544119)
#582191443055617	AUTUMN WAY	244	SUMMERTIME PKY	8232	(-85.8741780941, 38.0721878176)
#618342182786049	AUTUMN WAY	244	SUMMERTIME PKY	8232	(-85.873007987, 38.0733107806)

# 19920    {731744745003415, 722828392896919, 72287563753...
# I 65 RAMP



# 1 has 4 matches -> 
# removing EXPRESSWAYS from centerlines dealt with this one.

# 79772 : {731803473713560, 731813464524312, 844878478591512, 844908543362584}
# I 65 NORTH x I 65 RAMP
# no more from there 


# potential problematic numbers

#set(hi_match.keys()).intersection(hi_match2.keys()) # empty : good news
#  14288: ('start', 360168983520312, 8.767631726955189e-06),

#display(
##centerlines.loc[14288],
#intersections.loc[[360168983520312, 360748804105272]]
#

#centerlines.loc[[52803, 20860]]
#centerlines[centerlines.SIFIDLOW == 8594]
#centerlines.loc[[ 1498,  2541,  2610,  3823,  3882,  5039,  6722,  7769,  8692, 11961,
#       14175, 15423, 19704, 23933, 24872, 27737, 29258, 30870]] # I 265 RAMP.
#intersections.loc[847265632743817]
#intersections.loc[722828392896919]
#centerlines.loc[19920]
#ICpairs.loc[6146]

In [ ]:
# roadways = centerlines.groupby('SIFID').groups
# intxn_by_fst_sifid = intersections.groupby('FST_SIFID').groups
# # intxn_by_sec_sifid = intersections.groupby('SEC_SIFID') # probably not necessary
#     # ... since all records will be accessed by iterating over the fst_sifid groupby

# #intersections.FST_SIFID.hasnans # == False this is good

# def map_intersection_ids_to_centerline_ids(intersection_sifid_groups=intxn_by_fst_sifid, centerline_sifid_groups=roadways):
#     found = dict()
#     notfound = list()
#     for sifid_1 in intersection_sifid_groups.keys():
#         roadway_ids = centerline_sifid_groups.get(sifid_1, None)
#         if roadway_ids is not None:
#             found[sifid_1] = roadway_ids # first sifid match to centerlines id
#         else:
#             notfound.append(sifid_1)
#     return found, notfound

# def map_intersections_to_centerlines(intersections=intersections, centerlines=centerlines):
#     mapping = pd.DataFrame(columns=['full_match', 'fst_match_only', 'sec_match_only'])
#     full_matches = pd.Series(name='full_match', dtype="O")
#     roadways = centerlines.groupby('SIFID').groups
#     intersections_by_first_sifid = intersections.groupby('FST_SIFID').groups
#     notfound = list()

#     for sifid_1, intersection_ids in intersections_by_first_sifid.items():
#         centerline_ids = roadways.get(sifid_1, None)
#         if centerline_ids is None:
#             notfound.extend(intersection_ids)
#         else:
#             fst_match = centerlines.loc[centerline_ids]
#             for intersection_id in intersection_ids:
#                 sifid_2 = intersections.at[intersection_id, 'SEC_SIFID']
#                 full_match = fst_match[(fst_match.SIFIDLOW == sifid_2) | (fst_match.SIFIDHI == sifid_2)]
#                 if full_match.empty:
#                     mapping.at[intersection_id, 'fst_match_only'] = True
#                 else:
#                     full_match = full_match.index.tolist()
#                     #print(full_match)
#                     full_matches.at[intersection_id] = full_match
        
#     if notfound:
#         centerline_sifids = roadways.keys()
#         for intersection_id, sifid_2 in intersections.loc[notfound]['SEC_SIFID'].items():
#             if sifid_2 in centerline_sifids:
#                 mapping.at[intersection_id, 'sec_match_only'] = True

#     return pd.concat((full_matches, mapping))


# mapping = map_intersections_to_centerlines()

In [ ]:
#mapping.isna().apply(any, axis=1).all()
# test that each row has at least one value filled -> Yes
#intersections.index.difference(mapping.index) # == Index([693211604576105], dtype='int64')

#display(intersections.loc[693211604576105]) -> 13554, 13555 fst, sec ids

#centerlines[centerlines.SIFID == 13555] # nope, nor 13554 
# probably just ignore this.

#mapping[mapping.full_match.notna()]
#mapping

In [ ]:
# mapping = pd.DataFrame(columns=['full_match', 'fst_match_only', 'sec_match_only'])
# roadways = centerlines.groupby('SIFID').groups
# intersections_by_first_sifid = intersections.groupby('FST_SIFID').groups
# notfound = list()

# for sifid_1, intersection_ids in intersections_by_first_sifid.items():
#     centerline_ids = roadways.get(sifid_1, None)
#     if centerline_ids is None:
#         notfound.extend(intersection_ids)
#     else:
#         fst_match = centerlines.loc[centerline_ids]
#         #print(fst_match)
#         for intersection_id in intersection_ids:
#             sifid_2 = intersections.at[intersection_id, 'SEC_SIFID']
#             full_match = fst_match[(fst_match.SIFIDLOW == sifid_2) | (fst_match.SIFIDHI == sifid_2)]

In [ ]:
centerlines[centerlines.SIFID==1178]
notfound = [624,626,689,903,2053,122932,139877,161371,161372,168074]

intersections[intersections.FST_SIFID == 1178]
nf1 = intersections[intersections.FST_SIFID.isin(notfound)]
nf2 = centerlines[centerlines.SIFID.isin(nf1.SEC_SIFID.values)] # looks to be all interstate ramps
# it makes sense that these would not be in the centerline data b/c I probably stripped them out at a some point
# you can't/shouldn't ride a bicycle on the ramps/interstate!

noramp = nf2[nf2.CORE_CLASS != "INTERSTATE RAMP"] # 205 ramps. We don't need these roadways.
#display(noramp)
#nf.groupby('CORE_CLASS').count()

#nf.groupby('SIFID').groups
#sifid_twos = intersections[intersections.FST_SIFID.isin(notfound)].SEC_SIFID.values#.groupby('SEC_SIFID').groups
#for sifid_2 in sifid_twos:
#    i = centerlines[centerlines.SIFID == sifid_2].index.tolist()
#    if not i:
#        print(sifid_2)

display(nf1, nf2)

,FST_ROADNAME,SEC_ROADNAME,SIFCODE1,SIFCODE2,FST_SIFID,SEC_SIFID,GEOMETRY,state_grid_GEO
INTID,,,,,,,,
25314647488608,BRITTANY VALLEY RD,LIME KILN LN,0692,3860,689,3636,"[-85.63739842826769, 38.29902665283227]","[-85.63739357340009, 38.29901934737176]"
25533690815846,BRITTANY VALLEY RD,GLENVIEW AVE,0692,2566,689,2525,"[-85.6434753101308, 38.2964164239941]","[-85.64347045368233, 38.296409119316834]"
285078996590724,COFFEE TREE LN,COFFEE TREE PL,2053,2084,2053,2101,"[-85.53694581749606, 38.18196699123739]","[-85.53692786727781, 38.18195926142264]"
374478301589619,BOWLES AVE,WEBSTER ST,0624,7073,626,6361,"[-85.72680382327565, 38.25712141735226]","[-85.72679894542387, 38.25711412408772]"
374942158031000,BOWLES AVE,CABEL ST,0624,0898,626,875,"[-85.72832394001115, 38.256469323450425]","[-85.72831906176425, 38.256462030381684]"
414945534616712,CANDOR AVE,GARRS LN,0931,2488,903,2460,"[-85.81636719262018, 38.189799864851885]","[-85.81636229366431, 38.189792588666876]"
422723720394881,CANDOR AVE,LINHERK AVE,0931,3881,903,3654,"[-85.8169993940186, 38.18700350303334]","[-85.81699449508736, 38.18699622741413]"
432752417703459,BOWIE CT,BOWIE DR,0622,0623,624,625,"[-85.70260626299203, 38.14657969155578]","[-85.70260140045856, 38.1465724183819]"

,ROADNAME,SIFID,SIFCODE,low_cross_ROADNAME,SIFIDLOW,LOCROSSSIF,hi_cross_ROADNAME,SIFIDHI,HICROSSSIF,CORE_CLASS,GEOLOW,GEOHI
OBJECTID,,,,,,,,,,,,
3034,LIME KILN LN,3636,3860,LANSDOWNE AVE,3536,3743,RIVER KNOLLS DR,5040,5534,PRIMARY COLLECTOR,"[-85.64473369572579, 38.31284696929362]","[-85.64555838680533, 38.313566956021305]"
3125,WEBSTER ST,6361,7073,STORY AVE,13416,6183,BOWLES AVE,626,0624,LOCAL,"[-85.72647299204654, 38.25665296892628]","[-85.72680382327565, 38.25712141735226]"
3474,GARRS LN,2460,2488,CANDOR AVE,903,0931,NORTH LN,4265,4593,LOCAL,"[-85.81636719262018, 38.189799864851885]","[-85.81741529074715, 38.18987101606344]"
4249,GLENVIEW AVE,2525,2566,DUNRAVEN DR,1696,1726,DEAD END,8594,9811,LOCAL,"[-85.64201434345283, 38.29437496714594]","[-85.64219805634245, 38.29457377056122]"
4476,BOWIE DR,625,0623,BOWIE CT,624,0622,HICKOCK DR,13326,2913,LOCAL,"[-85.70260626299203, 38.14657969155578]","[-85.70169401763651, 38.14689512558871]"
...,...,...,...,...,...,...,...,...,...,...,...,...
31463,GLENVIEW AVE,2525,2566,GRAYSON CT,2626,2679,CABIN WAY,12896,1406,LOCAL,"[-85.64079071976235, 38.29284954144796]","[-85.64125447939766, 38.293433275538995]"
32265,COFFEE TREE PL,2101,2084,DEAD END,8594,9811,COFFEE TREE LN,2053,2053,LOCAL,"[-85.53795934713116, 38.181908231935815]","[-85.53694581749606, 38.18196699123739]"
32380,GARRS LN,2460,2488,LISA AVE,3661,3890,MILL CREEK DR,4085,4384,LOCAL,"[-85.81318601529698, 38.189609592766914]","[-85.81506403880756, 38.18972105387296]"
32411,LIME KILN LN,3636,3860,CLIFFWOOD RD,1197,1183,GLEN HILL RD,2517,2558,PRIMARY COLLECTOR,"[-85.63466591203287, 38.29553984485257]","[-85.63571474635039, 38.29685834011744]"
97010,CABEL ST,875,0898,FRANKLIN ST,2314,2327,ADAMS ST,16,0016,LOCAL,"[-85.72945928078852, 38.25785310200486]","[-85.73144079495475, 38.260238493282436]"

In [ ]:
# # # This is where Rehl Rd intersects Tucker station

""" SIFIDLOW	SIFIDHI	next	previouos
7109	5908	5908	NaN	NaN # next previous should be 12697?
9233	5908	12697	NaN	NaN
...
52804	12697	4674	NaN	NaN

This is where Rehl Rd intersects Tucker station

       | Tucker Station
       |
--Rehl--====Rehl====----Rehl--
                  |
                  | Tucker Station

This makes it too annoying to connect the segments using only SIFIDS. Lots of unusual cases.
We have exact geometry data, just use that
code for this already in centerline_data notebook """

' SIFIDLOW\tSIFIDHI\tnext\tpreviouos\n7109\t5908\t5908\tNaN\tNaN # next previous should be 12697?\n9233\t5908\t12697\tNaN\tNaN\n...\n52804\t12697\t4674\tNaN\tNaN\n\nThis is where Rehl Rd intersects Tucker station\n\n       | Tucker Station\n       |\n--Rehl--====Rehl====----Rehl--\n                  |\n                  | Tucker Station\n\nThis makes it too annoying to connect the segments using only SIFIDS. Lots of unusual cases.\nWe have exact geometry data, just use that\ncode for this already in centerline_data notebook '