In [ ]:
import pandas as pd

path_to_data = "./data/cleaner/centerlines_data.json"

cldata = pd.read_json(path_to_data)
#cldata.head()

,ROADNAME,CORE_CLASS,SIFID,SIFCODE,SIFIDLOW,LOCROSSSIF,SIFIDHI,HICROSSSIF,GEOMETRY
1,SERENITY CT,LOCAL,8665,9887,1550,1557,8594,9811,"[[-85.6809503218, 38.1588670887], [-85.6810007..."
2,S 28TH ST,LOCAL,5926,6570,2854,2934,2470,2499,"[[-85.8012012237, 38.230563793], [-85.80136926..."
3,BEECH ST,LOCAL,473,0458,6487,7212,10596,D596,"[[-85.8050149882, 38.2289330216], [-85.8048524..."
4,GARDEN DR,PRIMARY COLLECTOR,2442,2470,13394,5391,4702,5128,"[[-85.6802054534, 38.2480671366], [-85.6798630..."
5,PARKWAY DR,LOCAL,4573,4974,4162,4476,8594,9811,"[[-85.7420397977, 38.2118147709], [-85.7416475..."
...,...,...,...,...,...,...,...,...,...
180232,BROOKE ELIZABETH WAY,LOCAL,15329,F540,8594,9811,15331,F541,"[[-85.7085947307, 38.1432988961], [-85.7081273..."
180233,AIKEN RIDGE DR,LOCAL,15611,F760,15610,F759,15642,F791,"[[-85.4509340541, 38.2704398554], [-85.4510619..."
180234,AIKEN RIDGE DR,LOCAL,15611,F760,15642,F791,15610,F759,"[[-85.4517479832, 38.2709209675], [-85.4518987..."
180235,AIKEN RIDGE CIR,LOCAL,15610,F759,15611,F760,15611,F760,"[[-85.4527137888, 38.2712854193], [-85.4523040..."
180236,ASHER CT,LOCAL,15642,F791,15611,F760,8594,9811,"[[-85.4517479832, 38.2709209675], [-85.4515231..."

In [262]:
# GEOMETRY is recorded as lists of lists
# this causesproblems later b/c one algo uses a hash map and lists are unhashable
#TODO Perhaps fix this in the JSON import or in the cleaned file? Look at JSON data types

def fix_geo(points:[[float, float]]) -> ((float, float),):
    return tuple((long, lat) for long, lat in points)

cldata.GEOMETRY = cldata.GEOMETRY.apply(fix_geo)
cldata.head()

,ROADNAME,CORE_CLASS,SIFID,SIFCODE,SIFIDLOW,LOCROSSSIF,SIFIDHI,HICROSSSIF,GEOMETRY
1,SERENITY CT,LOCAL,8665,9887,1550,1557,8594,9811,"((-85.6809503218, 38.1588670887), (-85.6810007..."
2,S 28TH ST,LOCAL,5926,6570,2854,2934,2470,2499,"((-85.8012012237, 38.230563793), (-85.80136926..."
3,BEECH ST,LOCAL,473,0458,6487,7212,10596,D596,"((-85.8050149882, 38.2289330216), (-85.8048524..."
4,GARDEN DR,PRIMARY COLLECTOR,2442,2470,13394,5391,4702,5128,"((-85.6802054534, 38.2480671366), (-85.6798630..."
5,PARKWAY DR,LOCAL,4573,4974,4162,4476,8594,9811,"((-85.7420397977, 38.2118147709), (-85.7416475..."

In [263]:
USE_SIFID_COLUMNS = ['ROADNAME', 'SIFID', 'SIFIDLOW', 'SIFIDHI', 'GEOMETRY']
USE_SIFCODE_COLUMNS = ['ROADNAME', 'SIFCODE', 'LOCROSSSIF', 'HICROSSSIF', 'GEOMETRY']

In [264]:
SIFID_lookup = pd.Series(cldata.groupby(by='SIFID').indices, name='Lookup by SIFID')
SIFID_lookup.index.name='SIFID'
SIFID_lookup

SIFCODE_lookup = pd.Series(cldata.groupby(by='SIFCODE').indices, name='Lookup by SIFCODE')
SIFCODE_lookup.index.name='SIFCODE'
SIFCODE_lookup

# data.groupby(by='SIFID')['SIFCODE'].apply(lambda xs:(len(set(xs)) <= 1)).all() # == True
# data.groupby(by='SIFCODE')['SIFID'].apply(lambda xs:(len(set(xs)) <= 1)).all() # == True
# unique mapping between SIFID and SIFCODE. Good news. 

SIFID_lookup

SIFID
1        [2170, 3212, 5879, 7816, 8127, 9619, 10394, 10...
2                                                  [34888]
3                                            [2393, 27523]
4                                                   [2557]
5                                                  [25529]
                               ...
15638                                       [35020, 35021]
15639                                              [35024]
15640                                              [35029]
15641                                              [35031]
15642                                              [35038]
Name: Lookup by SIFID, Length: 11347, dtype: object

In [265]:
counts = SIFID_lookup.apply(len).sort_values(ascending=True)
SIFID_lookup[counts > 1]

# if you don't care about long vs short multisegments, which I don't think we do.
multisegments = SIFID_lookup[counts > 1].index

# for a list of multi segment roads sorted by list length
SIFID_lookup[counts[counts > 1].index]

SIFID_lookup[counts>1]

#cldata[cldata.SIFID==2543]

SIFID
1        [2170, 3212, 5879, 7816, 8127, 9619, 10394, 10...
3                                            [2393, 27523]
8                             [16342, 24413, 29597, 30362]
9                                     [5193, 10855, 27942]
10               [4502, 19690, 20238, 21195, 27977, 30826]
                               ...
15624                                       [34966, 34970]
15626                         [34975, 34976, 34978, 34981]
15628                                       [34993, 35018]
15632                  [35002, 35003, 35006, 35007, 35011]
15638                                       [35020, 35021]
Name: Lookup by SIFID, Length: 5763, dtype: object

In [266]:
from operator import itemgetter

sifid_data = cldata[USE_SIFID_COLUMNS].copy()

first_last_points = sifid_data.GEOMETRY.transform({"GEOFIRST":itemgetter(0), "GEOLAST":itemgetter(-1)})

sifid_data = pd.concat((sifid_data, first_last_points), axis=1).drop("GEOMETRY", axis=1)

for name in ['next_id', 'prev_id', 'low_id', 'hi_id']:
    sifid_data[name] = pd.Series()

sifid_data.next_id.dtype
sifid_data.head()

,ROADNAME,SIFID,SIFIDLOW,SIFIDHI,GEOFIRST,GEOLAST,next_id,prev_id,low_id,hi_id
1,SERENITY CT,8665,1550,8594,"(-85.6809503218, 38.1588670887)","(-85.6812346349, 38.1581804844)",NaN,NaN,NaN,NaN
2,S 28TH ST,5926,2854,2470,"(-85.8012012237, 38.230563793)","(-85.8013692698, 38.2293433595)",NaN,NaN,NaN,NaN
3,BEECH ST,473,6487,10596,"(-85.8050149882, 38.2289330216)","(-85.8048316249, 38.2275378873)",NaN,NaN,NaN,NaN
4,GARDEN DR,2442,13394,4702,"(-85.6802054534, 38.2480671366)","(-85.6798630078, 38.2476081599)",NaN,NaN,NaN,NaN
5,PARKWAY DR,4573,4162,8594,"(-85.7420397977, 38.2118147709)","(-85.7416475277, 38.2119685968)",NaN,NaN,NaN,NaN

In [267]:
# HERE
from collections import defaultdict

# algo to get links between segments in a roadway

data = sifid_data
test_sifid = 1

roadway = data[data.SIFID == test_sifid].copy() # copy for now
starts = defaultdict(list)

for segment_id, geofirst in roadway.GEOFIRST.items():
    starts[geofirst].append(segment_id)

for segment_id, geolast in roadway.GEOLAST.items():
    next_segment_ids = starts[geolast]

    if next_segment_ids: # ignore blank lists
        roadway.at[segment_id, 'next_id'] = next_segment_ids

    ends = defaultdict(list)
    # make prev_segment_ids
    for next_id in next_segment_ids:
        ends[next_id].append(segment_id)

    for next_id, prev_segment_ids in ends.items():
        roadway.at[next_id, 'prev_id'] = prev_segment_ids
    
roadway

,ROADNAME,SIFID,SIFIDLOW,SIFIDHI,GEOFIRST,GEOLAST,next_id,prev_id,low_id,hi_id
2398,NO NAME,1,8594,8594,"(-85.8444815932, 38.2013753392)","(-85.844988314, 38.2000420639)",[30388],[30289],NaN,NaN
3506,NO NAME,1,7417,8594,"(-85.7096882714, 38.128131124)","(-85.7095108424, 38.1286888006)",[166804],NaN,NaN,NaN
6313,NO NAME,1,8594,591,"(-85.8953120366, 38.1440146893)","(-85.8920342109, 38.143922224)",[10250],[16431],NaN,NaN
8356,NO NAME,1,8594,8594,"(-85.8479877846, 38.1773413022)","(-85.8488128852, 38.1771472776)",[24435],[11064],NaN,NaN
8683,NO NAME,1,8594,8594,"(-85.8428031334, 38.2012149341)","(-85.8444815932, 38.2013753392)",[2398],[25924],NaN,NaN
10250,NO NAME,1,591,8594,"(-85.8920342109, 38.143922224)","(-85.8901779074, 38.1438753086)","[21005, 25324]",[6313],NaN,NaN
11063,NO NAME,1,8594,1813,"(-85.7086645165, 38.12493153)","(-85.7081067425, 38.1248562874)",NaN,NaN,NaN,NaN
11064,NO NAME,1,8594,8594,"(-85.8477406224, 38.1771966371)","(-85.8479877846, 38.1773413022)","[8356, 23118]",NaN,NaN,NaN
11492,NO NAME,1,8594,8594,"(-85.8485709622, 38.1776167113)","(-85.8492600142, 38.1776831385)",[28036],[23118],NaN,NaN
13954,NO NAME,1,8594,8594,"(-85.8428031334, 38.2012149341)","(-85.8434303311, 38.2008512248)","[28746, 30289]",[25924],NaN,NaN
15159,NO NAME,1,8594,591,"(-85.8902193404, 38.1431650145)","(-85.8920571895, 38.1432263537)",[28655],[25324],NaN,NaN
16431,NO NAME,1,8594,8594,"(-85.8962149075, 38.1440519846)","(-85.8953120366, 38.1440146893)","[6313, 27605]",NaN,NaN,NaN
18079,NO NAME,1,5062,8594,"(-85.8486266793, 38.1786671473)","(-85.8492600142, 38.1776831385)",[28036],NaN,NaN,NaN
19502,NO NAME,1,8594,8594,"(-85.8485709622, 38.1776167113)","(-85.8488128852, 38.1771472776)",[24435],[23118],NaN,NaN
21005,NO NAME,1,8594,8594,"(-85.8901779074, 38.1438753086)","(-85.8902193404, 38.1431650145)",[15159],[10250],NaN,NaN
23118,NO NAME,1,8594,8594,"(-85.8479877846, 38.1773413022)","(-85.8485709622, 38.1776167113)","[11492, 19502]",[11064],NaN,NaN
24435,NO NAME,1,8594,8594,"(-85.8488128852, 38.1771472776)","(-85.8496796216, 38.1768691604)",[30653],[19502],NaN,NaN
25324,NO NAME,1,8594,8594,"(-85.8901779074, 38.1438753086)","(-85.8902193404, 38.1431650145)",[15159],[10250],NaN,NaN
25407,NO NAME,1,3191,2252,"(-85.749252152, 38.2530094773)","(-85.7483408726, 38.2530911319)",NaN,NaN,NaN,NaN
25924,NO NAME,1,3405,8594,"(-85.8413015548, 38.2030656311)","(-85.8428031334, 38.2012149341)","[8683, 13954]",NaN,NaN,NaN
26919,NO NAME,1,897,8594,"(-85.8301351454, 38.2136097438)","(-85.8320107851, 38.2120229119)",NaN,NaN,NaN,NaN
27605,NO NAME,1,8594,8594,"(-85.8953120366, 38.1440146893)","(-85.8953593354, 38.1433191649)",[31519],[16431],NaN,NaN
28036,NO NAME,1,8594,8594,"(-85.8492600142, 38.1776831385)","(-85.8496796216, 38.1768691604)",[30653],[18079],NaN,NaN
28655,NO NAME,1,591,8594,"(-85.8920571895, 38.1432263537)","(-85.8953593354, 38.1433191649)",[31519],[15159],NaN,NaN
28746,NO NAME,1,8594,8594,"(-85.8434303311, 38.2008512248)","(-85.844988314, 38.2000420639)",[30388],[13954],NaN,NaN
29463,NO NAME,1,906,8594,"(-85.8150314891, 38.2184316573)","(-85.8175947344, 38.2187237448)",NaN,NaN,NaN,NaN
30289,NO NAME,1,8594,8594,"(-85.8434303311, 38.2008512248)","(-85.8444815932, 38.2013753392)",[2398],[13954],NaN,NaN
30388,NO NAME,1,8594,8594,"(-85.844988314, 38.2000420639)","(-85.8454190253, 38.1996069575)",NaN,[28746],NaN,NaN
30653,NO NAME,1,8594,8594,"(-85.8496796216, 38.1768691604)","(-85.8500822852, 38.1770641288)",NaN,[28036],NaN,NaN
31519,NO NAME,1,8594,906,"(-85.8953593354, 38.1433191649)","(-85.8967911478, 38.1433697959)",NaN,[28655],NaN,NaN
68173,NO NAME,1,5487,14426,"(-85.7646861301, 38.1559416891)","(-85.7619311578, 38.1542117285)",NaN,NaN,NaN,NaN
155638,NO NAME,1,8594,14406,"(-85.6598789184, 38.0827507506)","(-85.6600126986, 38.0831101209)",NaN,NaN,NaN,NaN
165832,NO NAME,1,3623,8594,"(-85.7456177469, 38.2512340347)","(-85.7459519847, 38.2502753669)",NaN,NaN,NaN,NaN
166804,NO NAME,1,8594,8594,"(-85.7095108424, 38.1286888006)","(-85.7095260091, 38.1286917862)",NaN,[3506],NaN,NaN

In [268]:
# rework
# no default dicts; cleaner, probably faster
# # algo to get links between segments in a roadway

test_sifid = 1
roadway = data[data.SIFID == test_sifid].copy()
roadway_index = roadway.index

groupby_geofirst = roadway.groupby(by='GEOFIRST').groups

for segment_id, geolast in roadway.GEOLAST.items():
    next_segments = groupby_geofirst.get(geolast, None)
    if next_segments is not None: #ignore empties
        roadway.at[segment_id, 'next_id'] = tuple(next_segments)

groupby_geolast = roadway.groupby(by='GEOLAST').groups

for segment_id, geofirst in roadway.GEOFIRST.items():
    prev_segments = groupby_geolast.get(geofirst, None)
    if prev_segments is not None: # ignore empties
        roadway.at[segment_id, 'prev_id'] = tuple(prev_segments)


roadway

,ROADNAME,SIFID,SIFIDLOW,SIFIDHI,GEOFIRST,GEOLAST,next_id,prev_id,low_id,hi_id
2398,NO NAME,1,8594,8594,"(-85.8444815932, 38.2013753392)","(-85.844988314, 38.2000420639)","(30388,)","(8683, 30289)",NaN,NaN
3506,NO NAME,1,7417,8594,"(-85.7096882714, 38.128131124)","(-85.7095108424, 38.1286888006)","(166804,)",NaN,NaN,NaN
6313,NO NAME,1,8594,591,"(-85.8953120366, 38.1440146893)","(-85.8920342109, 38.143922224)","(10250,)","(16431,)",NaN,NaN
8356,NO NAME,1,8594,8594,"(-85.8479877846, 38.1773413022)","(-85.8488128852, 38.1771472776)","(24435,)","(11064,)",NaN,NaN
8683,NO NAME,1,8594,8594,"(-85.8428031334, 38.2012149341)","(-85.8444815932, 38.2013753392)","(2398,)","(25924,)",NaN,NaN
10250,NO NAME,1,591,8594,"(-85.8920342109, 38.143922224)","(-85.8901779074, 38.1438753086)","(21005, 25324)","(6313,)",NaN,NaN
11063,NO NAME,1,8594,1813,"(-85.7086645165, 38.12493153)","(-85.7081067425, 38.1248562874)",NaN,NaN,NaN,NaN
11064,NO NAME,1,8594,8594,"(-85.8477406224, 38.1771966371)","(-85.8479877846, 38.1773413022)","(8356, 23118)",NaN,NaN,NaN
11492,NO NAME,1,8594,8594,"(-85.8485709622, 38.1776167113)","(-85.8492600142, 38.1776831385)","(28036,)","(23118,)",NaN,NaN
13954,NO NAME,1,8594,8594,"(-85.8428031334, 38.2012149341)","(-85.8434303311, 38.2008512248)","(28746, 30289)","(25924,)",NaN,NaN
15159,NO NAME,1,8594,591,"(-85.8902193404, 38.1431650145)","(-85.8920571895, 38.1432263537)","(28655,)","(21005, 25324)",NaN,NaN
16431,NO NAME,1,8594,8594,"(-85.8962149075, 38.1440519846)","(-85.8953120366, 38.1440146893)","(6313, 27605)",NaN,NaN,NaN
18079,NO NAME,1,5062,8594,"(-85.8486266793, 38.1786671473)","(-85.8492600142, 38.1776831385)","(28036,)",NaN,NaN,NaN
19502,NO NAME,1,8594,8594,"(-85.8485709622, 38.1776167113)","(-85.8488128852, 38.1771472776)","(24435,)","(23118,)",NaN,NaN
21005,NO NAME,1,8594,8594,"(-85.8901779074, 38.1438753086)","(-85.8902193404, 38.1431650145)","(15159,)","(10250,)",NaN,NaN
23118,NO NAME,1,8594,8594,"(-85.8479877846, 38.1773413022)","(-85.8485709622, 38.1776167113)","(11492, 19502)","(11064,)",NaN,NaN
24435,NO NAME,1,8594,8594,"(-85.8488128852, 38.1771472776)","(-85.8496796216, 38.1768691604)","(30653,)","(8356, 19502)",NaN,NaN
25324,NO NAME,1,8594,8594,"(-85.8901779074, 38.1438753086)","(-85.8902193404, 38.1431650145)","(15159,)","(10250,)",NaN,NaN
25407,NO NAME,1,3191,2252,"(-85.749252152, 38.2530094773)","(-85.7483408726, 38.2530911319)",NaN,NaN,NaN,NaN
25924,NO NAME,1,3405,8594,"(-85.8413015548, 38.2030656311)","(-85.8428031334, 38.2012149341)","(8683, 13954)",NaN,NaN,NaN
26919,NO NAME,1,897,8594,"(-85.8301351454, 38.2136097438)","(-85.8320107851, 38.2120229119)",NaN,NaN,NaN,NaN
27605,NO NAME,1,8594,8594,"(-85.8953120366, 38.1440146893)","(-85.8953593354, 38.1433191649)","(31519,)","(16431,)",NaN,NaN
28036,NO NAME,1,8594,8594,"(-85.8492600142, 38.1776831385)","(-85.8496796216, 38.1768691604)","(30653,)","(11492, 18079)",NaN,NaN
28655,NO NAME,1,591,8594,"(-85.8920571895, 38.1432263537)","(-85.8953593354, 38.1433191649)","(31519,)","(15159,)",NaN,NaN
28746,NO NAME,1,8594,8594,"(-85.8434303311, 38.2008512248)","(-85.844988314, 38.2000420639)","(30388,)","(13954,)",NaN,NaN
29463,NO NAME,1,906,8594,"(-85.8150314891, 38.2184316573)","(-85.8175947344, 38.2187237448)",NaN,NaN,NaN,NaN
30289,NO NAME,1,8594,8594,"(-85.8434303311, 38.2008512248)","(-85.8444815932, 38.2013753392)","(2398,)","(13954,)",NaN,NaN
30388,NO NAME,1,8594,8594,"(-85.844988314, 38.2000420639)","(-85.8454190253, 38.1996069575)",NaN,"(2398, 28746)",NaN,NaN
30653,NO NAME,1,8594,8594,"(-85.8496796216, 38.1768691604)","(-85.8500822852, 38.1770641288)",NaN,"(24435, 28036)",NaN,NaN
31519,NO NAME,1,8594,906,"(-85.8953593354, 38.1433191649)","(-85.8967911478, 38.1433697959)",NaN,"(27605, 28655)",NaN,NaN
68173,NO NAME,1,5487,14426,"(-85.7646861301, 38.1559416891)","(-85.7619311578, 38.1542117285)",NaN,NaN,NaN,NaN
155638,NO NAME,1,8594,14406,"(-85.6598789184, 38.0827507506)","(-85.6600126986, 38.0831101209)",NaN,NaN,NaN,NaN
165832,NO NAME,1,3623,8594,"(-85.7456177469, 38.2512340347)","(-85.7459519847, 38.2502753669)",NaN,NaN,NaN,NaN
166804,NO NAME,1,8594,8594,"(-85.7095108424, 38.1286888006)","(-85.7095260091, 38.1286917862)",NaN,"(3506,)",NaN,NaN

In [269]:
roadway
low_cross_sifs = sifid_data[sifid_data.SIFID.isin(roadway.SIFIDLOW) & (sifid_data.SIFIDHI == test_sifid)]
hi_cross_sifs = sifid_data[sifid_data.SIFID.isin(roadway.SIFIDHI) & (sifid_data.SIFIDLOW == test_sifid)]


cross_sifs = sifid_data[(sifid_data.SIFIDLOW == test_sifid) | (sifid_data.SIFIDHI == test_sifid)]
cross_sifs

,ROADNAME,SIFID,SIFIDLOW,SIFIDHI,GEOFIRST,GEOLAST,next_id,prev_id,low_id,hi_id
86,S FLOYD ST,2252,1,3191,"(-85.7483408726, 38.2530911319)","(-85.7483793493, 38.2529029274)",NaN,NaN,NaN,NaN
1332,BLUE WING DR,591,1,3925,"(-85.8920571895, 38.1432263537)","(-85.8920859804, 38.1424606241)",NaN,NaN,NaN,NaN
1893,EAGLE PASS,1813,203,1,"(-85.7079819882, 38.1254403376)","(-85.7081067425, 38.1248562874)",NaN,NaN,NaN,NaN
2389,BLUE WING DR,591,1,1,"(-85.8920342109, 38.143922224)","(-85.8920571895, 38.1432263537)",NaN,NaN,NaN,NaN
3653,ROCKFORD LN,5062,1644,1,"(-85.8482217831, 38.1784499755)","(-85.8486266793, 38.1786671473)",NaN,NaN,NaN,NaN
5361,CANE RUN RD,906,4397,1,"(-85.8124564765, 38.221092062)","(-85.8150314891, 38.2184316573)",NaN,NaN,NaN,NaN
5443,ROCKFORD LN,5062,1,5239,"(-85.8486266793, 38.1786671473)","(-85.8495054162, 38.1790719616)",NaN,NaN,NaN,NaN
8706,E JEFFERSON ST,3191,1,12883,"(-85.749252152, 38.2530094773)","(-85.7504029204, 38.253116398)",NaN,NaN,NaN,NaN
11220,CANE RUN RD,906,1,3925,"(-85.8967911478, 38.1433697959)","(-85.8969179309, 38.1426395313)",NaN,NaN,NaN,NaN
13587,CAMP GROUND RD,897,3628,1,"(-85.829307576, 38.2134911751)","(-85.8301351454, 38.2136097438)",NaN,NaN,NaN,NaN
13830,EAGLE PASS,1813,1,3694,"(-85.7081067425, 38.1248562874)","(-85.7082334889, 38.1242849999)",NaN,NaN,NaN,NaN
16034,KRAMERS LN,3405,1,470,"(-85.8413015548, 38.2030656311)","(-85.843888918, 38.2042172257)",NaN,NaN,NaN,NaN
16080,WILDWOOD DR,7417,1,7416,"(-85.7096882714, 38.128131124)","(-85.709344846, 38.1280399863)",NaN,NaN,NaN,NaN
18002,E JEFFERSON ST,3191,1,2252,"(-85.749252152, 38.2530094773)","(-85.7483793493, 38.2529029274)",NaN,NaN,NaN,NaN
20238,S FLOYD ST,2252,4561,1,"(-85.748253414, 38.253614651)","(-85.7483408726, 38.2530911319)",NaN,NaN,NaN,NaN
21390,BLUE WING DR,591,13295,1,"(-85.8919766028, 38.144740192)","(-85.8920342109, 38.143922224)",NaN,NaN,NaN,NaN
24675,CAMP GROUND RD,897,1,12247,"(-85.8301351454, 38.2136097438)","(-85.8394311455, 38.2124378335)",NaN,NaN,NaN,NaN
26722,CANE RUN RD,906,1,897,"(-85.8150314891, 38.2184316573)","(-85.8179721092, 38.2154415187)",NaN,NaN,NaN,NaN
31471,KRAMERS LN,3405,3819,1,"(-85.838190158, 38.2019594491)","(-85.8413015548, 38.2030656311)",NaN,NaN,NaN,NaN
32589,CANE RUN RD,906,1859,1,"(-85.8965300726, 38.1450205)","(-85.8967911478, 38.1433697959)",NaN,NaN,NaN,NaN
67864,KENWOOD BUSINESS DR,14426,1,4211,"(-85.7619311578, 38.1542117285)","(-85.7631107212, 38.1508951236)",NaN,NaN,NaN,NaN
68171,SOUTHSIDE DR,5487,6794,1,"(-85.7646646187, 38.1562596515)","(-85.7646861301, 38.1559416891)",NaN,NaN,NaN,NaN
68172,SOUTHSIDE DR,5487,1,2770,"(-85.7646861301, 38.1559416891)","(-85.7652067794, 38.1537816274)",NaN,NaN,NaN,NaN
155660,3RD ST,14406,1,8594,"(-85.6600126986, 38.0831101209)","(-85.6597635012, 38.0831607684)",NaN,NaN,NaN,NaN
161037,3RD ST,14406,8594,1,"(-85.6612397539, 38.0828704175)","(-85.6600126986, 38.0831101209)",NaN,NaN,NaN,NaN
165831,E LIBERTY ST,3623,4715,1,"(-85.746584773, 38.2513368194)","(-85.7456177469, 38.2512340347)",NaN,NaN,NaN,NaN
165833,E LIBERTY ST,3623,1,3160,"(-85.7456177469, 38.2512340347)","(-85.7445699002, 38.2511199108)",NaN,NaN,NaN,NaN

In [270]:


low_groups = sifid_data.groupby(['SIFID', 'SIFIDLOW'])
hi_groups = sifid_data.groupby(['SIFID', 'SIFIDHI'])

In [271]:
display(ee.groups)

sifid_data.at[10250, 'GEOFIRST']

ee.get_group((1, 897))

{(-85.9368588569, 38.0059007504): [1334, 4613], (-85.9357035089, 38.0067117905): [11316], (-85.9332150252, 38.0090934509): [20599], (-85.9269230739, 38.0128719269): [2808, 21796], (-85.9214714039, 38.0185197301): [22217], (-85.9211733181, 38.0182948037): [15032, 25011], (-85.920226447, 38.0209466657): [22427], (-85.9177209754, 38.0217571424): [27330, 156207], (-85.9109850156, 38.0353251338): [760, 23539], (-85.9092247054, 38.020250973): [156206], (-85.9044306155, 38.0590019619): [30973], (-85.9039150286, 38.0732548479): [3872], (-85.9031568358, 38.0604441876): [14364, 22359], (-85.9024561559, 38.0755850425): [4688], (-85.9021426668, 38.0599151155): [27856], (-85.9021410913, 38.0161367636): [129328], (-85.9019691315, 38.0631753404): [31805], (-85.901791716, 38.0773288704): [26315], (-85.9017865047, 38.0619966831): [7484, 21733], (-85.9010371736, 38.0626921259): [1286, 3632], (-85.9009284252, 38.08037945): [6237, 16736], (-85.9005601728, 38.1647812505): [1507], (-85.9003728005, 38.0568870525): [28268, 31196], (-85.9001086521, 38.0622067098): [28251], (-85.9000716943, 38.0830328043): [17838], (-85.8999680681, 38.0639742629): [13552, 19953], (-85.8998263165, 38.0746210479): [13420], (-85.8997326156, 38.057607122): [12362, 27017], (-85.8993559315, 38.064708605): [20186, 23404], (-85.8990979612, 38.0616779053): [17060], (-85.8990976597, 38.0583285694): [1596, 28549], (-85.8990400468, 38.0634923501): [2255, 21434], (-85.8987312102, 38.0773526484): [4663], (-85.8985487913, 38.0499456499): [8031], (-85.8984566415, 38.0590513005): [7805, 16996], (-85.8984313917, 38.0642270671): [6951, 17173], (-85.8983664162, 38.0511142868): [2186], (-85.8981712504, 38.0611945942): [22633], (-85.8981326946, 38.1263081526): [24218], (-85.8980586623, 38.1323830694): [14408], (-85.8980258599, 38.0629628132): [2204, 21799], (-85.898010651, 38.1330265089): [13109], (-85.8977582938, 38.0793604415): [169667, 169670], (-85.8977573347, 38.0650330811): [12700, 32860], (-85.8977250631, 38.059878903): [9385, 19572], (-85.897708443, 38.0507781443): [25861, 29275], (-85.8975906239, 38.0519223461): [2176], (-85.8975099066, 38.1222973577): [1140, 3070], (-85.8973413404, 38.08171251): [169665], (-85.8972999483, 38.1398442038): [19583], (-85.8972774943, 38.1642092488): [65927, 65929], (-85.8972617856, 38.054601646): [20623, 23561], (-85.897170407, 38.0657410042): [5545], (-85.897113956, 38.0666198124): [3561], (-85.8970627494, 38.0802278276): [169669], (-85.8970077632, 38.0490908946): [4932], (-85.896998231, 38.0664089497): [4639], (-85.8969785168, 38.1323612546): [4470, 8473], (-85.8969179309, 38.1426395313): [10595], (-85.8968068832, 38.0655520671): [14530], (-85.8967911478, 38.1433697959): [11220], (-85.8966312391, 38.0526378128): [26259], (-85.8965300726, 38.1450205): [32589], (-85.8965300637, 38.1137655712): [76509], (-85.8965067589, 38.1135470062): [18108], (-85.8962432977, 38.1475454619): [116836, 116837], (-85.8962316067, 38.0530899378): [16594, 24536], (-85.8962149075, 38.1440519846): [16431], (-85.8961537281, 38.1123513184): [27340], (-85.8961420437, 38.0499729122): [15338, 27406], (-85.8960781836, 38.066424474): [12608], (-85.8960609744, 38.116744711): [5263, 8272], (-85.8959977724, 38.0660108465): [19441], (-85.8959925349, 38.1323326076): [7123, 27849], (-85.8958110846, 38.0705032502): [27346], (-85.8958052187, 38.1425626194): [23542, 27578], (-85.8957236667, 38.1510656645): [116835], (-85.8957015498, 38.0521513502): [10162], (-85.8956963397, 38.1137502886): [11538], (-85.8956773218, 38.1134473769): [4131, 16549], (-85.8956225588, 38.1125096241): [23316, 25725], (-85.8955505925, 38.132317303): [25598], (-85.8955312267, 38.0627133044): [20281], (-85.8954003478, 38.1109083861): [2175], (-85.8953866833, 38.0507444486): [13099, 26672], (-85.8953593354, 38.1433191649): [31519], (-85.8953549185, 38.05561066): [96063, 96353], (-85.8953120366, 38.1440146893): [6313, 27605], (-85.8952695723, 38.0596851393): [31509], (-85.8949989984, 38.0668204292): [6468], (-85.8949249167, 38.1164498807): [33176], (-85.8948510537, 38.0635292408): [7020, 9683], (-85.8945941955, 38.1425300589): [5982, 23059], (-85.894583428, 38.0515678988): [5127, 20852], (-85.8945201858, 38.0569958421): [8445, 17280], (-85.8945164469, 38.1588625168): [17669], (-85.894403307, 38.0673559411): [11400, 29904], (-85.894346425, 38.110751264): [31276, 33172], (-85.8943367574, 38.0591986231): [26825], (-85.8942898949, 38.0723329668): [175759], ...}

KeyError: (1, 897)

In [ ]:
# THERE
data = sifid_data
test_sifid = 1

roadway = data[data.SIFID == test_sifid].copy() # copy for now

lowsifids = set(roadway.SIFIDLOW)
ends = set(roadway.SIFIDHI)
starts = lowsifids - ends

ends -= starts
starts = list(starts)

print(starts)
for row in roadway[roadway.SIFIDLOW.isin(starts)].itertuples():
    next_row = roadway[roadway.GEOFIRST == row.GEOLAST]
    if len(next_row) != 1:
        continue
    else:
        next_row_id = next_row.index.item()

        roadway.at[row_id, 'next_id'] = next_row_id
        roadway.at[next_row_id, 'prev_id'] = row_id

        row_id = next_row_id
        geolast = next_row.GEOLAST.item()

        while 1:
            next_row = roadway[roadway.GEOFIRST == geolast]
            if len(next_row) != 1:
                break
            next_row_id = next_row.index.item()

            roadway.at[row_id, 'next_id'] = next_row_id
            roadway.at[next_row_id, 'prev_id'] = row_id

            row_id = next_row_id
            geolast = next_row.GEOLAST.item()
            



roadway
# this one is the problem
#      ROADNAME  SIFID  SIFIDLOW  SIFIDHI                         GEOFIRST  \
#8683   NO NAME      1      8594     8594  (-85.8428031334, 38.2012149341)   
#13954  NO NAME      1      8594     8594  (-85.8428031334, 38.2012149341)

[897, 5062, 3623, 3405, 5487, 3191, 7417]

,ROADNAME,SIFID,SIFIDLOW,SIFIDHI,GEOFIRST,GEOLAST,next_id,prev_id,low_id,hi_id
2398,NO NAME,1.0,8594.0,8594.0,"(-85.8444815932, 38.2013753392)","(-85.844988314, 38.2000420639)",NaN,NaN,NaN,NaN
3506,NO NAME,1.0,7417.0,8594.0,"(-85.7096882714, 38.128131124)","(-85.7095108424, 38.1286888006)",NaN,NaN,NaN,NaN
6313,NO NAME,1.0,8594.0,591.0,"(-85.8953120366, 38.1440146893)","(-85.8920342109, 38.143922224)",NaN,NaN,NaN,NaN
8356,NO NAME,1.0,8594.0,8594.0,"(-85.8479877846, 38.1773413022)","(-85.8488128852, 38.1771472776)",NaN,NaN,NaN,NaN
8683,NO NAME,1.0,8594.0,8594.0,"(-85.8428031334, 38.2012149341)","(-85.8444815932, 38.2013753392)",NaN,NaN,NaN,NaN
10250,NO NAME,1.0,591.0,8594.0,"(-85.8920342109, 38.143922224)","(-85.8901779074, 38.1438753086)",NaN,NaN,NaN,NaN
11063,NO NAME,1.0,8594.0,1813.0,"(-85.7086645165, 38.12493153)","(-85.7081067425, 38.1248562874)",NaN,NaN,NaN,NaN
11064,NO NAME,1.0,8594.0,8594.0,"(-85.8477406224, 38.1771966371)","(-85.8479877846, 38.1773413022)",NaN,NaN,NaN,NaN
11492,NO NAME,1.0,8594.0,8594.0,"(-85.8485709622, 38.1776167113)","(-85.8492600142, 38.1776831385)",NaN,NaN,NaN,NaN
13954,NO NAME,1.0,8594.0,8594.0,"(-85.8428031334, 38.2012149341)","(-85.8434303311, 38.2008512248)",NaN,NaN,NaN,NaN
15159,NO NAME,1.0,8594.0,591.0,"(-85.8902193404, 38.1431650145)","(-85.8920571895, 38.1432263537)",NaN,NaN,NaN,NaN
16431,NO NAME,1.0,8594.0,8594.0,"(-85.8962149075, 38.1440519846)","(-85.8953120366, 38.1440146893)",NaN,NaN,NaN,NaN
18079,NO NAME,1.0,5062.0,8594.0,"(-85.8486266793, 38.1786671473)","(-85.8492600142, 38.1776831385)",NaN,NaN,NaN,NaN
19502,NO NAME,1.0,8594.0,8594.0,"(-85.8485709622, 38.1776167113)","(-85.8488128852, 38.1771472776)",NaN,NaN,NaN,NaN
21005,NO NAME,1.0,8594.0,8594.0,"(-85.8901779074, 38.1438753086)","(-85.8902193404, 38.1431650145)",NaN,NaN,NaN,NaN
23118,NO NAME,1.0,8594.0,8594.0,"(-85.8479877846, 38.1773413022)","(-85.8485709622, 38.1776167113)",NaN,NaN,NaN,NaN
24435,NO NAME,1.0,8594.0,8594.0,"(-85.8488128852, 38.1771472776)","(-85.8496796216, 38.1768691604)",NaN,NaN,NaN,NaN
25324,NO NAME,1.0,8594.0,8594.0,"(-85.8901779074, 38.1438753086)","(-85.8902193404, 38.1431650145)",NaN,NaN,NaN,NaN
25407,NO NAME,1.0,3191.0,2252.0,"(-85.749252152, 38.2530094773)","(-85.7483408726, 38.2530911319)",NaN,NaN,NaN,NaN
25924,NO NAME,1.0,3405.0,8594.0,"(-85.8413015548, 38.2030656311)","(-85.8428031334, 38.2012149341)",NaN,NaN,NaN,NaN
26919,NO NAME,1.0,897.0,8594.0,"(-85.8301351454, 38.2136097438)","(-85.8320107851, 38.2120229119)",NaN,NaN,NaN,NaN
27605,NO NAME,1.0,8594.0,8594.0,"(-85.8953120366, 38.1440146893)","(-85.8953593354, 38.1433191649)",NaN,NaN,NaN,NaN
28036,NO NAME,1.0,8594.0,8594.0,"(-85.8492600142, 38.1776831385)","(-85.8496796216, 38.1768691604)",30653,166804,NaN,NaN
28655,NO NAME,1.0,591.0,8594.0,"(-85.8920571895, 38.1432263537)","(-85.8953593354, 38.1433191649)",NaN,NaN,NaN,NaN
28746,NO NAME,1.0,8594.0,8594.0,"(-85.8434303311, 38.2008512248)","(-85.844988314, 38.2000420639)",NaN,NaN,NaN,NaN
29463,NO NAME,1.0,906.0,8594.0,"(-85.8150314891, 38.2184316573)","(-85.8175947344, 38.2187237448)",NaN,NaN,NaN,NaN
30289,NO NAME,1.0,8594.0,8594.0,"(-85.8434303311, 38.2008512248)","(-85.8444815932, 38.2013753392)",NaN,NaN,NaN,NaN
30388,NO NAME,1.0,8594.0,8594.0,"(-85.844988314, 38.2000420639)","(-85.8454190253, 38.1996069575)",NaN,NaN,NaN,NaN
30653,NO NAME,1.0,8594.0,8594.0,"(-85.8496796216, 38.1768691604)","(-85.8500822852, 38.1770641288)",NaN,28036,NaN,NaN
31519,NO NAME,1.0,8594.0,906.0,"(-85.8953593354, 38.1433191649)","(-85.8967911478, 38.1433697959)",NaN,NaN,NaN,NaN
68173,NO NAME,1.0,5487.0,14426.0,"(-85.7646861301, 38.1559416891)","(-85.7619311578, 38.1542117285)",NaN,NaN,NaN,NaN
155638,NO NAME,1.0,8594.0,14406.0,"(-85.6598789184, 38.0827507506)","(-85.6600126986, 38.0831101209)",NaN,NaN,NaN,NaN
165832,NO NAME,1.0,3623.0,8594.0,"(-85.7456177469, 38.2512340347)","(-85.7459519847, 38.2502753669)",NaN,NaN,NaN,NaN
166804,NO NAME,1.0,8594.0,8594.0,"(-85.7095108424, 38.1286888006)","(-85.7095260091, 38.1286917862)",28036,4869,NaN,NaN
4869,NaN,NaN,NaN,NaN,NaN,NaN,166804,NaN,NaN,NaN

In [ ]:

geo_first_gby = sifid_data.groupby(['SIFID', 'GEOFIRST'])
geo_last_gby = sifid_data.groupby(['SIFID', 'GEOLAST'])
geo_first = geo_first_gby.groups
geo_last = geo_last_gby.groups

In [ ]:

gf_group = sifid_data.groupby('GEOFIRST').groups
gl_group = sifid_data.groupby('GEOLAST').groups

pairs = list()

for gl_point, low_group in gl_group.items():
    hi_group = gf_group.get(gl_point, None)
    if hi_group is not None:
        ...
        #pairs.append((low_group.to_list(), hi
    
low_group.to_list()

[177346]

In [ ]:
class SIF_data:
    pass

class SIFID_data(SIF_data):
    def __init__(self, centerlines:pd.DataFrame):
        self.data = ... # select out data from centerlines raw
        self.connections = self.get_geo_connections()

    def get_geo_connections(self) -> pd.DataFrame:
        self.data

In [675]:
    
pd.DataFrame.from_records(pairs, columns=["low", "hi"])

def get_geo_connections(data):
    one_to_one = list()
    one_to_many = list()
    many_to_one = list()
    many_to_many = list()

    gby_geofirst = data.groupby('GEOFIRST').groups
    gby_geolast = data.groupby('GEOLAST').groups
    for geolast_point, low_group in gby_geolast.items():
        hi_group = gby_geofirst.get(geolast_point, None)
        if hi_group is not None: #skip empties
            low_group = low_group.to_list()
            hi_group = hi_group.to_list()
            if len(low_group) == 1:
                if len(hi_group) == 1:
                    one_to_one.append((low_group[0], hi_group[0]))
                else:
                    one_to_many.append((low_group[0], hi_group))
            elif len(hi_group) == 1:
                many_to_one.append((low_group, hi_group[0]))
            else: 
                many_to_many.append((low_group, hi_group))

    return {'one_to_one': one_to_one, 
            'one_to_many': one_to_many, 'many_to_one': many_to_one,
            'many_to_many': many_to_many}
    


connections = get_geo_connections(sifid_data)
connections

{'one_to_one': [(156207, 156206),
  (156206, 129328),
  (29275, 8031),
  (2204, 22633),
  (30369, 6422),
  (22149, 10149),
  (19931, 175758),
  (13233, 29442),
  (15408, 16510),
  (13484, 29261),
  (915, 29420),
  (27250, 12755),
  (163592, 163593),
  (113637, 132847),
  (132848, 166472),
  (17599, 30642),
  (29691, 12853),
  (41607, 166475),
  (25778, 22653),
  (11672, 20423),
  (9085, 20937),
  (20941, 32395),
  (8305, 14169),
  (178954, 178952),
  (25002, 23932),
  (6534, 22619),
  (22654, 31660),
  (30994, 30428),
  (7299, 14827),
  (156513, 156514),
  (20480, 561),
  (19707, 21915),
  (22972, 27911),
  (12643, 11644),
  (12895, 33050),
  (27674, 31852),
  (18344, 21169),
  (4333, 1020),
  (7841, 31033),
  (160388, 160389),
  (1020, 12715),
  (26866, 30529),
  (1710, 7036),
  (31621, 16534),
  (965, 14427),
  (14479, 12376),
  (140847, 140848),
  (130277, 130278),
  (8401, 32355),
  (26028, 32100),
  (155657, 442),
  (31890, 8806),
  (18965, 19788),
  (19961, 29365),
  (16045, 1310),
  (167115, 167116),
  (23483, 8901),
  (23231, 12385),
  (29822, 21021),
  (31094, 18777),
  (31567, 17089),
  (9088, 166477),
  (166152, 20769),
  (169039, 169040),
  (89007, 166149),
  (14272, 30234),
  (1423, 29813),
  (147244, 146914),
  (146916, 146915),
  (157499, 157498),
  (20815, 30713),
  (155874, 155875),
  (23992, 7152),
  (15495, 3026),
  (20169, 22125),
  (28673, 28142),
  (146288, 146287),
  (25107, 10971),
  (24521, 20126),
  (8128, 11926),
  (29046, 32282),
  (158120, 158121),
  (972, 12765),
  (13172, 27163),
  (23966, 27933),
  (163268, 163269),
  (18931, 6904),
  (15364, 18846),
  (144995, 144996),
  (87422, 87423),
  (163269, 112677),
  (7231, 166483),
  (112674, 110121),
  (110125, 163268),
  (110121, 110123),
  (24326, 28443),
  (110123, 110125),
  (17821, 21319),
  (17009, 15605),
  (14598, 4273),
  (112677, 155639),
  (112675, 112674),
  (128353, 166494),
  (8080, 159114),
  (11772, 16980),
  (156834, 156833),
  (156836, 156835),
  (14337, 166796),
  (61129, 61128),
  (19625, 156834),
  (29206, 166790),
  (19397, 166797),
  (103728, 64029),
  (64027, 64028),
  (27076, 30498),
  (159109, 159108),
  (16543, 14227),
  (3158, 16061),
  (9787, 13978),
  (16106, 8795),
  (29002, 30105),
  (9956, 18511),
  (1041, 16839),
  (15274, 14839),
  (29763, 1028),
  (26250, 969),
  (764, 19167),
  (9594, 15232),
  (13332, 20264),
  (227, 228),
  (11601, 26106),
  (15313, 386),
  (26701, 24071),
  (14785, 10579),
  (8333, 14497),
  (10675, 166157),
  (19379, 494),
  (19652, 19473),
  (24944, 3874),
  (8820, 26306),
  (146608, 146281),
  (155884, 155885),
  (26554, 20881),
  (10490, 5521),
  (157477, 157476),
  (170640, 170629),
  (24011, 22613),
  (13560, 27915),
  (19368, 31879),
  (10831, 7225),
  (19278, 30914),
  (20692, 5692),
  (16214, 9476),
  (17754, 14711),
  (19696, 9578),
  (32671, 5707),
  (9080, 7329),
  (30792, 88673),
  (16608, 9765),
  (30751, 14668),
  (159439, 159438),
  (160065, 160068),
  (6305, 7128),
  (155654, 9508),
  (159760, 160066),
  (28411, 9376),
  (26461, 15104),
  (10966, 20320),
  (11007, 4374),
  (9565, 33140),
  (152997, 152998),
  (32684, 11073),
  (27624, 30777),
  (32371, 13290),
  (15543, 9397),
  (43888, 43878),
  (13325, 28070),
  (8321, 31318),
  (6606, 27534),
  (6605, 7568),
  (12655, 13899),
  (5578, 18929),
  (13224, 15348),
  (43876, 43883),
  (68173, 67864),
  (112365, 11914),
  (12938, 32055),
  (364, 525),
  (8747, 8104),
  (1757, 25996),
  (31066, 5590),
  (8495, 17738),
  (20995, 13309),
  (146596, 146595),
  (21813, 23135),
  (8972, 1429),
  (1790, 12),
  (16920, 6083),
  (52490, 52516),
  (144033, 28012),
  (110131, 110132),
  (110132, 161359),
  (30409, 6659),
  (110127, 110131),
  (32423, 30840),
  (157502, 110127),
  (161359, 161351),
  (21556, 27829),
  (157503, 157502),
  (96691, 31198),
  (23603, 17234),
  (1878, 26365),
  (10045, 27507),
  (175106, 175107),
  (163272, 163271),
  (30011, 21014),
  (32466, 12741),
  (145314, 145315),
  (7967, 12350),
  (163270, 163273),
  (80043, 9387),
  (12496, 13719),
  (22647, 11304),
  (11835, 7473),
  (27192, 24284),
  (23208, 20752),
  (17118, 13580),
  (156516, 156517),
  (14348, 12977),
  (17517, 21371),
  (20445, 32604),
  (121, 122),
  (84281, 84282),
  (8396, 25036),
  (33147, 10693),
  (22751, 21038),
  (26038, 166476),
  (24720, 28051),
  (5483, 13536),
  (28574, 4847),
  (1732, 7166),
  (3506, 166804),
  (149474, 149475),
  (10559, 166153),
  (6947, 31984),
  (165829, 165826),
  (30566, 21621),
  (13816, 7228),
  (139553, 139248),
  (45447, 45448),
  (16421, 24197),
  (56994, 56993),
  (32311, 300),
  (112681, 112680),
  (16470, 20650),
  (155647, 112684),
  (13659, 23717),
  (112680, 170627),
  (170316, 155647),
  (6978, 23726),
  (25322, 20328),
  (20973, 22598),
  (5206, 464),
  (31440, 16921),
  (27437, 29764),
  (16921, 7089),
  (32436, 26532),
  (13029, 33145),
  (15312, 166495),
  (4120, 22424),
  (18071, 30503),
  (11585, 7684),
  (23798, 20222),
  (30913, 21945),
  (15594, 3053),
  (24272, 8039),
  (166785, 117159),
  (161665, 161375),
  (146607, 146606),
  (145639, 166484),
  (89675, 89674),
  (159105, 159107),
  (84218, 84219),
  (30710, 24840),
  (11509, 17222),
  (144034, 144035),
  (19423, 166482),
  (37791, 155648),
  (155648, 18065),
  (156523, 156524),
  (157479, 157478),
  (157481, 157480),
  (4437, 18446),
  (79723, 79725),
  (6014, 25261),
  (56964, 8098),
  (107236, 140833),
  (84280, 84279),
  (166799, 25133),
  (22920, 29163),
  (343, 166489),
  (156518, 156519),
  (21695, 27465),
  (157505, 157506),
  (157485, 157484),
  (157487, 157486),
  (156528, 156527),
  (159427, 159428),
  (159120, 159112),
  (17431, 3640),
  (16341, 1653),
  (17540, 17116),
  (159119, 159111),
  (107563, 25676),
  (159429, 159116),
  (156838, 156837),
  (159425, 159118),
  (7082, 38084),
  (22451, 10078),
  (157501, 157500),
  (38091, 161360),
  (22059, 14990),
  (161039, 161350),
  (170318, 170315),
  (161040, 161349),
  (19174, 3943),
  (21082, 166465),
  (9625, 10323),
  (109804, 155636),
  (63368, 63369),
  (15779, 13498),
  (161360, 161037),
  (174792, 174793),
  (90286, 90594),
  (147882, 147881),
  (18185, 29406),
  (6814, 26714),
  (16013, 15591),
  (11737, 30993),
  (7796, 25008),
  (11859, 166808),
  (162947, 162948),
  (4299, 28096),
  (11108, 8299),
  (114303, 114288),
  (20334, 24726),
  (166493, 3582),
  (18123, 15887),
  (111, 110),
  (3218, 1785),
  (15882, 15122),
  (2198, 26696),
  (21419, 16073),
  (11374, 4750),
  (132555, 132556),
  (166806, 31764),
  (12097, 10907),
  (21163, 24428),
  (20439, 10497),
  (12005, 28394),
  (232, 226),
  (20030, 9436),
  (25520, 4681),
  (28394, 14398),
  (6911, 28181),
  (4687, 25068),
  (155636, 109812),
  (31419, 32128),
  (25761, 21954),
  (145325, 145326),
  (5757, 5102),
  (1552, 166488),
  (40641, 15770),
  (131883, 166795),
  (1608, 5676),
  (61764, 61763),
  (32906, 15246),
  (2969, 124199),
  (280, 278),
  (28755, 3616),
  (1034, 17814),
  (14562, 22474),
  (6215, 26509),
  (11347, 166471),
  (123882, 166798),
  (4574, 31955),
  (31757, 27468),
  (26226, 6819),
  (13924, 2834),
  (22378, 12319),
  (6138, 10329),
  (205, 206),
  (1102, 16881),
  (100193, 100194),
  (21855, 166487),
  (24755, 22009),
  (28612, 17980),
  (28660, 2875),
  (18290, 31391),
  (79087, 79086),
  (5316, 31157),
  (10526, 29026),
  (25385, 166154),
  (157161, 157162),
  (24267, 166467),
  (166158, 5422),
  (21476, 2715),
  (76838, 76837),
  (76836, 76835),
  (157494, 157493),
  (76840, 76839),
  (4854, 21833),
  (157493, 2966),
  (28003, 12683),
  (76833, 76834),
  (166481, 18642),
  (14846, 6981),
  (21346, 5814),
  (76843, 76844),
  (2070, 29518),
  (143076, 143075),
  (76841, 76842),
  (6098, 19355),
  (11820, 25698),
  (18295, 13472),
  (24271, 11213),
  (167759, 167433),
  (10308, 3952),
  (162310, 162311),
  (64025, 64026),
  (6910, 23424),
  (88397, 140285),
  (17923, 21918),
  (17844, 13762),
  (146285, 146286),
  (32201, 5616),
  (16428, 30911),
  (168706, 168705),
  (27836, 6053),
  (5161, 27670),
  (63363, 63362),
  (10987, 18452),
  (166805, 84253),
  (166802, 84255),
  (4981, 166787),
  (6813, 22891),
  (157495, 157496),
  (1586, 1551),
  (2346, 30086),
  (1280, 166788),
  (156196, 156195),
  (33089, 19807),
  (824, 2055),
  (8645, 13464),
  (23309, 11052),
  (161357, 161036),
  (9820, 13279),
  (59854, 19869),
  (18004, 12008),
  (157164, 157163),
  (28207, 11241),
  (166794, 85154),
  (2814, 20913),
  (18060, 28292),
  (18471, 8689),
  (87720, 87721),
  (9580, 4143),
  (28757, 26867),
  (13907, 15489),
  (173520, 173518),
  (159434, 159436),
  (179913, 179912),
  (11477, 934),
  (32961, 6629),
  (32435, 16637),
  (135728, 135727),
  (6748, 21971),
  (155650, 32352),
  (22300, 166486),
  (25182, 166468),
  (18596, 8847),
  (110440, 166470),
  (13826, 8548),
  (20974, 28996),
  (28996, 24697),
  (26321, 23559),
  (4732, 15686),
  (170650, 153320),
  (17155, 15275),
  (30883, 1951),
  (15442, 26133),
  (132546, 104673),
  (166810, 166811),
  (160397, 160396),
  (26768, 145955),
  (170652, 8287),
  (40008, 40009),
  (1569, 162320),
  (83555, 83554),
  (4599, 24833),
  (112, 113),
  (166496, 17144),
  (16094, 166480),
  (21706, 166491),
  (166803, 14923),
  (20474, 166809),
  (66903, 21312),
  (54762, 54766),
  (166490, 9955),
  (14849, 23847),
  (156197, 170648),
  (12028, 21726),
  (27989, 28187),
  (123553, 166800),
  (63378, 122321),
  (14082, 31851),
  (90943, 90942),
  (156200, 156199),
  (174, 173),
  (161363, 161348),
  (2985, 170320),
  (161366, 161361),
  (30317, 166150),
  (19274, 12817),
  (157166, 157165),
  (16227, 18222),
  (155641, 25380),
  (5394, 109475),
  (986, 109801),
  (28526, 27309),
  (86136, 86139),
  (86139, 86138),
  (157490, 157489),
  (156204, 156203),
  (157474, 157473),
  (15991, 13606),
  (161356, 161345),
  (157168, 157167),
  (16871, 4244),
  (157491, 157492),
  (29029, 166791),
  (156202, 156201),
  (167, 168),
  (24000, 6194),
  (1285, 22321),
  (19979, 8302),
  (44168, 44166),
  (31880, 7993),
  (129965, 129966),
  (38116, 155662),
  (7676, 166479),
  (38112, 38116),
  (166156, 32737),
  (140231, 166485),
  (60511, 60510),
  (131558, 155655),
  (129967, 129968),
  (131873, 131558),
  (3457, 12075),
  (24205, 8477),
  (64, 101),
  (27316, 8308),
  (6283, 3842),
  (170625, 170645),
  (34273, 34263),
  (152683, 152684),
  (13265, 3792),
  (24769, 1156),
  (160072, 135722),
  (109482, 155641),
  (109475, 109479),
  (143399, 143398),
  (157156, 157155),
  (5927, 18225),
  (109168, 109482),
  (109479, 109168),
  (157155, 157159),
  (157159, 157160),
  (85477, 166160),
  (85475, 166473),
  (60512, 151716),
  (146603, 146602),
  (164226, 164225),
  (37476, 154600),
  (22401, 14193),
  (22190, 1201),
  (161373, 161374),
  (101809, 101797),
  (161034, 161354),
  (161353, 161352),
  (156847, 157153),
  (157153, 157154),
  (161362, 161355),
  (161355, 161038),
  (161035, 161365),
  (412, 298),
  (38172, 38158),
  (1201, 109819),
  (109817, 22401),
  (411, 37474),
  (523, 37473),
  (156843, 156842),
  (156845, 156846),
  (3281, 166466),
  (37466, 37468),
  (173186, 37465),
  (156846, 127417),
  (109819, 109820),
  (155637, 109817),
  (16682, 37446),
  (155653, 156193),
  (156193, 156194),
  (38158, 38147),
  (109820, 108843),
  (177345, 155637)],
 'one_to_many': [(11316, [1334, 4613]),
  (15032, [2808, 21796]),
  (27330, [15032, 25011]),
  (23539, [27330, 156207]),
  (4932, [760, 23539]),
  (17838, [6237, 16736]),
  (20186, [13552, 19953]),
  (17173, [20186, 23404]),
  (6951, [2255, 21434]),
  (2255, [2204, 21799]),
  (5813, [9385, 19572]),
  (15338, [25861, 29275]),
  (24218, [1140, 3070]),
  (65928, [65927, 65929]),
  (27849, [4470, 8473]),
  (25122, [16594, 24536]),
  (26672, [15338, 27406]),
  (3070, [5263, 8272]),
  (25598, [7123, 27849]),
  (23059, [23542, 27578]),
  (11538, [4131, 16549]),
  (16549, [23316, 25725]),
  (20852, [13099, 26672]),
  (96064, [96063, 96353]),
  (16431, [6313, 27605]),
  (12878, [5982, 23059]),
  (38721, [5127, 20852]),
  (2634, [8445, 17280]),
  (9097, [11400, 29904]),
  (5164, [2266, 25122, 96064]),
  (4831, [23061, 31367]),
  (26319, [6993, 16325]),
  (10817, [4831, 5764]),
  (29479, [3580, 65928]),
  (10456, [14084, 28290]),
  (4720, [3950, 12878]),
  (7292, [2634, 5164]),
  (160074, [61456, 61762]),
  (13261, [3007, 23918]),
  (2491, [10116, 10817]),
  (31194, [2171, 12043]),
  (22739, [5401, 7292]),
  (3998, [26978, 29479]),
  (164230, [31194, 169668]),
  (6010, [6551, 18655]),
  (30090, [2491, 10456]),
  (15695, [1768, 31809]),
  (6046, [3067, 25792]),
  (29614, [20713, 22149]),
  (30670, [3379, 19141]),
  (4423, [2009, 11479]),
  (10250, [21005, 25324]),
  (32018, [7925, 31470]),
  (21307, [10351, 32018]),
  (12291, [4517, 25267]),
  (16303, [4598, 16540]),
  (9637, [23092, 24256]),
  (3913, [13484, 29614]),
  (13296, [3913, 17711]),
  (10445, [3236, 15459]),
  (7280, [6046, 26814]),
  (27789, [7614, 26109]),
  (26901, [27789, 30670]),
  (25267, [21466, 28476]),
  (10200, [10677, 11406]),
  (13860, [11528, 21437]),
  (1154, [25178, 26135]),
  (8775, [7280, 16330]),
  (25562, [10318, 24937]),
  (31462, [13155, 24746]),
  (17426, [10899, 10964]),
  (13956, [10200, 24370]),
  (7930, [915, 10129]),
  (13153, [4092, 10889]),
  (21858, [4728, 32950]),
  (163591, [146273, 146278]),
  (29153, [9637, 160074]),
  (22003, [10208, 26992]),
  (8709, [5898, 29153]),
  (164235, [164230, 164231]),
  (22629, [3508, 16371]),
  (26745, [8481, 24906]),
  (19189, [10589, 20833]),
  (9605, [22003, 27541]),
  (9587, [9605, 13860]),
  (10398, [864, 25562]),
  (21208, [1583, 27994]),
  (2946, [9587, 29693]),
  (33184, [25724, 175757]),
  (864, [4747, 6031]),
  (3091, [979, 18683]),
  (19049, [900, 21463]),
  (10588, [26745, 118760]),
  (28089, [13233, 22845]),
  (12066, [8926, 18978]),
  (720, [2163, 133156, 164235]),
  (118760, [118761, 118762]),
  (20970, [10588, 11955]),
  (9531, [19189, 21542]),
  (28209, [11417, 21208]),
  (6618, [1137, 4101]),
  (15572, [2562, 20996]),
  (132847, [132848, 133158]),
  (8625, [11250, 17599]),
  (13529, [5170, 26765]),
  (15158, [2272, 19399]),
  (2202, [25735, 26646]),
  (16778, [1804, 24634]),
  (18783, [18160, 20582]),
  (29269, [3091, 7390]),
  (5385, [19201, 27722]),
  (15623, [28651, 29417]),
  (21380, [3455, 16553]),
  (13451, [26172, 84269]),
  (19764, [6300, 10398]),
  (1416, [15158, 17698]),
  (3455, [6761, 30261]),
  (725, [8626, 18202, 20112]),
  (6761, [4214, 16059]),
  (4214, [2202, 27246]),
  (22512, [3413, 20536]),
  (26541, [17676, 140845]),
  (17676, [14851, 21927]),
  (32883, [10631, 15623]),
  (20523, [1416, 28424]),
  (20386, [6203, 17656]),
  (21927, [21902, 28630]),
  (18259, [22512, 41607]),
  (5169, [20386, 22138]),
  (20233, [11696, 29562]),
  (22781, [5169, 30822]),
  (2797, [14256, 29269]),
  (22619, [20121, 20233]),
  (30869, [5686, 18259]),
  (10916, [22781, 26594]),
  (23742, [5276, 25778]),
  (2082, [21401, 23742]),
  (12841, [10916, 30113]),
  (492, [9576, 24414]),
  (178952, [178951, 178953]),
  (21764, [11142, 31345]),
  (4553, [4553, 25476]),
  (20423, [3267, 9085]),
  (31091, [12512, 22182]),
  (30939, [31091, 32654]),
  (2310, [8, 4837]),
  (20937, [11894, 17284, 20509]),
  (19754, [2310, 7681]),
  (30256, [20911, 23017]),
  (20509, [9389, 25766]),
  (2983, [5331, 26724]),
  (23611, [7807, 13078]),
  (27145, [619, 12534]),
  (55684, [55370, 55376]),
  (30209, [13612, 20851]),
  (15252, [467, 3352]),
  (9536, [19764, 20857]),
  (11081, [19972, 29095]),
  (31936, [25542, 30142, 30209]),
  (6787, [8902, 13451]),
  (84256, [84258, 84275]),
  (55682, [55681, 55683]),
  (55685, [55682, 55684]),
  (24347, [1437, 22822]),
  (3978, [11396, 28856]),
  (26391, [485, 11081]),
  (8766, [3633, 15252]),
  (84257, [84256, 84260]),
  (30637, [9562, 16560]),
  (23932, [2393, 6201]),
  (7378, [492, 17715]),
  (619, [6240, 22654]),
  (21915, [5812, 25303]),
  (12501, [13049, 15814]),
  (10976, [22999, 55685]),
  (11130, [4853, 6680]),
  (24620, [32065, 32066]),
  (23666, [14843, 23146]),
  (485, [11193, 32544]),
  (1601, [14946, 16426]),
  (32165, [7378, 19825]),
  (30535, [21226, 21895]),
  (8569, [4671, 10379]),
  (3800, [8766, 10808]),
  (4741, [18763, 19008]),
  (2390, [15289, 30091]),
  (25169, [13866, 33002]),
  (18128, [8569, 23699]),
  (24019, [14406, 84257]),
  (11970, [2390, 16786]),
  (13744, [19586, 29485]),
  (14440, [18314, 27813]),
  (6715, [3153, 18128]),
  (23583, [23666, 30250]),
  (31671, [6061, 11970, 26178]),
  (19832, [11905, 26379]),
  (15918, [6715, 30994, 32847]),
  (27646, [9086, 23468]),
  (16323, [4741, 14498]),
  (8137, [1603, 13262]),
  (1642, [12052, 22826]),
  (18749, [13886, 27646]),
  (15989, [12501, 30802]),
  (25508, [6572, 12676]),
  (27100, [26391, 33024]),
  (7500, [18749, 32025]),
  (24538, [11418, 32007]),
  (12052, [31671, 32327]),
  (3828, [5706, 13961]),
  (22782, [23162, 32493]),
  (6120, [3202, 17368]),
  (25186, [4623, 21627]),
  (8078, [16323, 21709]),
  (16119, [14630, 22967]),
  (23212, [11489, 16119]),
  (8224, [12265, 23583]),
  (10204, [10852, 24019]),
  (1957, [31582, 32205]),
  (25934, [23212, 23952]),
  (1895, [15989, 32373]),
  (9275, [13744, 15918]),
  (13394, [15569, 32068]),
  (11191, [8078, 26439]),
  (9256, [12891, 20428]),
  (22163, [4303, 15723]),
  (18494, [16124, 20480]),
  (8206, [1957, 2071]),
  (25580, [6180, 8224]),
  (29129, [7898, 17524]),
  (24500, [24068, 25580]),
  (12563, [7821, 13394]),
  (7575, [9744, 26844]),
  (19136, [11191, 28955]),
  (30508, [11579, 27100]),
  (16780, [11969, 19136]),
  (27393, [11, 33048]),
  (22591, [26977, 30274]),
  (2862, [8206, 20641]),
  (8226, [18413, 20941]),
  (30133, [17531, 24500]),
  (12672, [6120, 10204]),
  (12951, [29367, 30133]),
  (9617, [17247, 21835]),
  (87435, [87436, 87437]),
  (17712, [639, 16145]),
  (18902, [1895, 10980]),
  (11586, [22591, 24896]),
  (23720, [9982, 22329]),
  (5289, [30475, 32139]),
  (79085, [10984, 21992]),
  (715, [22381, 30508]),
  (26421, [23895, 24538]),
  (27772, [18139, 23679]),
  (893, [1345, 30006]),
  (12722, [893, 19009]),
  (6682, [5343, 21488]),
  (27268, [6569, 23172]),
  (11115, [12722, 13888]),
  (16852, [23608, 23774]),
  (15868, [4066, 23323]),
  (6635, [6350, 17712]),
  (87432, [87408, 87431]),
  (7435, [14253, 21770]),
  (87431, [87427, 87430]),
  (20207, [12672, 26091]),
  (12758, [14506, 32635]),
  (19700, [13267, 23091]),
  (1565, [1535, 1539]),
  (15165, [7435, 9449]),
  (26515, [1562, 18948]),
  (29027, [6635, 32496]),
  (30951, [6785, 30247]),
  (10148, [32262, 87405]),
  (1536, [1532, 1538]),
  (12733, [6835, 17252]),
  (13911, [3203, 156513]),
  (562, [4333, 22932]),
  (4928, [5176, 28178]),
  (1564, [1533, 1536]),
  (1427, [9116, 29837]),
  (6760, [3706, 29027]),
  (3132, [10107, 25475]),
  (13608, [3170, 29820]),
  (29478, [2566, 18005]),
  (18952, [1281, 19700]),
  (32339, [3790, 29111]),
  (29820, [17401, 25295]),
  (17401, [21366, 23378]),
  (11472, [13608, 25604]),
  (30612, [11430, 23000]),
  (97000, [16735, 20918]),
  (8509, [4941, 19561]),
  (31973, [23355, 29964]),
  (28883, [8178, 15513]),
  (17018, [28375, 30951]),
  (19911, [9704, 11966]),
  (1561, [1564, 1565]),
  (22289, [4767, 5769]),
  (20859, [3132, 18529]),
  (22561, [20551, 22465]),
  (13969, [7633, 24232]),
  (32932, [7908, 18907]),
  (8560, [10309, 31251]),
  (13444, [20411, 21788]),
  (6100, [20621, 21987]),
  (7708, [827, 19911]),
  (32385, [14132, 20859]),
  (6933, [14853, 30100]),
  (28657, [2085, 10121]),
  (28837, [18598, 27453]),
  (391, [8124, 32385]),
  (16541, [483, 21798]),
  (13462, [9029, 13317]),
  (25753, [567, 7977]),
  (6490, [2835, 18397]),
  (15336, [782, 29821]),
  (169347, [169346, 169350]),
  (5825, [4483, 6490]),
  (7974, [20864, 22314]),
  (3029, [3199, 5825]),
  (19184, [3029, 7841, 15012]),
  (17870, [2404, 28837]),
  (3759, [16328, 25519]),
  (9344, [309, 130279]),
  (1121, [13462, 29847]),
  (22285, [2225, 4076]),
  (22908, [1373, 23094]),
  (16903, [4851, 7659]),
  (25444, [19000, 26866]),
  (19767, [10216, 24339]),
  (8917, [12056, 12925]),
  (9315, [13825, 22529]),
  (6585, [25577, 26001]),

In [702]:
cxda = pd.DataFrame(columns=['next_id', 'prev_id', 'hi_id', 'low_id', 'cx_hi', 'cx_low'])

def set_one_to_one_connection(data, low_index, hi_index):
    low_row = data.loc[low_index]
    hi_row = data.loc[hi_index]
    if low_row.SIFID == hi_row.SIFID:
        # same road way
        cxda.at[low_index, 'next_id'] = hi_index 
        cxda.at[hi_index, 'prev_id'] = low_index
    else:
        notfound = True
        if low_row.SIFIDHI == hi_row.SIFID:
            cxda.at[low_index, 'hi_id'] = hi_index
            cxda.at[hi_index, 'low_id'] = low_index
            notfound = False
        if hi_row.SIFIDHI == low_row.SIFID: # this can happen. *shrug*
            cxda.at[low_index, 'low_id'] = hi_index
            cxda.at[hi_index, 'hi_id'] = low_index
            notfound = False
        if notfound:
            cxda.at[low_index, 'cx_hi'] = hi_index
            cxda.at[hi_index, 'cx_low'] = low_index 
        

def set_one_to_many_connection(data, low_index, hi):
    ...

def set_many_to_one_connection(data, low, hi_index):
    ...

def set_many_to_many_connection(data, low, hi):
    ...

In [703]:
for lo, hi in connections['one_to_one']:
    set_one_to_one_connection(sifid_data, lo, hi)

cxda

       next_id prev_id   hi_id  low_id cx_hi cx_low
156207  156206     NaN     NaN     NaN   NaN    NaN
156206     NaN  156207  129328     NaN   NaN    NaN
129328     NaN     NaN     NaN  156206   NaN    NaN
29275      NaN     NaN    8031     NaN   NaN    NaN
8031       NaN     NaN     NaN   29275   NaN    NaN
...        ...     ...     ...     ...   ...    ...
156193  156194  155653     NaN     NaN   NaN    NaN
156194     NaN  156193     NaN     NaN   NaN    NaN
38147      NaN     NaN     NaN   38158   NaN    NaN
108843     NaN     NaN     NaN  109820   NaN    NaN
177345     NaN     NaN  155637     NaN   NaN    NaN

[1185 rows x 6 columns]

In [699]:
display(cxda.cx_hi[cxda.cx_hi.notna()], 
        cxda.cx_low[cxda.cx_low.notna()])

27624    30777.0
Name: cx_hi, dtype: float64

30777    27624.0
Name: cx_low, dtype: float64

In [700]:
sifid_data.loc[[27624 ,   30777]]

,ROADNAME,SIFID,SIFIDLOW,SIFIDHI,GEOFIRST,GEOLAST,next_id,prev_id,low_id,hi_id
27624,CANDACE WAY,8326,8325,8594,"(-85.7719600219, 38.1430445354)","(-85.771592421, 38.1424571006)",NaN,NaN,NaN,NaN
30777,CONNOR WAY,8327,8594,2672,"(-85.771592421, 38.1424571006)","(-85.7715273214, 38.1412880284)",NaN,NaN,NaN,NaN

In [694]:
cxda.loc[[30777,   27624,
17234,    23603,
160396   , 160397,
21726   ,   12028]]

        next_id  prev_id  hi_id  low_id     cx_hi    cx_low
30777       NaN      NaN    NaN     NaN       NaN   27624.0
27624       NaN      NaN    NaN     NaN   30777.0       NaN
17234       NaN      NaN    NaN     NaN       NaN   23603.0
23603       NaN      NaN    NaN     NaN   17234.0       NaN
160396      NaN      NaN    NaN     NaN       NaN  160397.0
160397      NaN      NaN    NaN     NaN  160396.0       NaN
21726       NaN      NaN    NaN     NaN       NaN   12028.0
12028       NaN      NaN    NaN     NaN   21726.0       NaN

In [ ]:


#display(lowdata, hidata)

fix_list = lambda xs: (xs if xs else None)

for index, value in lowdata.SIFID.items():
    comp = hidata[hidata.SIFID == value].index.tolist()
    #display(comp)
    comp2 = hidata[~hidata.index.isin(comp)].index.tolist() 

    display({'index':index, 'next_id':fix_list(comp), 'hi_id':fix_list(comp2)})
    
e = hidata.index.tolist()

da = dict()

#for ix, sifid in lowdata.SIFID.items():
#    display(ix, row)
#    seq_match = hidata[hidata.SIFID == sifid].index 
#    this = {'next_id': seq_match}
#    da[ix] = this
#da


low = lowdata.iloc[0]

hidata[hidata.SIFID == low.SIFID]

{'index': 1573, 'next_id': [10219], 'hi_id': [14380]}

,ROADNAME,SIFID,SIFIDLOW,SIFIDHI,GEOFIRST,GEOLAST,next_id,prev_id,low_id,hi_id
14380,CASTLEVIEW DR,1001,6413,8594,"(-85.6391830222, 38.2612831118)","(-85.641012932, 38.2634883978)",NaN,NaN,NaN,NaN

In [654]:

cxda = pd.DataFrame(columns=['next_id','prev_id','low_id', 'hi_id', 'cx_low', 'cx_hi'])
setlist = lambda xs:(tuple(xs) if xs else None)



def fix(xs):
    length = len(xs)
    if length == 1:
        return xs[0]
    elif length:
        return list(xs)
    else:
        return pd.NA
        

def match_roadways(data, connection_pair, memo=cxda):
    low, hi = connection_pair
    lowlen = len(low) == 1 
    hilen = len(hi) == 1

    # one to one
    if lowlen and hilen:
        hi_index = hi[0]
        low_index = low[0]
        low_SIFID = data.at[low_index, 'SIFID']
        if data.at[hi_index, 'SIFID'] == low_SIFID:
            # same roadway
            cxda.at[low_index, 'next_id'] = hi_index
            cxda.at[hi_index, 'prev_id'] = low_index
            # probably shouldn't put the lists here directly might need to make a copy.
            # what happens if this list is modified somehow? Could that ever happen?
            # If now, it probably doesn't matter. 
            # This result data will get copied into another DataFrame at some point anyway.
        elif data.at[hi_index, 'SIFIDLOW'] == low_SIFID:
            # intersetion
            cxda.at[low_index, 'hi_id'] = hi_index
            cxda.at[hi_index, 'low_id'] = low_index
        else:
            # some other weird case: possibly no such entries
            cxda.at[low_index, 'cx_hi'] = hi_index
            cxda.at[hi_index, 'cx_low'] = low_index

    # one to many or many to one
    elif lowlen or hilen:
        # one low to many hi
        if lowlen:
            low_index = low[0]
            low_SIFID = data.at[low_index, 'SIFID']
            hi_rows = data.loc[hi]

            # get hi roadways, cross streets, other
            hi_roadways = hi_rows[hi_rows.SIFID == low_SIFID].index
            hi_cross = hi_rows[hi_rows.SIFIDLOW == low_SIFID].index
            hi_other = hi_rows.index.difference(hi_roadways.union(hi_cross))

            # set low data
            cxda.at[low_index, 'next_id'] = fix(hi_roadways)
            cxda.at[low_index, 'hi_id'] = fix(hi_cross)
            cxda.at[low_index, 'cx_hi'] = fix(hi_other)

            # set hi data
            for hi_index in hi_roadways:
                cxda.at[hi_index, 'prev_id'] = low_index
            for hi_index in hi_cross:
                cxda.at[hi_index, 'low_id'] = low_index
            for hi_index in hi_other:
                cxda.at[hi_index, 'cx_low'] = low_index
            #cxda.loc[hi_roadways, 'prev_id'] = low_index
            #cxda.loc[hi_cross, 'low_id'] = low_index
            #cxda.loc[hi_other, 'cx_low'] = low_index

        # many low to one hi
        else:
            hi_index = hi[0]
            hi_SIFID = data.at[hi_index, 'SIFID']
            low_rows = data.loc[low]

            # get low roadways, cross streets, other
            low_roadways = low_rows[low_rows.SIFID == hi_SIFID].index
            low_cross = low_rows[low_rows.SIFIDHI == hi_SIFID].index
            low_other = low_rows.index.difference(low_roadways.union(low_cross))

            # set hi data
            cxda.at[hi_index, 'prev_id'] = fix(low_roadways)
            cxda.at[hi_index, 'low_id'] = fix(low_cross)
            cxda.at[hi_index, 'cx_low'] = fix(low_other)

            # set low data
            for low_index in low_roadways:
                cxda.at[hi_index, 'next_id'] = hi_index
            for low_index in low_cross:
                cxda.at[hi_index, 'hi_id'] = hi_index
            for low_index in low_other:
                cxda.at[hi_index, 'cx_hi'] = hi_index

    # many low to many hi 
    else:
        low_rows = data.loc[low].SIFID
        hi_rows = data.loc[hi][['SIFID', 'SIFIDLOW']]

        for low_index, low_SIFID in low_rows.items():
            low_roadways = hi_rows[hi_rows.SIFID == low_SIFID].index
            low_cross = hi_rows[hi_rows.SIFIDLOW == low_SIFID].index
            low_other = low_roadways.union(low_cross).symmetric_difference(hi)

            cxda.at[low_index, 'next_id'] = fix(low_roadways)
            cxda.at[low_index, 'hi_id'] = fix(low_cross)
            cxda.at[low_index, 'cx_hi'] = fix(low_other)

        for hi_index, hi_SIFID, hi_SIFIDLOW in hi_rows.itertuples():
            hi_roadways = low_rows[low_rows == hi_SIFID].index
            hi_cross = low_rows[low_rows == hi_SIFIDLOW].index
            hi_other = hi_roadways.union(hi_cross).symmetric_difference(low)

            cxda.at[hi_index, 'prev_id'] = fix(hi_roadways)
            cxda.at[hi_index, 'low_id'] = fix(hi_cross)
            cxda.at[hi_index, 'cx_low'] = fix(hi_other)

In [655]:

"""
if lowlen:
    low_index = low[0]
    low_SIFID = data.at[low_index, "SIFID"]
    ...
    rwy =hi[hi.SIFID == low_SIFID]
    rwy[prev] == this
    cross =hi[hi.SIFIDLOW == low_SIFID]
    other = hi[~(rwy + cross)]
""" 

for low, hi in connections:
    match_roadways(sifid_data, (low, hi))

cxda

       next_id prev_id  low_id   hi_id cx_low cx_hi
11316    11316   21796   20599   11316   <NA>  <NA>
4613       NaN   11316     NaN     NaN    NaN   NaN
1334       NaN     NaN   11316     NaN    NaN   NaN
15032    21796   27330     NaN    2808    NaN  <NA>
21796      NaN   15032     NaN     NaN    NaN   NaN
...        ...     ...     ...     ...    ...   ...
177349  108844  177348     NaN  177347    NaN  <NA>
108844     NaN  177349     NaN     NaN    NaN   NaN
177347     NaN     NaN  177349     NaN    NaN   NaN
177348  177349     NaN     NaN  177040    NaN  <NA>
177040     NaN     NaN  177348     NaN    NaN   NaN

[32453 rows x 6 columns]

In [659]:
cxda.cx_low.value_counts()

cx_low
19532     2
29529     2
164237    2
27573     2
20410     2
         ..
15064     1
13157     1
33114     1
5500      1
1932      1
Name: count, Length: 881, dtype: int64

In [657]:
cxda.cx_low[~cxda.cx_low.isna()]

27856      27017
26259      10162
2266        5164
25824      11250
22739     146278
           ...
38130      37473
1541        1542
1567      104687
123873     10584
44807       1932
Name: cx_low, Length: 1101, dtype: object

In [665]:
test = [27856 , 27017]
test = [44807     ,  1932]

display(
sifid_data.loc[test, :],
cxda.loc[test, :])
#sifid_data.loc[[44807   ,    1932],:]

,ROADNAME,SIFID,SIFIDLOW,SIFIDHI,GEOFIRST,GEOLAST,next_id,prev_id,low_id,hi_id
44807,ASHWORTH LN,12632,12804,10745,"(-85.4139452562, 38.2369794317)","(-85.4163812062, 38.2373828508)",NaN,NaN,NaN,NaN
1932,NOTTING HILL BLVD,12583,12595,12804,"(-85.4124007712, 38.2367036922)","(-85.4139452562, 38.2369794317)",NaN,NaN,NaN,NaN

      next_id prev_id low_id  hi_id cx_low  cx_hi
44807     NaN    <NA>   1727  44807   1932  44807
1932      NaN   20271    NaN    NaN    NaN    NaN

In [519]:
xs = sifid_data.loc[102:105].copy()

ys = sifid_data.loc[105:107].copy()

display(xs, ys)

,ROADNAME,SIFID,SIFIDLOW,SIFIDHI,GEOFIRST,GEOLAST,next_id,prev_id,low_id,hi_id
102,W CHESTNUT ST,1132,5608,1870,"(-85.7659874323, 38.2498497625)","(-85.764499876, 38.2496818796)",NaN,NaN,NaN,NaN
103,HASKIN AVE,2767,3708,3525,"(-85.7867074545, 38.1729543037)","(-85.7889057879, 38.1732430068)",NaN,NaN,NaN,NaN
104,PEACHTREE AVE,4597,889,474,"(-85.7795133347, 38.1925305777)","(-85.7795077699, 38.1916873341)",NaN,NaN,NaN,NaN
105,WOODRIDGE LAKE BLVD,10332,12657,10756,"(-85.860284218, 38.0911579781)","(-85.8613810886, 38.091199465)",NaN,NaN,NaN,NaN

,ROADNAME,SIFID,SIFIDLOW,SIFIDHI,GEOFIRST,GEOLAST,next_id,prev_id,low_id,hi_id
105,WOODRIDGE LAKE BLVD,10332,12657,10756,"(-85.860284218, 38.0911579781)","(-85.8613810886, 38.091199465)",NaN,NaN,NaN,NaN
106,WOODRIDGE LAKE BLVD,10332,10329,12657,"(-85.8594025126, 38.0924017026)","(-85.860284218, 38.0911579781)",NaN,NaN,NaN,NaN
107,SAND PIT LN,12657,10332,8594,"(-85.860284218, 38.0911579781)","(-85.8592079035, 38.0897552569)",NaN,NaN,NaN,NaN

In [527]:
xs.index.difference(ys.index)

Index([102, 103, 104], dtype='int64')