In [ ]:
import pandas as pd

from re import compile as re_compile

# path to CSV of centerlines coordinates
path_to_coordinates = "./data/cleaner/centerline_coordinates.csv"
centerline_data = "./data/cleaner/centerline_data.csv"

CO = coordinates = pd.read_csv(path_to_coordinates, index_col="OBJECTID")
cldata = pd.read_csv(centerline_data, index_col='OBJECTID')
[C for C in cldata.columns if "ADD" in C]

FileNotFoundError: [Errno 2] No such file or directory: '/Users/bencampbell/code/county_coverage/data/cleaner/centerline_coordinates.csv'

In [ ]:
cldata[['SIFIDHI', 'HICROSSSIF', 'HICROSSSU',
 'SIFIDLOW','LOCROSSSIF','LOCROSSPR','LOCROSSNA','LOCROSSSU']]

,SIFIDHI,HICROSSSIF,HICROSSPR,HICROSSNA,HICROSSSU,SIFIDLOW,LOCROSSSIF,LOCROSSPR,LOCROSSNA,LOCROSSSU
OBJECTID,,,,,,,,,,
1,8594,9811,NaN,DEAD END,NaN,1550,1557,NaN,DELLAFAY,DR
2,2470,2499,W,GAULBERT,AVE,2854,2934,W,HILL,ST
3,10596,D596,NaN,DR WILLIAM G WEATHERS,DR,6487,7212,NaN,WILSON,AVE
4,4702,5128,NaN,POPPY,WAY,13394,5391,NaN,RAINBOW,DR
5,8594,9811,NaN,DEAD END,NaN,4162,4476,NaN,MOUNT CLAIRE,AVE
...,...,...,...,...,...,...,...,...,...,...
172237,15435,F595,NaN,STONECROP,DR,15497,F645,NaN,SHOOTING STAR,DR
172238,14968,F356,NaN,PASSIONFLOWER,DR,15435,F595,NaN,STONECROP,DR
172239,3941,4214,W,MARKET,ST,8594,9811,NaN,DEAD END,NaN
172240,11996,D964,NaN,UNITY,PL,3206,3344,W,CARDINAL,BLVD
172545,2299,2305,S,4TH,ST,8594,9811,NaN,DEAD END,NaN

In [ ]:
# lookup based on sifids or other codes

def get_sifid(data, sifid:int):
    return data[data.SIFID == sifid]

def get_sifcode(data, sifcode=str):
    return data[data.SIFCODE == sifcode]

def get_sif(data, sifx):
    if isinstance(sifx, int):
        data[data.SIFID == sifid]
    elif isinstance(sifx, str):
        data[data.SIFCODE == sifcode]

def get_sifid(data, sifid=True, sifcode=F):


cldata[cldata.SIFCODE == '4974'].ROADNAME
#cldata.SIFCODE

cldata.SIFID[1]

np.int64(8665)

In [291]:
from collections import defaultdict

sifs = defaultdict(list)

cldata.SIFCODE.combine(cldata.SIFID, lambda x, y:sifs[x].append(y))

sifs

defaultdict(list,
            {'9887': [np.int64(8665), np.int64(8665)],
             '6570': [np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926),
              np.int64(5926)],
             '0458': [np.int64(473),
              np.int64(473),
              np.int64(473),
              np.int64(473),
              np.int64(473),
              np.int64(473),
              np.int64(473),
              np.int64(473),
              np.int64(473),
              np.int64(473),
              np.int64(473)],
             '2470': [np.int64(2442),
              np.int64(2442),
              np.int64(2442),
              np.int64(2442),
              np.int64(2442),
              np.int64(2442),
              np.int64(2442),
              np.int64(2442),
              np.int64(2442),
              np.int64(2442)],
             '4974': [np.int64(4573),
              np.int64(4573),
              np.int64(4573),
              np.int64(4573),
              np.int64(4573),
              np.int64(4573),
              np.int64(4573),
              np.int64(4573),
              np.int64(4573),
              np.int64(4573),
              np.int64(4573),
              np.int64(4573),
              np.int64(4573),
              np.int64(4573)],
             '4118': [np.int64(13360),
              np.int64(13360),
              np.int64(13360),
              np.int64(13360),
              np.int64(13360),
              np.int64(13360),
              np.int64(13360),
              np.int64(13360),
              np.int64(13360),
              np.int64(13360),
              np.int64(13360),
              np.int64(13360),
              np.int64(13360),
              np.int64(13360),
              np.int64(13360)],
             'E389': [np.int64(2082)],
             '7752': [np.int64(6942),
              np.int64(6942),
              np.int64(6942),
              np.int64(6942),
              np.int64(6942),
              np.int64(6942),
              np.int64(6942)],
             'E021': [np.int64(12052),
              np.int64(12052),
              np.int64(12052),
              np.int64(12052)],
             '2383': [np.int64(2363),
              np.int64(2363),
              np.int64(2363),
              np.int64(2363),
              np.int64(2363),
              np.int64(2363),
              np.int64(2363),
              np.int64(2363)],
             '9150': [np.int64(8033),
              np.int64(8033),
              np.int64(8033),
              np.int64(8033),
              np.int64(8033),
              np.int64(8033)],
             '5238': [np.int64(4793)],
             '8695': [np.int64(13479)],
             '7132': [np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413),
              np.int64(6413)],
             'E473': [np.int64(12597)],
             '0285': [np.int64(293)],
             '5709': [np.int64(5193),
              np.int64(5193),
              np.int64(5193),
              np.int64(5193),
              np.int64(5193),
              np.int64(5193),
              np.int64(5193)],
             '1232': [np.int64(1237),
              np.int64(1237),
              np.int64(1237),
              np.int64(1237),
              np.int64(1237),
              np.int64(1237),
              np.int64(1237)],
             '9955': [np.int64(8725),
              np.int64(8725),
              np.int64(8725),
              np.int64(8725),
              np.int64(8725),
              np.int64(8725),
              np.int64(8725),
              np.int64(8725),
              np.int64(8725),
              np.int64(8725),
              np.int64(8725),
              np.int64(8725),
              np.int64(8725),
              np.int64(8725),
              np.int64(8725),
              np.int64(8725),
              np.int64(8725),
              np.int64(8725),
              np.int64(8725),
              np.int64(8725),
              np.int64(8725),
              np.int64(8725),
              np.int64(8725),
              np.int64(8725),
              np.int64(8725),
              np.int64(8725),
              np.int64(8725),
              np.int64(8725),
              np.int64(8725),
              np.int64(8725),
              np.int64(8725),
              np.int64(8725)],
             '1181': [np.int64(1195),
              np.int64(1195),
              np.int64(1195),
              np.int64(1195),
              np.int64(1195),
              np.int64(1195),
              np.int64(1195),
              np.int64(1195),
              np.int64(1195),
              np.int64(1195),
              np.int64(1195),
              np.int64(1195),
              np.int64(1195),
              np.int64(1195)],
             '7592': [np.int64(6800), np.int64(6800)],
             '9351': [np.int64(8199),
              np.int64(8199),
              np.int64(8199),
              np.int64(8199),
              np.int64(8199)],
             'E568': [np.int64(12691),
              np.int64(12691),
              np.int64(12691),
              np.int64(12691),
              np.int64(12691),
              np.int64(12691)],
             'E674': [np.int64(12797), np.int64(12797)],
             'E675': [np.int64(12798)],
             'E583': [np.int64(12706), np.int64(12706), np.int64(12706)],
             'E581': [np.int64(12704),
              np.int64(12704),
              np.int64(12704),
              np.int64(12704),
              np.int64(12704),
              np.int64(12704)],
             'E582': [np.int64(12705), np.int64(12705)],
             '9409': [np.int64(8239),
              np.int64(8239),
              np.int64(8239),
              np.int64(8239),
              np.int64(8239),
              np.int64(8239),
              np.int64(8239),
              np.int64(8239),
              np.int64(8239),
              np.int64(8239),
              np.int64(8239),
              np.int64(8239),
              np.int64(8239)],
             'E632': [np.int64(12755)],
             '0231': [np.int64(248),
              np.int64(248),
              np.int64(248),
              np.int64(248),
              np.int64(248)],
             'E989': [np.int64(14177)],
             '2323': [np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312),
              np.int64(2312)],
             'F029': [np.int64(14285), np.int64(14285)],
             '8199': [np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259),
              np.int64(7259)],
             'F030': [np.int64(14287), np.int64(14287)],
             '9995': [np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762),
              np.int64(8762)],
             '0478': [np.int64(490),
              np.int64(490),
              np.int64(490),
              np.int64(490),
              np.int64(490),
              np.int64(490),
              np.int64(490),
              np.int64(490)],
             '9987': [np.int64(8755), np.int64(8755)],
             '4552': [np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227),
              np.int64(4227)],
             'E393': [np.int64(1282),
              np.int64(1282),
              np.int64(1282),
              np.int64(1282),
              np.int64(1282),
              np.int64(1282)],
             '4748': [np.int64(4387),
              np.int64(4387),
              np.int64(4387),
              np.int64(4387),
              np.int64(4387),
              np.int64(4387),
              np.int64(4387),
              np.int64(4387),
              np.int64(4387),
              np.int64(4387)],
             '2479': [np.int64(2451),

In [330]:
gby_sifcode = pd.Series(cldata.groupby(by='SIFCODE').indices)
gby_sifid = pd.Series(cldata.groupby(by='SIFID').indices)

gby_sifcode

0000    [2176, 3223, 5898, 7630, 7843, 8155, 9650, 104...
0001                                              [29339]
0002                                        [2400, 27591]
0003                                               [2565]
0004                                              [25593]
                              ...
F710                                       [34854, 34855]
F711                                              [34860]
F712                                              [34859]
F713                                              [34862]
F714                                              [34871]
Length: 11285, dtype: object

In [ ]:
pairs = {id:code for id, code in zip(gby_sifid.index, gby_sifcode.index)}

for key, code in pairs.items():
    code = int(code)
    if code != key -1:
        #print(key)
        break


max(pairs.keys())
keys = set(pairs.keys())

memo = 27
for m in [n for n in range(1, 15567) if n not in keys]:
    print(m, m - memo)
    memo = m

27 27
63 36
84 21
147 63
180 33
219 39
243 24
361 118
366 5
381 15
389 8
398 9
402 4
418 16
455 37
465 10
519 54
784 265
790 6
848 58
899 51
917 18
941 24
969 28
991 22
998 7
1037 39
1102 65
1164 62
1178 14
1241 63
1259 18
1306 47
1477 171
1618 141
1624 6
1634 10
1636 2
1704 68
1825 121
1843 18
1855 12
1881 26
1889 8
1934 45
1967 33
1973 6
2023 50
2062 39
2093 31
2165 72
2227 62
2258 31
2277 19
2297 20
2302 5
2311 9
2315 4
2316 1
2327 11
2330 3
2349 19
2350 1
2368 18
2427 59
2447 20
2450 3
2528 78
2616 88
2708 92
2750 42
2758 8
2826 68
2894 68
2907 13
2987 80
3005 18
3008 3
3038 30
3066 28
3071 5
3096 25
3131 35
3146 15
3159 13
3177 18
3203 26
3231 28
3241 10
3262 21
3266 4
3273 7
3327 54
3333 6
3359 26
3361 2
3416 55
3417 1
3445 28
3446 1
3448 2
3457 9
3492 35
3601 109
3612 11
3621 9
3647 26
3690 43
3716 26
3739 23
3741 2
3747 6
3751 4
3752 1
3764 12
3766 2
3803 37
3827 24
3842 15
3844 2
3870 26
3890 20
3893 3
3894 1
3912 18
3921 9
3939 18
3948 9
4041 93
4044 3
4050 6
4054 4
4070 16
4083 13
4090 7
4109 19
4126 17
4132 6
4137 5
4195 58
4212 17
4215 3
4251 36
4260 9
4267 7
4283 16
4289 6
4316 27
4317 1
4341 24
4353 12
4374 21
4377 3
4458 81
4460 2
4480 20
4497 17
4498 1
4499 1
4518 19
4525 7
4536 11
4588 52
4677 89
4694 17
4695 1
4711 16
4717 6
4736 19
4740 4
4743 3
4745 2
4751 6
4755 4
4768 13
4775 7
4784 9
4825 41
4836 11
4843 7
4852 9
4853 1
4857 4
4858 1
4879 21
4880 1
4883 3
4889 6
4892 3
4895 3
4898 3
4901 3
4903 2
4907 4
4977 70
4983 6
4984 1
4985 1
5007 22
5010 3
5015 5
5025 10
5027 2
5031 4
5094 63
5105 11
5131 26
5159 28
5168 9
5169 1
5170 1
5171 1
5187 16
5200 13
5219 19
5222 3
5223 1
5225 2
5228 3
5234 6
5299 65
5303 4
5307 4
5323 16
5327 4
5329 2
5331 2
5345 14
5352 7
5385 33
5387 2
5415 28
5416 1
5426 10
5437 11
5441 4
5455 14
5467 12
5472 5
5506 34
5510 4
5514 4
5603 89
5627 24
5631 4
5633 2
5647 14
5660 13
5663 3
5665 2
5666 1
5670 4
5676 6
5708 32
5748 40
5789 41
5829 40
5838 9
5841 3
5848 7
5863 15
5872 9
5905 33
5984 79
5985 1
6001 16
6012 11
6017 5
6023 6
6026 3
6030 4
6045 15
6063 18
6083 20
6113 30
6127 14
6137 10
6185 48
6189 4
6197 8
6201 4
6203 2
6225 22
6270 45
6303 33
6345 42
6351 6
6353 2
6384 31
6400 16
6410 10
6424 14
6447 23
6451 4
6464 13
6466 2
6472 6
6537 65
6544 7
6579 35
6597 18
6616 19
6661 45
6693 32
6724 31
6737 13
6746 9
6766 20
6811 45
6815 4
6865 50
6866 1
6878 12
6908 30
6988 80
6999 11
7050 51
7107 57
7157 50
7218 61
7230 12
7235 5
7274 39
7340 66
7342 2
7371 29
7393 22
7433 40
7449 16
7451 2
7467 16
7468 1
7474 6
7475 1
7477 2
7480 3
7481 1
7488 7
7499 11
7551 52
7585 34
7622 37
7698 76
7820 122
7850 30
7851 1
7852 1
7853 1
7854 1
7855 1
7856 1
7857 1
7858 1
7859 1
7878 19
7903 25
7906 3
7958 52
8002 44
8010 8
8019 9
8064 45
8065 1
8068 3
8073 5
8114 41
8116 2
8142 26
8170 28
8174 4
8175 1
8183 8
8201 18
8219 18
8234 15
8236 2
8340 104
8346 6
8347 1
8435 88
8593 158
8594 1
8637 43
8666 29
8690 24
8742 52
8750 8
8767 17
8768 1
8769 1
8770 1
8771 1
8772 1
8773 1
8774 1
8775 1
8776 1
8777 1
8778 1
8779 1
8780 1
8781 1
8782 1
8783 1
8784 1
8785 1
8786 1
8787 1
8788 1
8789 1
8790 1
8791 1
8792 1
8793 1
8794 1
8795 1
8796 1
8797 1
8798 1
8799 1
8800 1
8801 1
8802 1
8803 1
8804 1
8805 1
8806 1
8807 1
8808 1
8809 1
8810 1
8811 1
8812 1
8813 1
8814 1
8815 1
8816 1
8817 1
8818 1
8819 1
8820 1
8821 1
8822 1
8823 1
8824 1
8825 1
8826 1
8827 1
8828 1
8829 1
8830 1
8831 1
8832 1
8833 1
8834 1
8835 1
8836 1
8837 1
8838 1
8839 1
8840 1
8841 1
8842 1
8843 1
8844 1
8845 1
8846 1
8847 1
8848 1
8849 1
8850 1
8851 1
8852 1
8853 1
8854 1
8855 1
8856 1
8857 1
8858 1
8859 1
8860 1
8861 1
8862 1
8863 1
8864 1
8865 1
8866 1
8867 1
8868 1
8869 1
8870 1
8871 1
8872 1
8873 1
8874 1
8875 1
8876 1
8877 1
8878 1
8879 1
8880 1
8881 1
8882 1
8883 1
8884 1
8885 1
8886 1
8887 1
8888 1
8889 1
8890 1
8891 1
8892 1
8893 1
8894 1
8895 1
8896 1
8897 1
8898 1
8899 1
8900 1
8901 1
8902 1
8903 1
8904 1
8905 1
8906 1
8907 1
8908 1
8909 1
8910 1
8911 1
8912 1
8913 1
8914 1
8915 1
8916 1
8917 1
8918 1
8919 1
8920 1
8921 1
8922 1
8923 1
8924 1
8925 1
8926 1
8927 1
8928 1
8929 1
8930 1
8931 1
8932 1
8933 1
8934 1
8935 1
8936 1
8937 1
8938 1
8939 1
8940 1
8941 1
8942 1
8943 1
8944 1
8945 1
8946 1
8947 1
8948 1
8949 1
8950 1
8951 1
8952 1
8953 1
8954 1
8955 1
8956 1
8957 1
8958 1
8959 1
8960 1
8961 1
8962 1
8963 1
8964 1
8965 1
8966 1
8967 1
8968 1
8969 1
8970 1
8971 1
8972 1
8973 1
8974 1
8975 1
8976 1
8977 1
8978 1
8979 1
8980 1
8981 1
8982 1
8983 1
8984 1
8985 1
8986 1
8987 1
8988 1
8989 1
8990 1
8991 1
8992 1
8993 1
8994 1
8995 1
8996 1
8997 1
8998 1
8999 1
9000 1
9001 1
9002 1
9003 1
9004 1
9005 1
9006 1
9007 1
9008 1
9009 1
9010 1
9011 1
9012 1
9013 1
9014 1
9015 1
9016 1
9017 1
9018 1
9019 1
9020 1
9021 1
9022 1
9023 1
9024 1
9025 1
9026 1
9027 1
9028 1
9029 1
9030 1
9031 1
9032 1
9033 1
9034 1
9035 1
9036 1
9037 1
9038 1
9039 1
9040 1
9041 1
9042 1
9043 1
9044 1
9045 1
9046 1
9047 1
9048 1
9049 1
9050 1
9051 1
9052 1
9053 1
9054 1
9055 1
9056 1
9057 1
9058 1
9059 1
9060 1
9061 1
9062 1
9063 1
9064 1
9065 1
9066 1
9067 1
9068 1
9069 1
9070 1
9071 1
9072 1
9073 1
9074 1
9075 1
9076 1
9077 1
9078 1
9079 1
9080 1
9081 1
9082 1
9083 1
9084 1
9085 1
9086 1
9087 1
9088 1
9089 1
9090 1
9091 1
9092 1
9093 1
9094 1
9095 1
9096 1
9097 1
9098 1
9099 1
9100 1
9101 1
9102 1
9103 1
9104 1
9105 1
9106 1
9107 1
9108 1
9109 1
9110 1
9111 1
9112 1
9113 1
9114 1
9115 1
9116 1
9117 1
9118 1
9119 1
9120 1
9121 1
9122 1
9123 1
9124 1
9125 1
9126 1
9127 1
9128 1
9129 1
9130 1
9131 1
9132 1
9133 1
9134 1
9135 1
9136 1
9137 1
9138 1
9139 1
9140 1
9141 1
9142 1
9143 1
9144 1
9145 1
9146 1
9147 1
9148 1
9149 1
9150 1
9151 1
9152 1
9153 1
9154 1
9155 1
9156 1
9157 1
9158 1
9159 1
9160 1
9161 1
9162 1
9163 1
9164 1
9165 1
9166 1
9167 1
9168 1
9169 1
9170 1
9171 1
9172 1
9173 1
9174 1
9175 1
9176 1
9177 1
9178 1
9179 1
9180 1
9181 1
9182 1
9183 1
9184 1
9185 1
9186 1
9187 1
9188 1
9189 1
9190 1
9191 1
9192 1
9193 1
9194 1
9195 1
9196 1
9197 1
9198 1
9199 1
9200 1
9201 1
9202 1
9203 1
9204 1
9205 1
9206 1
9207 1
9208 1
9209 1
9210 1
9211 1
9212 1
9213 1
9214 1
9215 1
9216 1
9217 1
9218 1
9219 1
9220 1
9221 1
9222 1
9223 1
9224 1
9225 1
9226 1
9227 1
9228 1
9229 1
9230 1
9231 1
9232 1
9233 1
9234 1
9235 1
9236 1
9237 1
9238 1
9239 1
9240 1
9241 1
9242 1
9243 1
9244 1
9245 1
9246 1
9247 1
9248 1
9249 1
9250 1
9251 1
9252 1
9253 1
9254 1
9255 1
9256 1
9257 1
9258 1
9259 1
9260 1
9261 1
9262 1
9263 1
9264 1
9265 1
9266 1
9267 1
9268 1
9269 1
9270 1
9271 1
9272 1
9273 1
9274 1
9275 1
9276 1
9277 1
9278 1
9279 1
9280 1
9281 1
9282 1
9283 1
9284 1
9285 1
9286 1
9287 1
9288 1
9289 1
9290 1
9291 1
9292 1
9293 1
9294 1
9295 1
9296 1
9297 1
9298 1
9299 1
9300 1
9301 1
9302 1
9303 1
9304 1
9305 1
9306 1
9307 1
9308 1
9309 1
9310 1
9311 1
9312 1
9313 1
9314 1
9315 1
9316 1
9317 1
9318 1
9319 1
9320 1
9321 1
9322 1
9323 1
9324 1
9325 1
9326 1
9327 1
9328 1
9329 1
9330 1
9331 1
9332 1
9333 1
9334 1
9335 1
9336 1
9337 1
9338 1
9339 1
9340 1
9341 1
9342 1
9343 1
9344 1
9345 1
9346 1
9347 1
9348 1
9349 1
9350 1
9351 1
9352 1
9353 1
9354 1
9355 1
9356 1
9357 1
9358 1
9359 1
9360 1
9361 1
9362 1
9363 1
9364 1
9365 1
9366 1
9367 1
9368 1
9369 1
9370 1
9371 1
9372 1
9373 1
9374 1
9375 1
9376 1
9377 1
9378 1
9379 1
9380 1
9381 1
9382 1
9383 1
9384 1
9385 1
9386 1
9387 1
9388 1
9389 1
9390 1
9391 1
9392 1
9393 1
9394 1
9395 1
9396 1
9397 1
9398 1
9399 1
9400 1
9401 1
9402 1
9403 1
9404 1
9405 1
9406 1
9407 1
9408 1
9409 1
9410 1
9411 1
9412 1
9413 1
9414 1
9415 1
9416 1
9417 1
9418 1
9419 1
9420 1
9421 1
9422 1
9423 1
9424 1
9425 1
9426 1
9427 1
9428 1
9429 1
9430 1
9431 1
9432 1
9433 1
9434 1
9435 1
9436 1
9437 1
9438 1
9439 1
9440 1
9441 1
9442 1
9443 1
9444 1
9445 1
9446 1
9447 1
9448 1
9449 1
9450 1
9451 1
9452 1
9453 1
9454 1
9455 1
9456 1
9457 1
9458 1
9459 1
9460 1
9461 1
9462 1
9463 1
9464 1
9465 1
9466 1
9467 1
9468 1
9469 1
9470 1
9471 1
9472 1
9473 1
9474 1
9475 1
9476 1
9477 1
9478 1
9479 1
9480 1
9481 1
9482 1
9483 1
9484 1
9485 1
9486 1
9487 1
9488 1
9489 1
9490 1
9491 1
9492 1
9493 1
9494 1
9495 1
9496 1
9497 1
9498 1
9499 1
9500 1
9501 1
9502 1
9503 1
9504 1
9505 1
9506 1
9507 1
9508 1
9509 1
9510 1
9511 1
9512 1
9513 1
9514 1
9515 1
9516 1
9517 1
9518 1
9519 1
9520 1
9521 1
9522 1
9523 1
9524 1
9525 1
9526 1
9527 1
9528 1
9529 1
9530 1
9531 1
9532 1
9533 1
9534 1
9535 1
9536 1
9537 1
9538 1
9539 1
9540 1
9541 1
9542 1
9543 1
9544 1
9545 1
9546 1
9547 1
9548 1
9549 1
9550 1
9551 1
9552 1
9553 1
9554 1
9555 1
9556 1
9557 1
9558 1
9559 1
9560 1
9561 1
9562 1
9563 1
9564 1
9565 1
9566 1
9567 1
9568 1
9569 1
9570 1
9571 1
9572 1
9573 1
9574 1
9575 1
9576 1
9577 1
9578 1
9579 1
9580 1
9581 1
9582 1
9583 1
9584 1
9585 1
9586 1
9587 1
9588 1
9589 1
9590 1
9591 1
9592 1
9593 1
9594 1
9595 1
9596 1
9597 1
9598 1
9599 1
9600 1
9601 1
9602 1
9603 1
9604 1
9605 1
9606 1
9607 1
9608 1
9609 1
9610 1
9611 1
9612 1
9613 1
9614 1
9615 1
9616 1
9617 1
9618 1
9619 1
9620 1
9621 1
9622 1
9623 1
9624 1
9625 1
9626 1
9627 1
9628 1
9629 1
9630 1
9631 1
9632 1
9633 1
9634 1
9635 1
9636 1
9637 1
9638 1
9639 1
9640 1
9641 1
9642 1
9643 1
9644 1
9645 1
9646 1
9647 1
9648 1
9649 1
9650 1
9651 1
9652 1
9653 1
9654 1
9655 1
9656 1
9657 1
9658 1
9659 1
9660 1
9661 1
9662 1
9663 1
9664 1
9665 1
9666 1
9667 1
9668 1
9669 1
9670 1
9671 1
9672 1
9673 1
9674 1
9675 1
9676 1
9677 1
9678 1
9679 1
9680 1
9681 1
9682 1
9683 1
9684 1
9685 1
9686 1
9687 1
9688 1
9689 1
9690 1
9691 1
9692 1
9693 1
9694 1
9695 1
9696 1
9697 1
9698 1
9699 1
9700 1
9701 1
9702 1
9703 1
9704 1
9705 1
9706 1
9707 1
9708 1
9709 1
9710 1
9711 1
9712 1
9713 1
9714 1
9715 1
9716 1
9717 1
9718 1
9719 1
9720 1
9721 1
9722 1
9723 1
9724 1
9725 1
9726 1
9727 1
9728 1
9729 1
9730 1
9731 1
9732 1
9733 1
9734 1
9735 1
9736 1
9737 1
9738 1
9739 1
9740 1
9741 1
9742 1
9743 1
9744 1
9745 1
9746 1
9747 1
9748 1
9749 1
9750 1
9751 1
9752 1
9753 1
9754 1
9755 1
9756 1
9757 1
9758 1
9759 1
9760 1
9761 1
9762 1
9763 1
9764 1
9765 1
9766 1
9767 1
9768 1
9769 1
9770 1
9771 1
9772 1
9773 1
9774 1
9775 1
9776 1
9777 1
9778 1
9779 1
9780 1
9781 1
9782 1
9783 1
9784 1
9785 1
9786 1
9787 1
9788 1
9789 1
9790 1
9791 1
9792 1
9793 1
9794 1
9795 1
9796 1
9797 1
9798 1
9799 1
9800 1
9801 1
9802 1
9803 1
9804 1
9805 1
9806 1
9807 1
9808 1
9809 1
9810 1
9811 1
9812 1
9813 1
9814 1
9815 1
9816 1
9817 1
9818 1
9819 1
9820 1
9821 1
9822 1
9823 1
9824 1
9825 1
9826 1
9827 1
9828 1
9829 1
9830 1
9831 1
9832 1
9833 1
9834 1
9835 1
9836 1
9837 1
9838 1
9839 1
9840 1
9841 1
9842 1
9843 1
9844 1
9845 1
9846 1
9847 1
9848 1
9849 1
9850 1
9851 1
9852 1
9853 1
9854 1
9855 1
9856 1
9857 1
9858 1
9859 1
9860 1
9861 1
9862 1
9863 1
9864 1
9865 1
9866 1
9867 1
9868 1
9869 1
9870 1
9871 1
9872 1
9873 1
9874 1
9875 1
9876 1
9877 1
9878 1
9879 1
9880 1
9881 1
9882 1
9883 1
9884 1
9885 1
9886 1
9887 1
9888 1
9889 1
9890 1
9891 1
9892 1
9893 1
9894 1
9895 1
9896 1
9897 1
9898 1
9899 1
9900 1
9901 1
9902 1
9903 1
9904 1
9905 1
9906 1
9907 1
9908 1
9909 1
9910 1
9911 1
9912 1
9913 1
9914 1
9915 1
9916 1
9917 1
9918 1
9919 1
9920 1
9921 1
9922 1
9923 1
9924 1
9925 1
9926 1
9927 1
9928 1
9929 1
9930 1
9931 1
9932 1
9933 1
9934 1
9935 1
9936 1
9937 1
9938 1
9939 1
9940 1
9941 1
9942 1
9943 1
9944 1
9945 1
9946 1
9947 1
9948 1
9949 1
9950 1
9951 1
9952 1
9953 1
9954 1
9955 1
9956 1
9957 1
9958 1
9959 1
9960 1
9961 1
9962 1
9963 1
9964 1
9965 1
9966 1
9967 1
9968 1
9969 1
9970 1
9971 1
9972 1
9973 1
9974 1
9975 1
9976 1
9977 1
9978 1
9979 1
9980 1
9981 1
9982 1
9983 1
9984 1
9985 1
9986 1
9987 1
9988 1
9989 1
9990 1
9991 1
9992 1
9993 1
9994 1
9995 1
9996 1
9997 1
9998 1
9999 1
10000 1
10001 1
10002 1
10003 1
10004 1
10005 1
10006 1
10007 1
10008 1
10009 1
10010 1
10011 1
10012 1
10013 1
10014 1
10015 1
10016 1
10017 1
10018 1
10019 1
10020 1
10021 1
10022 1
10023 1
10024 1
10025 1
10026 1
10027 1
10028 1
10029 1
10030 1
10031 1
10032 1
10033 1
10034 1
10035 1
10036 1
10037 1
10038 1
10039 1
10040 1
10041 1
10042 1
10043 1
10044 1
10045 1
10046 1
10047 1
10048 1
10049 1
10050 1
10051 1
10052 1
10053 1
10054 1
10055 1
10056 1
10057 1
10068 11
10107 39
10130 23
10143 13
10175 32
10181 6
10196 15
10220 24
10221 1
10222 1
10242 20
10256 14
10279 23
10410 131
10469 59
10471 2
10562 91
10646 84
10679 33
10723 44
10812 89
10813 1
10814 1
10815 1
10816 1
10817 1
10818 1
10819 1
10820 1
10821 1
10822 1
10824 2
10825 1
10826 1
10827 1
10828 1
10829 1
10830 1
10831 1
10832 1
10833 1
10834 1
10835 1
10836 1
10837 1
10838 1
10839 1
10840 1
10841 1
10842 1
10843 1
10844 1
10845 1
10846 1
10847 1
10848 1
10849 1
10850 1
10851 1
10852 1
10853 1
10854 1
10855 1
10856 1
10857 1
10858 1
10859 1
10860 1
10861 1
10862 1
10863 1
10864 1
10865 1
10866 1
10867 1
10868 1
10869 1
10870 1
10871 1
10872 1
10873 1
10874 1
10875 1
10876 1
10877 1
10878 1
10879 1
10880 1
10881 1
10882 1
10883 1
10884 1
10885 1
10886 1
10887 1
10888 1
10889 1
10890 1
10891 1
10892 1
10893 1
10894 1
10895 1
10896 1
10897 1
10898 1
10899 1
10900 1
10901 1
10902 1
10903 1
10904 1
10905 1
10906 1
10907 1
10908 1
10909 1
10910 1
10911 1
10912 1
10913 1
10914 1
10915 1
10916 1
10917 1
10918 1
10919 1
10920 1
10921 1
10922 1
10923 1
10924 1
10925 1
10926 1
10927 1
10928 1
10929 1
10930 1
10931 1
10932 1
10933 1
10934 1
10935 1
10936 1
10937 1
10938 1
10939 1
10940 1
10941 1
10942 1
10943 1
10944 1
10945 1
10946 1
10947 1
10948 1
10949 1
10950 1
10951 1
10952 1
10953 1
10954 1
10955 1
10956 1
10957 1
10958 1
10959 1
10960 1
10961 1
10962 1
10963 1
10964 1
10965 1
10966 1
10967 1
10968 1
10969 1
10970 1
10971 1
10972 1
10973 1
10974 1
10975 1
10976 1
10977 1
10978 1
10979 1
10980 1
10981 1
10982 1
10983 1
10984 1
10985 1
10986 1
10987 1
10988 1
10989 1
10990 1
10991 1
10992 1
10993 1
10994 1
10995 1
10996 1
10997 1
10998 1
10999 1
11000 1
11001 1
11002 1
11003 1
11004 1
11005 1
11006 1
11007 1
11008 1
11009 1
11010 1
11011 1
11012 1
11013 1
11014 1
11015 1
11016 1
11017 1
11018 1
11019 1
11020 1
11021 1
11022 1
11023 1
11024 1
11025 1
11026 1
11027 1
11028 1
11029 1
11030 1
11031 1
11032 1
11033 1
11034 1
11035 1
11036 1
11037 1
11038 1
11039 1
11040 1
11041 1
11042 1
11043 1
11044 1
11045 1
11046 1
11047 1
11048 1
11049 1
11050 1
11051 1
11052 1
11053 1
11054 1
11055 1
11056 1
11057 1
11058 1
11059 1
11060 1
11061 1
11062 1
11063 1
11064 1
11065 1
11066 1
11067 1
11068 1
11069 1
11070 1
11071 1
11072 1
11073 1
11074 1
11075 1
11076 1
11077 1
11078 1
11079 1
11080 1
11081 1
11082 1
11083 1
11084 1
11085 1
11086 1
11087 1
11088 1
11089 1
11090 1
11091 1
11092 1
11093 1
11094 1
11095 1
11096 1
11097 1
11098 1
11099 1
11100 1
11101 1
11102 1
11103 1
11104 1
11105 1
11106 1
11107 1
11108 1
11109 1
11110 1
11111 1
11112 1
11113 1
11114 1
11115 1
11116 1
11117 1
11118 1
11119 1
11120 1
11121 1
11122 1
11123 1
11124 1
11125 1
11126 1
11127 1
11128 1
11129 1
11130 1
11131 1
11132 1
11133 1
11134 1
11135 1
11136 1
11137 1
11138 1
11139 1
11140 1
11141 1
11142 1
11143 1
11144 1
11145 1
11146 1
11147 1
11148 1
11149 1
11150 1
11151 1
11152 1
11153 1
11154 1
11155 1
11156 1
11157 1
11158 1
11159 1
11160 1
11161 1
11162 1
11163 1
11164 1
11165 1
11166 1
11167 1
11168 1
11169 1
11170 1
11171 1
11172 1
11173 1
11174 1
11175 1
11176 1
11177 1
11178 1
11179 1
11180 1
11181 1
11182 1
11183 1
11184 1
11185 1
11186 1
11187 1
11188 1
11189 1
11190 1
11191 1
11192 1
11193 1
11194 1
11195 1
11196 1
11197 1
11198 1
11199 1
11200 1
11201 1
11202 1
11203 1
11204 1
11205 1
11206 1
11207 1
11208 1
11209 1
11210 1
11211 1
11212 1
11213 1
11214 1
11215 1
11216 1
11217 1
11218 1
11219 1
11220 1
11221 1
11222 1
11223 1
11224 1
11225 1
11226 1
11227 1
11228 1
11229 1
11230 1
11231 1
11232 1
11233 1
11234 1
11235 1
11236 1
11237 1
11238 1
11239 1
11240 1
11241 1
11242 1
11243 1
11244 1
11245 1
11246 1
11247 1
11248 1
11249 1
11250 1
11251 1
11252 1
11253 1
11254 1
11255 1
11256 1
11257 1
11258 1
11259 1
11260 1
11261 1
11262 1
11263 1
11264 1
11265 1
11266 1
11267 1
11268 1
11269 1
11270 1
11271 1
11272 1
11273 1
11274 1
11275 1
11276 1
11277 1
11278 1
11279 1
11280 1
11281 1
11282 1
11283 1
11284 1
11285 1
11286 1
11287 1
11288 1
11289 1
11290 1
11291 1
11292 1
11293 1
11294 1
11295 1
11296 1
11297 1
11298 1
11299 1
11300 1
11301 1
11302 1
11303 1
11304 1
11305 1
11306 1
11307 1
11308 1
11309 1
11310 1
11311 1
11312 1
11313 1
11314 1
11315 1
11316 1
11317 1
11318 1
11319 1
11320 1
11321 1
11322 1
11323 1
11324 1
11325 1
11326 1
11327 1
11328 1
11329 1
11330 1
11331 1
11332 1
11333 1
11334 1
11335 1
11336 1
11337 1
11338 1
11339 1
11340 1
11341 1
11342 1
11343 1
11344 1
11345 1
11346 1
11347 1
11348 1
11349 1
11350 1
11351 1
11352 1
11353 1
11354 1
11355 1
11356 1
11357 1
11358 1
11359 1
11360 1
11361 1
11362 1
11363 1
11364 1
11365 1
11366 1
11367 1
11368 1
11369 1
11370 1
11371 1
11372 1
11373 1
11374 1
11375 1
11376 1
11377 1
11378 1
11379 1
11380 1
11381 1
11382 1
11383 1
11384 1
11385 1
11386 1
11387 1
11388 1
11389 1
11390 1
11391 1
11392 1
11393 1
11394 1
11395 1
11396 1
11397 1
11398 1
11399 1
11400 1
11401 1
11402 1
11403 1
11404 1
11405 1
11406 1
11407 1
11408 1
11409 1
11410 1
11411 1
11412 1
11413 1
11414 1
11415 1
11416 1
11417 1
11418 1
11419 1
11420 1
11421 1
11422 1
11423 1
11424 1
11425 1
11426 1
11427 1
11428 1
11429 1
11430 1
11431 1
11432 1
11433 1
11434 1
11435 1
11436 1
11437 1
11438 1
11439 1
11440 1
11441 1
11442 1
11443 1
11444 1
11445 1
11446 1
11447 1
11448 1
11449 1
11450 1
11451 1
11452 1
11453 1
11454 1
11455 1
11456 1
11457 1
11458 1
11459 1
11460 1
11461 1
11462 1
11463 1
11464 1
11465 1
11466 1
11467 1
11468 1
11469 1
11470 1
11471 1
11472 1
11473 1
11474 1
11475 1
11476 1
11477 1
11478 1
11479 1
11480 1
11481 1
11482 1
11483 1
11484 1
11485 1
11486 1
11487 1
11488 1
11489 1
11490 1
11491 1
11492 1
11493 1
11494 1
11495 1
11496 1
11497 1
11498 1
11499 1
11500 1
11501 1
11502 1
11503 1
11504 1
11505 1
11506 1
11507 1
11508 1
11509 1
11510 1
11511 1
11512 1
11513 1
11514 1
11515 1
11516 1
11517 1
11518 1
11519 1
11520 1
11521 1
11522 1
11523 1
11524 1
11525 1
11526 1
11527 1
11528 1
11529 1
11530 1
11531 1
11532 1
11533 1
11534 1
11535 1
11536 1
11537 1
11538 1
11539 1
11540 1
11541 1
11542 1
11543 1
11544 1
11545 1
11546 1
11547 1
11548 1
11549 1
11550 1
11551 1
11552 1
11553 1
11554 1
11555 1
11556 1
11557 1
11558 1
11559 1
11560 1
11561 1
11562 1
11563 1
11564 1
11565 1
11566 1
11567 1
11568 1
11569 1
11570 1
11571 1
11572 1
11573 1
11574 1
11575 1
11576 1
11577 1
11578 1
11579 1
11580 1
11581 1
11582 1
11583 1
11584 1
11585 1
11586 1
11587 1
11588 1
11589 1
11590 1
11591 1
11592 1
11593 1
11594 1
11595 1
11596 1
11597 1
11598 1
11599 1
11600 1
11601 1
11602 1
11603 1
11604 1
11605 1
11606 1
11607 1
11608 1
11609 1
11610 1
11611 1
11612 1
11613 1
11614 1
11615 1
11616 1
11617 1
11618 1
11619 1
11620 1
11621 1
11622 1
11623 1
11624 1
11625 1
11626 1
11627 1
11628 1
11629 1
11630 1
11631 1
11632 1
11633 1
11634 1
11635 1
11636 1
11637 1
11638 1
11639 1
11640 1
11641 1
11642 1
11643 1
11644 1
11645 1
11646 1
11647 1
11648 1
11649 1
11650 1
11651 1
11652 1
11653 1
11654 1
11655 1
11656 1
11657 1
11658 1
11659 1
11660 1
11661 1
11662 1
11663 1
11664 1
11665 1
11666 1
11667 1
11668 1
11669 1
11670 1
11671 1
11672 1
11673 1
11674 1
11675 1
11676 1
11677 1
11678 1
11679 1
11680 1
11681 1
11682 1
11683 1
11684 1
11685 1
11686 1
11687 1
11688 1
11689 1
11690 1
11691 1
11692 1
11693 1
11694 1
11695 1
11696 1
11697 1
11698 1
11699 1
11700 1
11701 1
11702 1
11703 1
11704 1
11705 1
11706 1
11707 1
11708 1
11709 1
11710 1
11711 1
11712 1
11713 1
11714 1
11715 1
11716 1
11717 1
11718 1
11719 1
11720 1
11721 1
11722 1
11723 1
11724 1
11725 1
11726 1
11727 1
11728 1
11729 1
11730 1
11731 1
11732 1
11733 1
11734 1
11735 1
11736 1
11737 1
11738 1
11739 1
11740 1
11741 1
11742 1
11743 1
11744 1
11745 1
11746 1
11747 1
11748 1
11749 1
11750 1
11751 1
11752 1
11753 1
11754 1
11755 1
11756 1
11757 1
11758 1
11760 2
11761 1
11762 1
11763 1
11764 1
11765 1
11766 1
11767 1
11768 1
11769 1
11770 1
11771 1
11772 1
11773 1
11774 1
11775 1
11776 1
11777 1
11778 1
11779 1
11780 1
11781 1
11782 1
11783 1
11784 1
11785 1
11786 1
11787 1
11788 1
11789 1
11790 1

In [310]:
cldata[cldata.SIFCODE == '0016']

,RWCOMPKEY,RWCOMPKEYPARENT,LOW_ADDRESS,FROM_ADDRESS,TO_ADDRESS,LFROM,LTO,RFROM,RTO,SIFID,...,ALIAS2_TYPE,ALIAS2_SIFID,ALIAS3_DIR,ALIAS3_STRNAME,ALIAS3_TYPE,ALIAS3_SIFID,ALIAS4_DIR,ALIAS4_STRNAME,ALIAS4_TYPE,ALIAS4_SIFID
OBJECTID,,,,,,,,,,,,,,,,,,,,,
9689,15336,0,100,100,113,100,112,101,113,16,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
12620,20101,0,390,390,399,390,398,391,399,16,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
18362,15293,0,114,114,127,114,126,115,127,16,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
18779,15243,0,128,128,129,128,128,129,129,16,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
31141,15231,0,130,130,209,130,208,131,209,16,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
97009,15189,0,210,210,299,210,298,211,299,16,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0
160069,20098,0,300,300,389,300,388,301,389,16,...,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN,0

In [199]:
coordinate_pattern = re_compile("(-?[0-9]+\.[0-9]+),(-?[0-9]+\.[0-9]+)")
    
def string_to_coordinates(string):
    out = list()
    for longitude, latitude in coordinate_pattern.findall(string):
        out.append((float(longitude), float(latitude)))
    return out


def get_box_from_points(coordinates):
    longitude_min = float('inf')
    longitude_max = -float('inf')
    latitude_min = float('inf')
    latitude_max = -float('inf')
    # The default is set to +/- infinity to ensure that the 
    for longitude, latitude in coordinates:
        if longitude < longitude_min:
            longitude_min = longitude
        if longitude > longitude_max:
            longitude_max = longitude
        if latitude < latitude_min:
            latitude_min = latitude
        if latitude > latitude_max:
            latitude_max = latitude 
    return {'longitude_min':longitude_min, 'longitude_max':longitude_max,
            'latitude_min':latitude_min, 'latitude_max':latitude_max}

In [206]:
parsed_coordinates = CO.COORDINATES.apply(string_to_coordinates)

In [201]:
get_box_from_points(parsed_coordinates[2])

{'longitude_min': -85.8013692697861,
 'longitude_max': -85.8012012237063,
 'latitude_min': 38.2293433595089,
 'latitude_max': 38.2305637930331}

In [202]:

boxes = CO.COORDINATES.apply(string_to_coordinates).apply(get_box_from_points)
boxes = pd.DataFrame.from_records(boxes.values)
boxes['OBJECTID'] = CO.index
boxes = boxes.set_index('OBJECTID')
boxes

          longitude_min  longitude_max  latitude_min  latitude_max
OBJECTID
1            -85.681235     -85.680950     38.158161     38.158867
2            -85.801369     -85.801201     38.229343     38.230564
3            -85.805015     -85.804692     38.227538     38.228933
4            -85.680205     -85.679863     38.247608     38.248067
5            -85.742040     -85.741648     38.211815     38.211969
...                 ...            ...           ...           ...
172237       -85.569499     -85.568968     38.334101     38.334777
172238       -85.568968     -85.568469     38.333488     38.334101
172239       -85.813102     -85.812529     38.261615     38.262190
172240       -85.761629     -85.761182     38.218800     38.220560
172545       -85.763058     -85.762272     38.219393     38.219482

[34874 rows x 4 columns]

In [226]:
from math import floor
from random import randrange

long_min = boxes.longitude_min.min()
long_max = boxes.longitude_max.max()
lat_min = boxes.latitude_min.min()
lat_max = boxes.latitude_max.max()

long_span = long_max - long_min
lat_span = lat_max - lat_min

def convert_long(longitude, precision=16):
    return floor(((longitude - long_min)/long_span) * (2 ** (precision)))

def convert_lat(latitude, precision=16):
    return floor(((latitude - lat_min)/lat_span) * (2 ** (precision)))

def convert_coordinate(coordinate, precision=16):
    longitude, latitude = coordinate
    longitude = (longitude - long_min)/long_span
    longitude *= 2 ** precision
    latitude = (latitude - lat_min)/lat_span
    latitude *= 2 ** precision
    return floor(longitude), floor(latitude)

In [231]:

def make_coordinate_converter(precision=16):
    denominator = 2 ** precision
    def convert_coordinates(coordinate_list):
        out = list()
        for longitude, latitude in coordinate_list:
            longitude = (longitude - long_min)/long_span
            latitude = (latitude - lat_min)/lat_span
            out.append( (floor(longitude * denominator), floor(latitude * denominator)) )
        return out
    return convert_coordinates


cc = coordinate_converter(20)
CO = parsed_coordinates
CO.apply(cc)

cc(CO[172239])

[(228900, 728603),
 (228842, 727817),
 (228838, 727793),
 (228831, 727771),
 (228822, 727751),
 (228812, 727733),
 (228799, 727718),
 (228785, 727707),
 (228771, 727699),
 (228301, 727769),
 (228211, 727777),
 (228122, 727786),
 (228087, 727786),
 (228054, 727777),
 (228021, 727758),
 (227992, 727732),
 (227965, 727698),
 (227890, 727001)]

In [224]:

MID = (long_min + long_max)/2

gt_half = boxes[boxes.longitude_max > MID]
gt_less = boxes[boxes.longitude_max <= MID]

In [223]:

def splitter(value):
    def compare(minimum, maximum):
        if maximum < value:
            return "<"
        elif minimum > value:
            return ">"
        else:
            return "~"
    return compare

f=splitter(mid)

sp = boxes.longitude_min.combine(boxes.longitude_max, f)

sp.value_counts()[1]/2/2/2/2/2/2/2/2/2/2

/var/folders/7s/9_9p_dsj0n9581txqt_9rrpc0000gn/T/ipykernel_8690/2595208648.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sp.value_counts()[1]/2/2/2/2/2/2/2/2/2/2

np.float64(14.701171875)

In [222]:
def get_brackets(start, stop, steps=10):
    span = stop - start
    return [1 + ((n/steps) * span) for n in range(1, steps+1)]
    

get_brackets(1, 2, 10)

[1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0]

In [221]:
def slots(low, hi, steps):
    if steps < 0:
        raise ValueError(f"steps must be > 0. Got {steps}")
    elif steps == 0:
        return [low, hi]
    else:
        cut = (low + hi)/2
        memo = [low, cut]
        steps -= 1
        back = 2
        while steps:
            ...