# Data dictionary 

| alias | data type | description | notes |
|-------|-----------|-------------|-------|
| OBJECTID | OID | Internal feature number.; Description source; ESRI; Description of values Sequential unique whole numbers that are automatically generated. ||
| SIFCODE | String | Street code number from the Metro Street Index File (SIF) table ||
| LOW_ADDRESS | String | Lowest address number within a centerline segment.  This could differ from FROM_ADDRESS because a FROM_ADDRESS number could be the highest number within the range but the location is at the starting segment of a one way street. ||
| UNITID2 | String | Unique identifier for Midas asset management system ||
| FROM_ADDRESS | Integer | Beginning address for centerline segment ||
| TO_ADDRESS | Integer | Ending address for centerline segment ||
| LFROM | Integer | From house number for left side of street ||
| LTO | Integer | To house number for left side of street ||
| RFROM | Integer | From house number for right side of street ||
| RTO | Integer | To house number for right side of street ||
|||||
| LENGTH | Double | Length of the segment in feet; duplication of Shape.Length column due to ArcGIS software limitation ||
| see notes | Geometry | Feature geometry.; * Description source; ESRI; * Description of values Coordinates defining the features. ||
| SHAPELEN | Double | Length of line segment in feet; Description source; ESRI ||
|||||
| RWCOMPKEY | Integer | Unique Identifier for each arc feature in Midas asset management system ||
| RWCOMPKEYPARENT | Integer | Previous RWCompKey number ||
|||||
| AVDIR | String | Street direction (N, S, E, W); used for creating geocoding indexes ||
| AVPRETYPE | String | Pre Street Type (ie. USHY, BLVD, PL, AVE);  used for creating geocoding indexes ||
| AVSTNAME | String | Street Name; used for creating geocoding indexes ||
| COMPTYPE | Integer | Unique identifier for Midas asset management system ||
| AVSTTYPE | String | Street Type; used for creating geocoding indexes ||
| AVSUFDIR | String | Street Suffix Direction; used for creating geocoding indexes ||
|||||
| LOCROSSSIF | String | Sifcode of the low cross street ||
| HICROSSSIF | String | Sifcode of the high cross street ||
| SIFIDLOW | Integer | Integer Street Index File number of lower cross street ||
| SIFIDHI | Integer | Integer Street Index File number of higher cross street ||
|||||
| LOCROSSPR | String | Prefix Name of Cross Street on Low address end of street segment. ||
| LOCROSSNA | String | Name of cross street on Low address end of street segment. ||
| LOCROSSSU | String | Suffix name of cross street on low address end of street segment. ||
| HICROSSPR | String | Prefix name of cross street on high address end of street segment. ||
| HICROSSNA | String | Name of cross street on high address end of street segment ||
| HICROSSSU | String | Suffix name of cross street on high address end of street segment.; Description of values Sequential unique whole numbers that are automatically generated. ||
|||||
| SIFID | Integer | Integer Street Index File number; alternate to SIFCODE ||
| ROADNAME | String | Street direction, name, type and suffix direction ||
| DIR | String | Direction; N, S, E, W ||
| STRNAME | String | Street name ||
| TYPE | String | Street type; ie. AVE, RD, ST, etal. ||
|||||
| CORE_CLASS | String | Street class from Metro Louisville Comp Plan; List of values; Expressway	Expressway Street Class from Metro Louisville Comp Plan; Interstate Ramps	Interstate Ramps Street Class from Metro Louisville Comp Plan; Major Arterial	Major Arterial Street Class from Metro Louisville Comp Plan; Minor Arterial	Minor Arterial Street Class from Metro Louisville Comp Plan; Primary Collector	Primary Collector Street Class from Metro Louisville Comp Plan; Secondary Collector	Secondary Collector Street Class from Metro Louisville Comp Plan; Local	Local Street Class from Metro Louisville Comp Plan; Pedestrian Walkways	Pedestrian Walkways Street Class from Metro Louisville Comp Plan; Unclassified	Unclassified Street Class from Metro Louisville Comp Plan ||
| STCL_CLASS | SmallInteger | Street class; Description source; Metro Public Works; List of values; 1	Expressway; 2	Interstate Ramp; 3	Major Arterial; 4	Minor Aterial; 5	Primary Collector; 6	Secondary Collector; 7	Local; 8	Pedestrian Walkway; 9	Response Route; 99	Inactive ||
 CLASS_ABRV | String | Street class abreviation ||
|||||
| ZIP_LEFT | Integer | Zip Code of left side of street ||
| ZIP_RIGHT | Integer | Zip Code of right side of street ||
| COMPKEY | Integer | Unique identifier for Midas asset management system ||
| UNITID | String | Unique identifier for Midas asset management system ||
|||||
| ALIAS1_DIR | String |  ||
| ALIAS1_STRNAME | String |  ||
| ALIAS1_TYPE | String |  ||
| ALIAS1_SIFID | Double |  ||
| ALIAS2_DIR | String |  ||
| ALIAS2_STRNAME | String |  ||
| ALIAS2_TYPE | String |  ||
| ALIAS2_SIFID | Double |  ||
| ALIAS3_DIR | String |  ||
| ALIAS3_STRNAME | String |  ||
| ALIAS3_TYPE | String |  ||
| ALIAS3_SIFID | Double |  ||
| ALIAS4_DIR | String |  ||
| ALIAS4_STRNAME | String |  ||
| ALIAS4_TYPE | String |  ||
| ALIAS4_SIFID | Double |  ||
|||||
| FTIMP | Double | Impedance value for travel time (minutes) in from-to segment direction based on design speed for each street class. ||
| TFIMP | Double | Impedance value for travel time (minutes) in to-from segment direction based on design speed for each street class. ||
| SPEED | SmallInteger | Speed limit indicator actual values; List of values; 15	15 MPH; 25	25 MPH; 35	35 MPH; 45	45 MPH ||
| MAIN_DIST | String | Metro Lousiville Public Works Street Maintenance District designation ||
| MAPNO | String | Key to location in LOJIC Street Atlas ||
| OWNER_NAME | String | Indicates street ownership; Description source; Metro Public Works; List of values; Federal	Federal Street Ownership; Metro	Metro Louisville Street Ownership; State	Kentucky State Government Ownership; Private	Private Ownership; [Individual City Names]	Name of the City that owns thr street ||
| OWNER_ABRV | String | Ownership abbreviation ||
| MUNI_NAME | String | Municipality the from node is located within. ||
| ONE_WAY | String | One-way designation; FT or blank. ||
| ROUTE_LBL | String | Label text ||
| MAIN_RESP | String | Indicates maintenance responsibility; List of values; Metro	Metro Maintenance Responsibility; Metroctr	Metroctr Maintenance Responsibility; State	State Maintenance Responsibility; 2nd Class City	2nd Class City Maintenance Responsibility; 3rd Class City	3rd Class City Maintenance Responsibility; 4th Class City	4th Class City Maintenance Responsibility; 5th Class City	5th Class City Maintenance Responsibility; 6th Class City	6th Class City Maintenance Responsibility; Non-Metro	Maintenance responsibility of non-government owner group. ||
| MAIN_ABRV | String | Maintenance abbreviation ||
| COUNDIST | SmallInteger | Louisville Metro Council district number: 1-26 ||
| ENTERED_BY | String | Editor that added the feature ||
| ENTERED_ON | Date | Date feature was added ||
| UPDATED_BY | String | Editor that updated the feature ||
| UPDATED_ON | Date | Date the feature was updated ||


This table was generated by some version of the code following this cell.
BLANKLINE = | | | | |

In [7]:
# scraping metadata from LOJIC

# imports
import re
import pandas as pd

# constants
metadata_path = "/Users/bencampbell/code/county_coverage/data/raw/centerlines_column_metadata.txt"

FIELDNAME = re.compile('\s*Field\s*([A-Z0-9]+)')

In [8]:
# parsing centerline metadata 
FIELDNAME = re.compile('\s*Field\s*([A-Z0-9_]+)')
FIELDID = re.compile("Field\s*([A-Z0-9_]+).*")

def parse_fieldname_data(metadata_lines):
    page = list()
    name = 'never appears' 
        
    # break up file to sections 
    for line in metadata_lines:
        line = line.strip()
        m = FIELDID.match(line)
        if m:
            name = m.groups()[0]
            info = list()
            memo = {"name": name, 'info':info}
            page.append(memo)
        elif line.startswith("Hide"):
            assert name in line
        elif line: # ignore empty lines
            info.append(line) 

    # parse infomation in each section
    for section_data in page:
        info = section_data.pop('info')
        index = 0
        for line in info:
            index += 1
            if line.startswith("*\u2009"):
                key, value = line.lstrip("*\u2009").split("\u2003", maxsplit=1)
                section_data[key.lower()] = value
            elif line.startswith("Field description"):
                break
        section_data['description'] = info[index:]
    return page

def get_fieldname_metadata(filepath=metadata_path):
    with open(filepath) as file:
        out = parse_fieldname_data(file)
    return pd.DataFrame.from_dict(out)

fieldname_metadata = get_fieldname_metadata()
fieldname_metadata

,name,alias,data type,width,precision,scale,description
0,LENGTH,LENGTH,Double,8,38,8,[Length of the segment in feet; duplication of...
1,SIFCODE,SIFCODE,String,4,0,0,[Street code number from the Metro Street Inde...
2,LOW_ADDRESS,LOW_ADDRESS,String,5,0,0,[Lowest address number within a centerline seg...
3,UNITID2,UNITID2,String,20,0,0,[Unique identifier for Midas asset management ...
4,FROM_ADDRESS,FROM_ADDRESS,Integer,4,10,0,[Beginning address for centerline segment]
...,...,...,...,...,...,...,...
71,ALIAS3_SIFID,ALIAS3_SIFID,Double,8,38,8,[]
72,ALIAS4_DIR,ALIAS4_DIR,String,2,0,0,[]
73,ALIAS4_STRNAME,ALIAS4_STRNAME,String,30,0,0,[]
74,ALIAS4_TYPE,ALIAS4_TYPE,String,4,0,0,[]
75,ALIAS4_SIFID,ALIAS4_SIFID,Double,8,38,8,[]

In [9]:
# get type info
dtypes = fieldname_metadata[['name', 'data type']]

# dtypes['data type'].unique() ->
['Double' 'String' 'Integer' 'OID' 'Geometry' 'SmallInteger' 'Date']


dtypes[dtypes['data type'] == 'Date'] 
# ENTERED_ON and UPDATE_ON have Date dtype. Don't need these columns, 
# so I'll treat Dates like a string to parse later if needed. 
# same for 

def change_type(type_value):
    return {
        'Double': float,
        'String': str,
        'Integer': int,
        'SmallInteger': int,
    }.get(type_value, type_value)

dtypes[dtypes['data type'] == 'Geometry']

     name data type
12  SHAPE  Geometry

In [10]:
# convert scraped data to markdown

def pass1(lines):
    memo = list()
    data = list()
    for line in lines:
        line = line.strip()
        if line.startswith("Hide"):
            data.append(memo)
            memo = list()
        elif line == "►":
            pass
        elif line:
            memo.append(line)
    return data

def pass2(data):
    out = dict()
    name = data[0].split(maxsplit=1)[1]
    out['fieldname'] = name
    index = 0
    for line in data[1:]:
        index += 1
        if line.startswith("*\u2009"):
            key, value = line.lstrip("*\u2009").split("\u2003",maxsplit=1)
            out[key.lower()] = value
        elif line.startswith("Field description"):
            break
    out['description'] = data[index + 1:]
    return out

def parse_metadata(filepath):
    with open(filepath) as file:
        chunks = pass1(file)
    return list(pass2(chunk) for chunk in chunks)
    
parse_metadata(metadata_path)

org = pd.DataFrame.from_dict(parse_metadata(metadata_path))

#all(org.fieldname == org.alias) # good. can delete one column

org = org[['fieldname', 'data type', 'description']]

org.to_markdown()

def make_markdown_table(dataframe):
    # create header
    col_names = ["|"]
    sep = ["|"]

    add_columns = ['notes'] # add any extra column names you want here. 
    add_columns_mkd = len(add_columns) * " |"
    df_columns = list(dataframe.columns)
    df_columns.extend(add_columns)

    for column in df_columns:
        col_names.append(f" {column} |")
        sep.append(f"-{'-'*len(column)}-|")
    # create markdown text
    markdown = [''.join(col_names), ''.join(sep)]
    for _, info in dataframe.iterrows():
        description = "; ".join(info.description)
        line = f"| {info.name} | {info['data type']} | {description} |"
        line += add_columns_mkd
        markdown.append(line)
    return markdown

#print('\n'.join(make_markdown_table(fieldname_metadata[['name', 'alias', 'data type', 'description']])))

In [55]:
# generate markdown


def generate_markdown(data):
    page = list()
    data_columns = list(data.columns)
    extra_columns = ['notes']
    add_columns = ' | '.join(extra_columns)
    header = "| {} | {} |".format(' | '.join(data_columns), add_columns)
    blank_line = "| {} |" +  ' | '.join('' for x in extra_columns) + "|"

    
    page.append(header)
    page.append(''.join('-' if char != '|' else char for char in header))
    for _, row in data[data_columns].iterrows():
        g = blank_line.format(' | '.join(str(v) for v in row)) # more general form of this function
        page.append(g)
        #print(g)
    return page

#print(*page, sep='\n')

def get_fieldname_metadata(filepath=metadata_path):
    with open(filepath) as file:
        out = parse_fieldname_data(file)
    return pd.DataFrame.from_dict(out)

fd = get_fieldname_metadata()
fd.description = fd.description.apply('; '.join)

all(fd.name == fd.alias) # False; not all match
fd[fd.name != fd.alias] # name == SHAPE but alias == SHAPE.LEN
# json data uses SHAPELEN
# no key SHAPE exists in json. 
# fd[fd.name=='SHAPE'].alias = "SHAPELEN"
# will fix this manually

fd = fd[['alias', 'data type', 'description']]

In [56]:

print(*generate_markdown(fd), sep = '\n')

#for _, row in fd.iterrows():
#    print(row)

| alias | data type | description | notes |
|-------|-----------|-------------|-------|
| LENGTH | Double | Length of the segment in feet; duplication of Shape.Length column due to ArcGIS software limitation ||
| SIFCODE | String | Street code number from the Metro Street Index File (SIF) table ||
| LOW_ADDRESS | String | Lowest address number within a centerline segment.  This could differ from FROM_ADDRESS because a FROM_ADDRESS number could be the highest number within the range but the location is at the starting segment of a one way street. ||
| UNITID2 | String | Unique identifier for Midas asset management system ||
| FROM_ADDRESS | Integer | Beginning address for centerline segment ||
| OBJECTID | OID | Internal feature number.; Description source; ESRI; Description of values Sequential unique whole numbers that are automatically generated. ||
| TO_ADDRESS | Integer | Ending address for centerline segment ||
| LFROM | Integer | From house number for left side of street ||
| LTO | Integer | To house number for left side of street ||
| RFROM | Integer | From house number for right side of street ||
| RTO | Integer | To house number for right side of street ||
| MUNI_NAME | String | Municipality the from node is located within. ||
| SHAPE | Geometry | Feature geometry.; * Description source; ESRI; * Description of values Coordinates defining the features. ||
| SHAPE.LEN | Double | Length of line segment in feet; Description source; ESRI ||
| RWCOMPKEYPARENT | Integer | Previous RWCompKey number ||
| ONE_WAY | String | One-way designation; FT or blank. ||
| AVDIR | String | Street direction (N, S, E, W); used for creating geocoding indexes ||
| AVPRETYPE | String | Pre Street Type (ie. USHY, BLVD, PL, AVE);  used for creating geocoding indexes ||
| AVSTNAME | String | Street Name; used for creating geocoding indexes ||
| COMPTYPE | Integer | Unique identifier for Midas asset management system ||
| AVSTTYPE | String | Street Type; used for creating geocoding indexes ||
| AVSUFDIR | String | Street Suffix Direction; used for creating geocoding indexes ||
| LOCROSSPR | String | Prefix Name of Cross Street on Low address end of street segment. ||
| LOCROSSNA | String | Name of cross street on Low address end of street segment. ||
| LOCROSSSU | String | Suffix name of cross street on low address end of street segment. ||
| LOCROSSSIF | String | Sifcode of the low cross street ||
| HICROSSPR | String | Prefix name of cross street on high address end of street segment. ||
| HICROSSNA | String | Name of cross street on high address end of street segment ||
| HICROSSSU | String | Suffix name of cross street on high address end of street segment.; Description of values Sequential unique whole numbers that are automatically generated. ||
| HICROSSSIF | String | Sifcode of the high cross street ||
| RWCOMPKEY | Integer | Unique Identifier for each arc feature in Midas asset management system ||
| FTIMP | Double | Impedance value for travel time (minutes) in from-to segment direction based on design speed for each street class. ||
| TFIMP | Double | Impedance value for travel time (minutes) in to-from segment direction based on design speed for each street class. ||
| SPEED | SmallInteger | Speed limit indicator actual values; List of values; 15	15 MPH; 25	25 MPH; 35	35 MPH; 45	45 MPH ||
| MAIN_DIST | String | Metro Lousiville Public Works Street Maintenance District designation ||
| MAPNO | String | Key to location in LOJIC Street Atlas ||
| OWNER_NAME | String | Indicates street ownership; Description source; Metro Public Works; List of values; Federal	Federal Street Ownership; Metro	Metro Louisville Street Ownership; State	Kentucky State Government Ownership; Private	Private Ownership; [Individual City Names]	Name of the City that owns thr street ||
| OWNER_ABRV | String | Ownership abbreviation ||
| SIFID | Integer | Integer Street Index File number; alternate to SIFCODE ||
| ROADNAME | String | Street direction, name, type and suffix direction ||
| DIR | String | Direction; N, S, E, W ||
| STRNAME | String | Street name ||
| TYPE | String | Street type; ie. AVE, RD, ST, etal. ||
| MAIN_RESP | String | Indicates maintenance responsibility; List of values; Metro	Metro Maintenance Responsibility; Metroctr	Metroctr Maintenance Responsibility; State	State Maintenance Responsibility; 2nd Class City	2nd Class City Maintenance Responsibility; 3rd Class City	3rd Class City Maintenance Responsibility; 4th Class City	4th Class City Maintenance Responsibility; 5th Class City	5th Class City Maintenance Responsibility; 6th Class City	6th Class City Maintenance Responsibility; Non-Metro	Maintenance responsibility of non-government owner group. ||
| MAIN_ABRV | String | Maintenance abbreviation ||
| COUNDIST | SmallInteger | Louisville Metro Council district number: 1-26 ||
| CORE_CLASS | String | Street class from Metro Louisville Comp Plan; List of values; Expressway	Expressway Street Class from Metro Louisville Comp Plan; Interstate Ramps	Interstate Ramps Street Class from Metro Louisville Comp Plan; Major Arterial	Major Arterial Street Class from Metro Louisville Comp Plan; Minor Arterial	Minor Arterial Street Class from Metro Louisville Comp Plan; Primary Collector	Primary Collector Street Class from Metro Louisville Comp Plan; Secondary Collector	Secondary Collector Street Class from Metro Louisville Comp Plan; Local	Local Street Class from Metro Louisville Comp Plan; Pedestrian Walkways	Pedestrian Walkways Street Class from Metro Louisville Comp Plan; Unclassified	Unclassified Street Class from Metro Louisville Comp Plan ||
| SIFIDLOW | Integer | Integer Street Index File number of lower cross street ||
| SIFIDHI | Integer | Integer Street Index File number of higher cross street ||
| STCL_CLASS | SmallInteger | Street class; Description source; Metro Public Works; List of values; 1	Expressway; 2	Interstate Ramp; 3	Major Arterial; 4	Minor Aterial; 5	Primary Collector; 6	Secondary Collector; 7	Local; 8	Pedestrian Walkway; 9	Response Route; 99	Inactive ||
| ZIP_LEFT | Integer | Zip Code of left side of street ||
| ZIP_RIGHT | Integer | Zip Code of right side of street ||
| CLASS_ABRV | String | Street class abreviation ||
| COMPKEY | Integer | Unique identifier for Midas asset management system ||
| UNITID | String | Unique identifier for Midas asset management system ||
| ENTERED_BY | String | Editor that added the feature ||
| ENTERED_ON | Date | Date feature was added ||
| UPDATED_BY | String | Editor that updated the feature ||
| UPDATED_ON | Date | Date the feature was updated ||
| ROUTE_LBL | String | Label text ||
| ALIAS1_DIR | String |  ||
| ALIAS1_STRNAME | String |  ||
| ALIAS1_TYPE | String |  ||
| ALIAS1_SIFID | Double |  ||
| ALIAS2_DIR | String |  ||
| ALIAS2_STRNAME | String |  ||
| ALIAS2_TYPE | String |  ||
| ALIAS2_SIFID | Double |  ||
| ALIAS3_DIR | String |  ||
| ALIAS3_STRNAME | String |  ||
| ALIAS3_TYPE | String |  ||
| ALIAS3_SIFID | Double |  ||
| ALIAS4_DIR | String |  ||
| ALIAS4_STRNAME | String |  ||
| ALIAS4_TYPE | String |  ||
| ALIAS4_SIFID | Double |  ||

| name | alias | data type | description | notes |
|------|-------|-----------|-------------|-------|
| LENGTH | LENGTH | Double | Length of the segment in feet; duplication of Shape.Length column due to ArcGIS software limitation ||
| SIFCODE | SIFCODE | String | Street code number from the Metro Street Index File (SIF) table ||
| LOW_ADDRESS | LOW_ADDRESS | String | Lowest address number within a centerline segment.  This could differ from FROM_ADDRESS because a FROM_ADDRESS number could be the highest number within the range but the location is at the starting segment of a one way street. ||
| UNITID2 | UNITID2 | String | Unique identifier for Midas asset management system ||
| FROM_ADDRESS | FROM_ADDRESS | Integer | Beginning address for centerline segment ||
| OBJECTID | OBJECTID | OID | Internal feature number.; Description source; ESRI; Description of values Sequential unique whole numbers that are automatically generated. ||
| TO_ADDRESS | TO_ADDRESS | Integer | Ending address for centerline segment ||
| LFROM | LFROM | Integer | From house number for left side of street ||
| LTO | LTO | Integer | To house number for left side of street ||
| RFROM | RFROM | Integer | From house number for right side of street ||
| RTO | RTO | Integer | To house number for right side of street ||
| MUNI_NAME | MUNI_NAME | String | Municipality the from node is located within. ||
| SHAPE | SHAPE | Geometry | Feature geometry.; * Description source; ESRI; * Description of values Coordinates defining the features. ||
| SHAPE | SHAPE.LEN | Double | Length of line segment in feet; Description source; ESRI ||
| RWCOMPKEYPARENT | RWCOMPKEYPARENT | Integer | Previous RWCompKey number ||
| ONE_WAY | ONE_WAY | String | One-way designation; FT or blank. ||
| AVDIR | AVDIR | String | Street direction (N, S, E, W); used for creating geocoding indexes ||
| AVPRETYPE | AVPRETYPE | String | Pre Street Type (ie. USHY, BLVD, PL, AVE);  used for creating geocoding indexes ||
| AVSTNAME | AVSTNAME | String | Street Name; used for creating geocoding indexes ||
| COMPTYPE | COMPTYPE | Integer | Unique identifier for Midas asset management system ||
| AVSTTYPE | AVSTTYPE | String | Street Type; used for creating geocoding indexes ||
| AVSUFDIR | AVSUFDIR | String | Street Suffix Direction; used for creating geocoding indexes ||
| LOCROSSPR | LOCROSSPR | String | Prefix Name of Cross Street on Low address end of street segment. ||
| LOCROSSNA | LOCROSSNA | String | Name of cross street on Low address end of street segment. ||
| LOCROSSSU | LOCROSSSU | String | Suffix name of cross street on low address end of street segment. ||
| LOCROSSSIF | LOCROSSSIF | String | Sifcode of the low cross street ||
| HICROSSPR | HICROSSPR | String | Prefix name of cross street on high address end of street segment. ||
| HICROSSNA | HICROSSNA | String | Name of cross street on high address end of street segment ||
| HICROSSSU | HICROSSSU | String | Suffix name of cross street on high address end of street segment.; Description of values Sequential unique whole numbers that are automatically generated. ||
| HICROSSSIF | HICROSSSIF | String | Sifcode of the high cross street ||
| RWCOMPKEY | RWCOMPKEY | Integer | Unique Identifier for each arc feature in Midas asset management system ||
| FTIMP | FTIMP | Double | Impedance value for travel time (minutes) in from-to segment direction based on design speed for each street class. ||
| TFIMP | TFIMP | Double | Impedance value for travel time (minutes) in to-from segment direction based on design speed for each street class. ||
| SPEED | SPEED | SmallInteger | Speed limit indicator actual values; List of values; 15	15 MPH; 25	25 MPH; 35	35 MPH; 45	45 MPH ||
| MAIN_DIST | MAIN_DIST | String | Metro Lousiville Public Works Street Maintenance District designation ||
| MAPNO | MAPNO | String | Key to location in LOJIC Street Atlas ||
| OWNER_NAME | OWNER_NAME | String | Indicates street ownership; Description source; Metro Public Works; List of values; Federal	Federal Street Ownership; Metro	Metro Louisville Street Ownership; State	Kentucky State Government Ownership; Private	Private Ownership; [Individual City Names]	Name of the City that owns thr street ||
| OWNER_ABRV | OWNER_ABRV | String | Ownership abbreviation ||
| SIFID | SIFID | Integer | Integer Street Index File number; alternate to SIFCODE ||
| ROADNAME | ROADNAME | String | Street direction, name, type and suffix direction ||
| DIR | DIR | String | Direction; N, S, E, W ||
| STRNAME | STRNAME | String | Street name ||
| TYPE | TYPE | String | Street type; ie. AVE, RD, ST, etal. ||
| MAIN_RESP | MAIN_RESP | String | Indicates maintenance responsibility; List of values; Metro	Metro Maintenance Responsibility; Metroctr	Metroctr Maintenance Responsibility; State	State Maintenance Responsibility; 2nd Class City	2nd Class City Maintenance Responsibility; 3rd Class City	3rd Class City Maintenance Responsibility; 4th Class City	4th Class City Maintenance Responsibility; 5th Class City	5th Class City Maintenance Responsibility; 6th Class City	6th Class City Maintenance Responsibility; Non-Metro	Maintenance responsibility of non-government owner group. ||
| MAIN_ABRV | MAIN_ABRV | String | Maintenance abbreviation ||
| COUNDIST | COUNDIST | SmallInteger | Louisville Metro Council district number: 1-26 ||
| CORE_CLASS | CORE_CLASS | String | Street class from Metro Louisville Comp Plan; List of values; Expressway	Expressway Street Class from Metro Louisville Comp Plan; Interstate Ramps	Interstate Ramps Street Class from Metro Louisville Comp Plan; Major Arterial	Major Arterial Street Class from Metro Louisville Comp Plan; Minor Arterial	Minor Arterial Street Class from Metro Louisville Comp Plan; Primary Collector	Primary Collector Street Class from Metro Louisville Comp Plan; Secondary Collector	Secondary Collector Street Class from Metro Louisville Comp Plan; Local	Local Street Class from Metro Louisville Comp Plan; Pedestrian Walkways	Pedestrian Walkways Street Class from Metro Louisville Comp Plan; Unclassified	Unclassified Street Class from Metro Louisville Comp Plan ||
| SIFIDLOW | SIFIDLOW | Integer | Integer Street Index File number of lower cross street ||
| SIFIDHI | SIFIDHI | Integer | Integer Street Index File number of higher cross street ||
| STCL_CLASS | STCL_CLASS | SmallInteger | Street class; Description source; Metro Public Works; List of values; 1	Expressway; 2	Interstate Ramp; 3	Major Arterial; 4	Minor Aterial; 5	Primary Collector; 6	Secondary Collector; 7	Local; 8	Pedestrian Walkway; 9	Response Route; 99	Inactive ||
| ZIP_LEFT | ZIP_LEFT | Integer | Zip Code of left side of street ||
| ZIP_RIGHT | ZIP_RIGHT | Integer | Zip Code of right side of street ||
| CLASS_ABRV | CLASS_ABRV | String | Street class abreviation ||
| COMPKEY | COMPKEY | Integer | Unique identifier for Midas asset management system ||
| UNITID | UNITID | String | Unique identifier for Midas asset management system ||
| ENTERED_BY | ENTERED_BY | String | Editor that added the feature ||
| ENTERED_ON | ENTERED_ON | Date | Date feature was added ||
| UPDATED_BY | UPDATED_BY | String | Editor that updated the feature ||
| UPDATED_ON | UPDATED_ON | Date | Date the feature was updated ||
| ROUTE_LBL | ROUTE_LBL | String | Label text ||
| ALIAS1_DIR | ALIAS1_DIR | String |  ||
| ALIAS1_STRNAME | ALIAS1_STRNAME | String |  ||
| ALIAS1_TYPE | ALIAS1_TYPE | String |  ||
| ALIAS1_SIFID | ALIAS1_SIFID | Double |  ||
| ALIAS2_DIR | ALIAS2_DIR | String |  ||
| ALIAS2_STRNAME | ALIAS2_STRNAME | String |  ||
| ALIAS2_TYPE | ALIAS2_TYPE | String |  ||
| ALIAS2_SIFID | ALIAS2_SIFID | Double |  ||
| ALIAS3_DIR | ALIAS3_DIR | String |  ||
| ALIAS3_STRNAME | ALIAS3_STRNAME | String |  ||
| ALIAS3_TYPE | ALIAS3_TYPE | String |  ||
| ALIAS3_SIFID | ALIAS3_SIFID | Double |  ||
| ALIAS4_DIR | ALIAS4_DIR | String |  ||
| ALIAS4_STRNAME | ALIAS4_STRNAME | String |  ||
| ALIAS4_TYPE | ALIAS4_TYPE | String |  ||
| ALIAS4_SIFID | ALIAS4_SIFID | Double |  ||